#!/usr/bin/env python3
"""
build_site.py — turn a page inventory into a multi-page static site, reading
repo files only.

WHY THIS EXISTS: the operator ruled that site content must be sourced from
the repo so drift between a repo's positioning decisions and its public site
becomes STRUCTURALLY impossible, not something a review happens to catch.
The concrete incident that forced the point: the Neotoma page's anti-profile
still excluded people who "need zero-install onboarding" after a merged
decision had explicitly retracted that exclusion, because the page held a
hand-copied version of a positioning fact instead of rendering the current
one. This generator is how a page renders the current one.

INPUT CONTRACT (what this script reads, and only this):
  1. A page inventory: execution/scripts/site_generator/inventory/<product>.json
     One entry per page; matches the PAGE INVENTORY shape declared on
     build-landing-page Stage 1 (.claude/skills/build-landing-page/SKILL.md,
     "Extending to a site: the page inventory"). Each page names its
     rendered_page_template and, per section, a CONTENT ORIGIN:
       - "authored"           -> a repo markdown path (README, docs/, a
                                  foundation doc). Rendered as-is; the site
                                  never copies its sentences elsewhere.
       - "positioning_mirror" -> a docs/positioning/<product>/<slug>.md file
                                  generated by render_positioning_docs.py
                                  (PR #1137) from a Neotoma target_persona /
                                  analysis / research_finding entity. Read
                                  the CURRENT file on disk; never cached,
                                  never re-derived from memory of what the
                                  entity used to say.
       - "page_specific"      -> a small JSON file under content/<product>/
                                  holding copy that exists only to make this
                                  one page read well (a headline, a CTA
                                  label). This is the ONE kind of content
                                  this generator's inventory is allowed to
                                  hold verbatim.
  2. Design tokens: execution/scripts/site_generator/design_tokens/<product>.json
     Generated by render_design_tokens.py from the shared design_system
     Neotoma entity (ent_72e01f1008653b601be1a956) — never hand-edited, never
     invented here. See that script's module docstring.
  3. Whatever repo files the inventory's "authored" and "positioning_mirror"
     sections point at (README.md, docs/positioning/**).

This script makes ZERO Neotoma calls. That is load-bearing, not incidental:
"the site reads repo files, all of them — some authored, some generated. It
does not read Neotoma at build time" is the property that keeps Neotoma
canonical for positioning and the repo canonical for reference without a
site build depending on live credentials. Anything that needs Neotoma
(design tokens, positioning mirrors) has its OWN separate render step that
runs first and leaves a file behind; this script only ever reads files.

OUTPUT: dist/site/<product>/<slug>/index.html (or dist/site/<product>/index.html
for the root page), each a complete static HTML document — no build step,
no JS framework, no server required to view it. This is deliberately the
simplest format `actions/upload-pages-artifact` (what neotoma.io's own
deploy-pages-site.yml workflow already uses) can ship: that workflow uploads
a directory of static files, and this generator's output IS one. It does not
touch neotoma.io's existing site_pages/ output or its build pipeline (a
Vite/React/Playwright-prerendered SPA — a different, larger system this
generator does not replace or compete with; see the PR description for why).

TEMPLATE ENGINE: this repo runs stdlib-only Python in every generator script
(render_plan_docs.py, render_agent_docs.py, the hooks) and has no Jinja2 (or
similar) dependency installed. Rather than add one for a single script, this
module uses plain Python string building via the small helpers in
templates/render.py — no new third-party dependency, consistent with the
rest of execution/scripts/.

DESIGN-SYSTEM INTERFACE this generator expects (see render_design_tokens.py
for the exact shape): a JSON object with `shared` (spacing_system,
border_radius, anti_patterns, positioning_principles, scope — identical
across products) and `product` (color_palette, type_scale — per-product
theme). A design_system entity that does not yet exist for a product is a
STOP, not a fallback to invented defaults — see resolve_design_tokens()
below and "Never silently substitute a default" (CLAUDE.md scope rules,
build-landing-page's own closing scope rules).

FULL WEB CAPABILITY: unlike a Neotoma rendered_page (CSP blocks external
scripts; inline SVG only), this generator's output is a normal static site
with no such restriction — it can load web fonts, ship a <script> file,
use CSS animations, etc. The design_system tokens this generator consumes
assume that full capability; nothing here narrows it to rendered_page limits.

Usage:
    build_site.py <product>                 # inventory -> dist/site/<product>/
    build_site.py <product> --check          # exit 1 if dist/ differs from
                                              # what the inventory+sources
                                              # would produce right now
    build_site.py <product> --out <dir>      # override output directory
                                              # (used by the preview server)

Env: none required — this script reads only repo-relative files.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
GEN_DIR = Path(__file__).resolve().parent
INVENTORY_DIR = GEN_DIR / "inventory"
DESIGN_TOKENS_DIR = GEN_DIR / "design_tokens"
CONTENT_DIR = GEN_DIR / "content"
DEFAULT_OUT_DIR = REPO_ROOT / "dist" / "site"

sys.path.insert(0, str(GEN_DIR))
from templates import render as tpl  # noqa: E402


class BuildBlocker(Exception):
    """Raised when the build cannot proceed honestly — a missing source, a
    missing design system, an unresolvable section. Per build-landing-page's
    closing scope rule: 'a page built on an invented ICP is worse than a
    stopped run, because nothing marks it as invented.' The same holds for a
    site build silently skipping a section or fabricating design tokens."""


def load_inventory(product: str) -> dict:
    path = INVENTORY_DIR / f"{product}.json"
    if not path.exists():
        raise BuildBlocker(
            f"no page inventory for product '{product}' at {path.relative_to(REPO_ROOT)}"
        )
    return json.loads(path.read_text())


def resolve_design_tokens(inventory: dict) -> dict:
    rel = inventory.get("design_tokens")
    if not rel:
        raise BuildBlocker("inventory does not declare a design_tokens path")
    path = GEN_DIR / rel
    if not path.exists():
        raise BuildBlocker(
            f"design tokens not found at {path.relative_to(REPO_ROOT)} — "
            f"run render_design_tokens.py first; this generator does not "
            f"invent visual tokens (see build_site.py module docstring)"
        )
    return json.loads(path.read_text())


def resolve_section(product: str, section: dict) -> dict:
    """Resolve one section's content per its declared origin. Returns a dict
    always carrying `_resolved: bool` and, on failure, `_blocker: str` — a
    section that cannot be resolved is reported, never silently dropped or
    filled with placeholder text (build-landing-page's own rule: a missing
    stage entity is the finding, not something to paper over)."""
    origin = section.get("origin")
    source = section.get("source")

    if origin == "page_specific":
        path = GEN_DIR / source
        if not path.exists():
            return {
                "_resolved": False,
                "_blocker": f"page_specific source missing: {source}",
            }
        data = json.loads(path.read_text())
        return {"_resolved": True, "origin": origin, "data": data}

    if origin == "authored":
        path = REPO_ROOT / source
        if not path.exists():
            return {
                "_resolved": False,
                "_blocker": f"authored source missing: {source}",
            }
        return {
            "_resolved": True,
            "origin": origin,
            "markdown": path.read_text(),
            "source_path": source,
        }

    if origin == "positioning_mirror":
        path = REPO_ROOT / source
        if not path.exists():
            # This is the expected, honest state as of this generator's first
            # version: render_positioning_docs.py ships in PR #1137, which is
            # open and unmerged as of this writing. Report it as a blocker
            # rather than fabricating positioning copy or silently omitting
            # the section — see the PR-status note in this repo's PR
            # description for the generator itself.
            return {
                "_resolved": False,
                "_blocker": (
                    f"positioning mirror missing: {source} (source entity "
                    f"{section.get('source_entity_id', 'unknown')}) — generate it with "
                    f"execution/scripts/render_positioning_docs.py once PR #1137 "
                    f"(feat/positioning-projection) is merged, or run it from that "
                    f"branch directly"
                ),
            }
        return {
            "_resolved": True,
            "origin": origin,
            "markdown": path.read_text(),
            "source_path": source,
            "source_entity_id": section.get("source_entity_id"),
        }

    return {"_resolved": False, "_blocker": f"unknown content origin: {origin!r}"}


def build_page(product: str, page: dict, tokens: dict) -> tuple[str, list[str]]:
    """Render one page. Returns (html, blockers) — blockers is non-empty when
    one or more sections could not be resolved; the page still renders with
    those sections visibly marked, so a `--check` or a human reviewer sees
    exactly what is missing rather than a page that looks complete but
    silently dropped content."""
    blockers: list[str] = []
    resolved_sections = []
    for section in page.get("sections", []):
        r = resolve_section(product, section)
        if not r["_resolved"]:
            blockers.append(f"{page['slug']}#{section['id']}: {r['_blocker']}")
        resolved_sections.append((section["id"], r))

    html = tpl.render_page(
        product=product, page=page, sections=resolved_sections, tokens=tokens
    )
    return html, blockers


def build(product: str, out_dir: Path) -> list[str]:
    inventory = load_inventory(product)
    tokens = resolve_design_tokens(inventory)

    all_blockers: list[str] = []
    written: list[Path] = []
    for page in inventory["pages"]:
        html, blockers = build_page(product, page, tokens)
        all_blockers.extend(blockers)

        slug = page["slug"]
        page_dir = out_dir / product if slug == "index" else out_dir / product / slug
        page_dir.mkdir(parents=True, exist_ok=True)
        out_path = page_dir / "index.html"
        out_path.write_text(html)
        written.append(out_path)

    # Copy static asset passthrough (none yet for ateles beyond inline CSS,
    # but the hook exists so a later page can add one without a generator
    # change).
    print(f"built {len(written)} page(s) for '{product}' -> {out_dir / product}")
    for p in written:
        print(f"  {p.relative_to(REPO_ROOT)}")
    if all_blockers:
        print(f"\n{len(all_blockers)} section(s) could not be resolved:")
        for b in all_blockers:
            print(f"  BLOCKED: {b}")
    return all_blockers


def check(product: str, out_dir: Path) -> int:
    """Rebuild each page in memory (never touching disk for the rebuild
    itself) and diff against what is currently written under out_dir — same
    drift contract as the other repo generators' --check. Blockers still
    fail --check: an unresolved section means the site does not yet
    honestly reflect its declared sources."""
    inventory = load_inventory(product)
    tokens = resolve_design_tokens(inventory)

    blockers: list[str] = []
    diffs: list[str] = []
    for page in inventory["pages"]:
        html, page_blockers = build_page(product, page, tokens)
        blockers.extend(page_blockers)
        slug = page["slug"]
        rel = (
            Path(product) / "index.html"
            if slug == "index"
            else Path(product) / slug / "index.html"
        )
        on_disk = out_dir / rel
        if not on_disk.exists():
            diffs.append(f"missing on disk: {rel}")
            continue
        if on_disk.read_text() != html:
            diffs.append(f"content differs: {rel}")

    if blockers:
        print(f"CHECK FAILED — {len(blockers)} unresolved section(s):")
        for b in blockers:
            print(f"  BLOCKED: {b}")
        return 1
    if diffs:
        print(f"CHECK FAILED — dist/site/{product} differs from a fresh build:")
        for d in diffs:
            print(f"  {d}")
        return 1
    print(
        f"site check OK — dist/site/{product} matches a fresh build from the inventory, with no unresolved sections"
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("product", help="product slug (e.g. ateles)")
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify dist/ matches a fresh build, and no section is unresolved",
    )
    parser.add_argument(
        "--out",
        default=str(DEFAULT_OUT_DIR),
        help="output directory (default: dist/site)",
    )
    args = parser.parse_args()

    out_dir = Path(args.out)
    if not out_dir.is_absolute():
        out_dir = REPO_ROOT / out_dir

    try:
        if args.check:
            return check(args.product, out_dir)
        blockers = build(args.product, out_dir)
        return 1 if blockers else 0
    except BuildBlocker as exc:
        print(f"BUILD BLOCKED: {exc}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
