#!/usr/bin/env python3
"""
build_site.py — turn a page inventory into a multi-page static site, reading
repo files only.

WHY THIS EXISTS: the operator ruled that site content must be sourced from
the repo so drift between a repo's positioning decisions and its public site
becomes STRUCTURALLY impossible, not something a review happens to catch.
The concrete incident that forced the point: the Neotoma page's anti-profile
still excluded people who "need zero-install onboarding" after a merged
decision had explicitly retracted that exclusion, because the page held a
hand-copied version of a positioning fact instead of rendering the current
one. This generator is how a page renders the current one.

INPUT CONTRACT (what this script reads, and only this):
  1. A page inventory: execution/scripts/site_generator/inventory/<product>.json
     One entry per page; matches the PAGE INVENTORY shape declared on
     build-landing-page Stage 1 (.claude/skills/build-landing-page/SKILL.md,
     "Extending to a site: the page inventory"). Each page names its
     rendered_page_template and, per section, a CONTENT ORIGIN:
       - "authored"           -> a repo markdown path (README, docs/, a
                                  foundation doc), or a JSON composition under
                                  docs/sites/. Markdown sources pair with a
                                  bounded public-copy projection; authored JSON
                                  is the durable visual/content composition.
       - "positioning_mirror" -> a docs/positioning/<product>/<slug>.md file
                                  generated by render_positioning_docs.py
                                  from a Neotoma target_persona / analysis /
                                  research_finding entity. Read
                                  the CURRENT file on disk; never cached,
                                  never re-derived from memory of what the
                                  entity used to say. Public routes project it
                                  rather than pasting the analysis verbatim.
       - "page_specific"      -> a small JSON file under content/<product>/
                                  holding transitions or CTAs that exist only
                                  to make this one page read well. Structural
                                  compositions belong under docs/sites/.
  2. Design tokens: execution/scripts/site_generator/design_tokens/<product>.json
     Generated by render_design_tokens.py from the product's canonical
     design_system entity — never hand-edited, never invented here. See that
     script's module docstring.
  3. Whatever repo files the inventory's "authored" and "positioning_mirror"
     sections point at (README.md, docs/positioning/**).

This script makes ZERO Neotoma calls. That is load-bearing, not incidental:
"the site reads repo files, all of them — some authored, some generated. It
does not read Neotoma at build time" is the property that keeps Neotoma
canonical for positioning and the repo canonical for reference without a
site build depending on live credentials. Anything that needs Neotoma
(design tokens, positioning mirrors) has its OWN separate render step that
runs first and leaves a file behind; this script only ever reads files.

OUTPUT: dist/site/<product>/<slug>/index.html (or dist/site/<product>/index.html
for the root page), each a complete static HTML document — no build step,
no JS framework, no server required to view it. This is deliberately the
simplest format `actions/upload-pages-artifact` (what neotoma.io's own
deploy-pages-site.yml workflow already uses) can ship: that workflow uploads
a directory of static files, and this generator's output IS one. It does not
touch neotoma.io's existing site_pages/ output or its build pipeline (a
Vite/React/Playwright-prerendered SPA — a different, larger system this
generator does not replace or compete with; see the PR description for why).

TEMPLATE ENGINE: this repo runs stdlib-only Python in every generator script
(render_plan_docs.py, render_agent_docs.py, the hooks) and has no Jinja2 (or
similar) dependency installed. Rather than add one for a single script, this
module uses plain Python string building via the small helpers in
templates/render.py — no new third-party dependency, consistent with the
rest of execution/scripts/.

DESIGN-SYSTEM INTERFACE this generator expects (see render_design_tokens.py
for the exact shape): a JSON object with `identity` (spacing_system,
border_radius, anti_patterns, positioning_principles, scope) and `product`
(color_palette, type_scale). `shared` remains accepted for old test fixtures,
but checked-in product artifacts use their distinct canonical identities. A
design_system entity that does not yet exist for a product is a STOP, not a
fallback to invented defaults — see resolve_design_tokens()
below and "Never silently substitute a default" (CLAUDE.md scope rules,
build-landing-page's own closing scope rules).

FULL WEB CAPABILITY: unlike a Neotoma rendered_page (CSP blocks external
scripts; inline SVG only), this generator's output is a normal static site
with no such restriction — it can load web fonts, ship a <script> file,
use CSS animations, etc. The design_system tokens this generator consumes
assume that full capability; nothing here narrows it to rendered_page limits.

Usage:
    build_site.py <product>                 # inventory -> dist/site/<product>/
    build_site.py <product> --check          # exit 1 if dist/ differs from
                                              # what the inventory+sources
                                              # would produce right now
    build_site.py <product> --out <dir>      # override output directory
                                              # (used by the preview server)

Env: none required — this script reads only repo-relative files.
"""

from __future__ import annotations

import argparse
import html as html_mod
import json
import re
import sys
import tempfile
from pathlib import Path, PurePosixPath

REPO_ROOT = Path(__file__).resolve().parents[3]
GEN_DIR = Path(__file__).resolve().parent
INVENTORY_DIR = GEN_DIR / "inventory"
DESIGN_TOKENS_DIR = GEN_DIR / "design_tokens"
CONTENT_DIR = GEN_DIR / "content"
DEFAULT_OUT_DIR = REPO_ROOT / "dist" / "site"

sys.path.insert(0, str(GEN_DIR))
from templates import render as tpl  # noqa: E402


class BuildBlocker(Exception):
    """Raised when the build cannot proceed honestly — a missing source, a
    missing design system, an unresolvable section. Per build-landing-page's
    closing scope rule: 'a page built on an invented ICP is worse than a
    stopped run, because nothing marks it as invented.' The same holds for a
    site build silently skipping a section or fabricating design tokens."""


def load_inventory(product: str) -> dict:
    path = INVENTORY_DIR / f"{product}.json"
    if not path.exists():
        raise BuildBlocker(
            f"no page inventory for product '{product}' at {path.relative_to(REPO_ROOT)}"
        )
    return json.loads(path.read_text())


def resolve_design_tokens(inventory: dict) -> dict:
    rel = inventory.get("design_tokens")
    if not rel:
        raise BuildBlocker("inventory does not declare a design_tokens path")
    path = GEN_DIR / rel
    if not path.exists():
        raise BuildBlocker(
            f"design tokens not found at {path.relative_to(REPO_ROOT)} — "
            f"run render_design_tokens.py first; this generator does not "
            f"invent visual tokens (see build_site.py module docstring)"
        )
    return json.loads(path.read_text())


def resolve_section(product: str, section: dict) -> dict:
    """Resolve one section's content per its declared origin. Returns a dict
    always carrying `_resolved: bool` and, on failure, `_blocker: str` — a
    section that cannot be resolved is reported, never silently dropped or
    filled with placeholder text (build-landing-page's own rule: a missing
    stage entity is the finding, not something to paper over)."""
    origin = section.get("origin")
    source = section.get("source")

    if origin == "page_specific":
        path = GEN_DIR / source
        if not path.exists():
            return {
                "_resolved": False,
                "_blocker": f"page_specific source missing: {source}",
            }
        data = json.loads(path.read_text())
        composition_keys = {"proof", "grants", "levels", "correction"}
        if composition_keys.intersection(data):
            return {
                "_resolved": False,
                "_blocker": (
                    f"page_specific source {source} holds composition, not a transition"
                ),
            }
        concept_blocker = _attach_concept_film(data)
        if concept_blocker:
            return {"_resolved": False, "_blocker": concept_blocker}
        return {"_resolved": True, "origin": origin, "data": data}

    if origin == "authored":
        path = REPO_ROOT / source
        if not path.exists():
            return {
                "_resolved": False,
                "_blocker": f"authored source missing: {source}",
            }
        if path.suffix == ".json":
            try:
                data = json.loads(path.read_text())
            except json.JSONDecodeError as exc:
                return {
                    "_resolved": False,
                    "_blocker": f"authored source invalid JSON: {source}: {exc.msg}",
                }
            concept_blocker = _attach_concept_film(data)
            if concept_blocker:
                return {"_resolved": False, "_blocker": concept_blocker}
            return {
                "_resolved": True,
                "origin": origin,
                "data": data,
                "source_path": source,
            }
        markdown = path.read_text()
        headings = section.get("headings", [])
        available = set(re.findall(r"(?m)^##\s+(.+?)\s*$", markdown))
        missing = [heading for heading in headings if heading not in available]
        if missing:
            return {
                "_resolved": False,
                "_blocker": f"authored source {source} is missing headings: {', '.join(missing)}",
            }
        resolved = {
            "_resolved": True,
            "origin": origin,
            "markdown": markdown,
            "source_path": source,
            "link_base": section.get("link_base"),
        }
        return _attach_public_projection(resolved, section)

    if origin == "positioning_mirror":
        path = REPO_ROOT / source
        if not path.exists():
            return {
                "_resolved": False,
                "_blocker": (
                    f"positioning mirror missing: {source} (source entity "
                    f"{section.get('source_entity_id', 'unknown')}) — generate it with "
                    f"execution/scripts/render_positioning_docs.py"
                ),
            }
        markdown = path.read_text()
        headings = section.get("headings", [])
        available = set(re.findall(r"(?m)^##\s+(.+?)\s*$", markdown))
        missing = [heading for heading in headings if heading not in available]
        if missing:
            return {
                "_resolved": False,
                "_blocker": f"positioning mirror {source} is missing headings: {', '.join(missing)}",
            }
        resolved = {
            "_resolved": True,
            "origin": origin,
            "markdown": markdown,
            "source_path": source,
            "source_entity_id": section.get("source_entity_id"),
        }
        return _attach_public_projection(resolved, section)

    return {"_resolved": False, "_blocker": f"unknown content origin: {origin!r}"}


def _attach_concept_film(data: dict) -> str | None:
    """Resolve and validate an optional hero concept-film brief.

    The static semantic visual remains the poster and reduced-motion fallback.
    A future local asset can be attached without changing the public-copy or
    layout contract, but the brief must remain silent, short, local, and within
    the declared performance budget.
    """
    brief_rel = data.get("concept_film_brief")
    if not brief_rel:
        return None
    path = (GEN_DIR / brief_rel).resolve()
    if not path.is_relative_to(GEN_DIR.resolve()):
        return f"concept film brief escapes the generator directory: {brief_rel}"
    if not path.exists():
        return f"concept film brief missing: {brief_rel}"
    brief = json.loads(path.read_text())
    duration = brief.get("duration_seconds")
    if not isinstance(duration, (int, float)) or not 6 <= duration <= 10:
        return f"concept film brief {brief_rel} must declare a 6–10 second loop"
    playback = brief.get("playback") or {}
    for attribute in ("muted", "autoplay", "playsinline", "loop"):
        if playback.get(attribute) is not True:
            return f"concept film brief {brief_rel} must enable {attribute}"
    if playback.get("reduced_motion") != "static_poster":
        return f"concept film brief {brief_rel} must use a static reduced-motion poster"
    performance = brief.get("performance") or {}
    max_bytes = performance.get("max_bytes")
    if not isinstance(max_bytes, int) or max_bytes > 1_800_000:
        return f"concept film brief {brief_rel} exceeds the 1.8 MB media budget"
    asset = brief.get("asset") or {}
    for field in ("video_src", "fallback_src", "poster_src"):
        value = asset.get(field) or ""
        if value:
            source_path = PurePosixPath(value)
            if (
                not value.startswith("/assets/")
                or ".." in source_path.parts
                or source_path.name == ""
            ):
                return f"concept film brief {brief_rel} has invalid {field}"
    if asset.get("enabled_in_hero") is False:
        for field in ("video_src", "fallback_src", "poster_src"):
            asset[field] = ""
        data["concept_film"] = brief
        return None
    asset_bindings = (
        ("repository_video_path", "public_video_path", "video_src"),
        ("repository_fallback_path", "public_fallback_path", "fallback_src"),
        ("repository_poster_path", "public_poster_path", "poster_src"),
    )
    for repository_field, public_field, source_field in asset_bindings:
        repository_value = asset.get(repository_field) or ""
        public_value = asset.get(public_field) or ""
        configured_source = asset.get(source_field) or ""
        if not repository_value:
            if configured_source:
                return (
                    f"concept film brief {brief_rel} configures {source_field} "
                    f"without {repository_field}"
                )
            continue
        repository_path = (REPO_ROOT / repository_value).resolve()
        if not repository_path.is_relative_to(REPO_ROOT.resolve()):
            return f"concept film brief {brief_rel} escapes the repository"
        if repository_path.exists():
            if not public_value:
                return (
                    f"concept film brief {brief_rel} has {repository_field} "
                    f"without {public_field}"
                )
            public_path = PurePosixPath(public_value)
            if (
                not public_value.startswith("/assets/")
                or ".." in public_path.parts
                or public_path.name == ""
            ):
                return f"concept film brief {brief_rel} has invalid {public_field}"
            if repository_path.stat().st_size > max_bytes:
                return (
                    f"concept film asset {repository_value} exceeds the "
                    f"{max_bytes}-byte media budget"
                )
            if configured_source and configured_source != public_value:
                return (
                    f"concept film brief {brief_rel} has mismatched "
                    f"{source_field} and {public_field}"
                )
            asset[source_field] = public_value
        elif configured_source:
            return f"concept film asset missing: {repository_value}"
    data["concept_film"] = brief
    return None


def _collect_concept_assets(inventory: dict) -> tuple[dict[Path, bytes], list[str]]:
    """Collect declared local film assets into the generated product tree.

    Briefed-but-not-yet-generated assets are intentionally absent. Once a
    file appears at a declared repository path, the generator copies it to
    its public path and ``_attach_concept_film`` enables the matching source.
    """
    assets: dict[Path, bytes] = {}
    blockers: list[str] = []
    brief_paths = {
        section_data.get("concept_film_brief")
        for page in inventory.get("pages", [])
        for section in page.get("sections", [])
        if section.get("origin") in ("page_specific", "authored")
        and section.get("source", "").endswith(".json")
        for section_data in [
            json.loads(
                (
                    (GEN_DIR if section.get("origin") == "page_specific" else REPO_ROOT)
                    / section["source"]
                ).read_text()
            )
            if (
                (GEN_DIR if section.get("origin") == "page_specific" else REPO_ROOT)
                / section["source"]
            ).exists()
            else {}
        ]
        if section_data.get("concept_film_brief")
    }
    for brief_rel in sorted(brief_paths):
        brief_path = (GEN_DIR / brief_rel).resolve()
        if not brief_path.is_relative_to(GEN_DIR.resolve()):
            blockers.append(
                f"concept film brief escapes the generator directory: {brief_rel}"
            )
            continue
        if not brief_path.exists():
            continue
        brief = json.loads(brief_path.read_text())
        asset = brief.get("asset") or {}
        if asset.get("enabled_in_hero") is False:
            continue
        max_bytes = (brief.get("performance") or {}).get("max_bytes", 0)
        for repository_field, public_field in (
            ("repository_video_path", "public_video_path"),
            ("repository_fallback_path", "public_fallback_path"),
            ("repository_poster_path", "public_poster_path"),
        ):
            repository_value = asset.get(repository_field) or ""
            public_value = asset.get(public_field) or ""
            if not repository_value:
                continue
            repository_path = (REPO_ROOT / repository_value).resolve()
            if not repository_path.is_relative_to(REPO_ROOT.resolve()):
                blockers.append(
                    f"concept film brief {brief_rel} escapes the repository"
                )
                continue
            if not repository_path.exists():
                continue
            if not public_value.startswith("/assets/"):
                blockers.append(
                    f"concept film brief {brief_rel} has invalid {public_field}"
                )
                continue
            public_path = PurePosixPath(public_value)
            if ".." in public_path.parts or public_path.name == "":
                blockers.append(
                    f"concept film brief {brief_rel} has invalid {public_field}"
                )
                continue
            if (
                isinstance(max_bytes, int)
                and repository_path.stat().st_size > max_bytes
            ):
                blockers.append(
                    f"concept film asset {repository_value} exceeds the "
                    f"{max_bytes}-byte media budget"
                )
                continue
            assets[Path(*public_path.parts[1:])] = repository_path.read_bytes()
    return assets, blockers


def _attach_public_projection(resolved: dict, section: dict) -> dict:
    """Attach a reader-facing projection while retaining the evidence source.

    Positioning and foundation documents are allowed to carry internal
    locators, citations, analysis narration, and implementation bookkeeping.
    A public page is not. The projection is a small, reviewable adapter whose
    ``_source`` declaration must match the source already resolved above.
    This keeps provenance durable without turning it into public copy.
    """
    projection_rel = section.get("projection")
    if not projection_rel:
        return resolved
    projection_path = GEN_DIR / projection_rel
    if not projection_path.exists():
        return {
            "_resolved": False,
            "_blocker": f"public projection missing: {projection_rel}",
        }
    projection = json.loads(projection_path.read_text())
    declared = projection.get("_source") or {}
    if declared.get("path") != resolved["source_path"]:
        return {
            "_resolved": False,
            "_blocker": (
                f"public projection {projection_rel} declares source "
                f"{declared.get('path')!r}, expected {resolved['source_path']!r}"
            ),
        }
    expected_entity = resolved.get("source_entity_id")
    if expected_entity and declared.get("entity_id") != expected_entity:
        return {
            "_resolved": False,
            "_blocker": (
                f"public projection {projection_rel} declares entity "
                f"{declared.get('entity_id')!r}, expected {expected_entity!r}"
            ),
        }
    resolved["public_projection"] = projection
    resolved["projection_path"] = projection_rel
    return resolved


def build_page(
    product: str, page: dict, site_pages: list[dict], tokens: dict
) -> tuple[str, list[str]]:
    """Render one page. Returns (html, blockers) — blockers is non-empty when
    one or more sections could not be resolved; the page still renders with
    those sections visibly marked, so a `--check` or a human reviewer sees
    exactly what is missing rather than a page that looks complete but
    silently dropped content."""
    blockers: list[str] = []
    resolved_sections = []
    for section in page.get("sections", []):
        r = resolve_section(product, section)
        # Presentation is declared by the inventory. Keep it beside the
        # resolved source so the renderer can select a bounded, source-backed
        # cut without duplicating the source prose in page-specific JSON.
        r["section"] = section
        if not r["_resolved"]:
            blockers.append(f"{page['slug']}#{section['id']}: {r['_blocker']}")
        resolved_sections.append((section["id"], r))

    html = tpl.render_page(
        product=product,
        page=page,
        site_pages=site_pages,
        sections=resolved_sections,
        tokens=tokens,
    )
    return html, blockers


def render_site(product: str) -> tuple[dict[Path, str | bytes], list[str]]:
    """Resolve every page into an in-memory output tree.

    Keeping resolution separate from disk writes makes the build fail closed:
    one unresolved section prevents the product tree from being replaced, so
    a preview can never mistake a partly generated site for a complete one.
    """
    inventory = load_inventory(product)
    tokens = resolve_design_tokens(inventory)

    all_blockers: list[str] = []
    rendered: dict[Path, str | bytes] = {}
    for page in inventory["pages"]:
        html, blockers = build_page(product, page, inventory["pages"], tokens)
        all_blockers.extend(blockers)

        slug = page["slug"]
        rel = Path("index.html") if slug == "index" else Path(slug) / "index.html"
        rendered[rel] = html
    concept_assets, asset_blockers = _collect_concept_assets(inventory)
    rendered.update(concept_assets)
    all_blockers.extend(asset_blockers)
    all_blockers.extend(_validate_site(product, inventory, rendered))
    return rendered, all_blockers


def _validate_site(
    product: str, inventory: dict, rendered: dict[Path, str | bytes]
) -> list[str]:
    """Bind the product-page constraints the generator can verify mechanically."""
    blockers: list[str] = []
    routes = {
        "/" if page["slug"] == "index" else f"/{page['slug']}/"
        for page in inventory["pages"]
    }
    for page in inventory["pages"]:
        for section in page.get("sections", []):
            source = section.get("source", "")
            needs_projection = section.get("origin") == "positioning_mirror" or (
                section.get("origin") == "authored" and not source.endswith(".json")
            )
            if needs_projection and not section.get("projection"):
                blockers.append(
                    f"{page['slug']}#{section['id']}: public source section has no "
                    "reader-facing projection"
                )
    for rel, html in rendered.items():
        if isinstance(html, bytes):
            continue
        if product in {"neotoma", "ateles"}:
            for disclosure in ("<details", "<summary"):
                if disclosure in html.casefold():
                    blockers.append(
                        f"{rel}: public product routes must not hide copy in "
                        f"{disclosure[1:]} disclosures"
                    )
        for href in re.findall(r'href="(/[^"]*)"', html):
            path = href.split("#", 1)[0]
            if path and path not in routes:
                blockers.append(f"{rel}: unresolved internal link {href}")
        blockers.extend(_public_copy_leaks(rel, html))

    homepage = next(
        (page for page in inventory["pages"] if page["slug"] == "index"), None
    )
    if not homepage:
        blockers.append("inventory has no index page")
        return blockers
    sequence = [section["id"] for section in homepage.get("sections", [])]
    required = ["hero", "failures", "mechanism"]
    if product in ("neotoma", "ateles") and sequence[:3] != required:
        blockers.append(
            "homepage must begin hero -> failures -> mechanism; "
            f"found {' -> '.join(sequence[:3])}"
        )

    home_html = rendered.get(Path("index.html"), "")
    assert isinstance(home_html, str)
    category = {
        "neotoma": "The system of record for AI agents",
        "ateles": "The operating system for agent organizations",
    }.get(product)
    if category and category not in home_html:
        blockers.append(f"homepage is missing settled category noun: {category}")
    if product == "neotoma":
        hero_match = re.search(
            r'(?s)<section class="takeover-hero record-hero" id="hero">(.*?)</section>',
            home_html,
        )
        hero_html = hero_match.group(1) if hero_match else ""
        if not hero_match:
            blockers.append("homepage is missing the Neotoma cinematic hero")
        for marker in ("<svg", "concept-film-overlay", "record-semantic-overlay"):
            if marker in hero_html:
                blockers.append(
                    f"Neotoma cinematic hero must not contain a semantic overlay: {marker}"
                )
        for marker in (
            'data-concept-film-active="true"',
            '<video class="concept-film-media"',
            '<img class="concept-film-poster-media"',
        ):
            if marker not in hero_html:
                blockers.append(f"Neotoma cinematic hero is missing media: {marker}")
        banned_claims = (
            "your agent forgot",
            "your agents forgot",
            "agents forget",
            "neotoma is a state layer",
            "neotoma is agent memory",
            "neotoma is a memory system",
        )
        lower = home_html.casefold()
        for claim in banned_claims:
            if claim in lower:
                blockers.append(f"homepage contains retired Neotoma framing: {claim}")
    if product == "ateles":
        for marker in (
            "swarm-field",
            "swarm-member",
            "handoff-signal",
            "authorization-seal",
        ):
            if marker not in home_html:
                blockers.append(f"homepage is missing Ateles swarm marker: {marker}")
        if "org-link" in home_html:
            blockers.append("homepage gives the Ateles swarm permanent graph edges")
        if "seal-board" in home_html:
            blockers.append(
                "homepage still renders the seal as Ateles's primary metaphor"
            )
    return blockers


def _public_copy_leaks(rel: Path, document: str | bytes) -> list[str]:
    """Reject internal workbench vocabulary from generated public pages."""
    if isinstance(document, bytes):
        return []
    # A blocked build is never published or written over the last complete
    # tree. Its diagnostic names the missing repo source intentionally; do not
    # mistake that operator-only error panel for reader-facing copy.
    public_document = re.sub(
        r'(?is)<div\s+class="blocker"[^>]*>.*?</div>', " ", document
    )
    without_code = re.sub(
        r"(?is)<(?:style|script)\b[^>]*>.*?</(?:style|script)>", " ", public_document
    )
    visible = html_mod.unescape(re.sub(r"(?s)<[^>]+>", " ", without_code))
    visible = re.sub(r"\s+", " ", visible)
    patterns = {
        "entity id": r"\bent_[0-9a-f]{12,}\b",
        "candidate label": r"\bCandidate\s+[A-Z]\b",
        "entity-type label": r"\b(?:research_finding|target_persona|category_definition)\b",
        "repo filename": r"\b(?:README|[a-z][a-z0-9_-]*)\.md\b",
        "source rail": r"\bSOURCE\s*[·:]\s*(?:ent_|[^\s<]+\.md\b|research_finding\b)",
        "internal scope notation": r"\[(?:role|blast|handoff|attention):",
        "analysis narration": r"\b(?:source-backed|rendered from|this preview)\b",
        "phase bookkeeping": r"\b(?:phase|stage)\s+[0-9]+\b",
    }
    leaks = []
    for label, pattern in patterns.items():
        if re.search(pattern, visible, flags=re.IGNORECASE):
            leaks.append(f"{rel}: public copy leaks {label}")
    if "The distributed-authority operating layer for governed initiative" in visible:
        leaks.append(f"{rel}: public copy contains superseded Ateles category phrase")
    return leaks


def _replace_product_tree(
    product: str, out_dir: Path, rendered: dict[Path, str | bytes]
) -> None:
    """Atomically replace one product's generated tree.

    The staging directory lives beside the target so both renames stay on the
    same filesystem. If the replacement fails, the previous tree is restored.
    Successful replacement also removes pages deleted from the inventory.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / product
    with tempfile.TemporaryDirectory(prefix=f".{product}-", dir=out_dir) as tmp:
        tmp_dir = Path(tmp)
        staged = tmp_dir / "next"
        previous = tmp_dir / "previous"
        for rel, content in rendered.items():
            path = staged / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            if isinstance(content, bytes):
                path.write_bytes(content)
            else:
                path.write_text(content)

        if target.exists():
            target.replace(previous)
        try:
            staged.replace(target)
        except Exception:
            if previous.exists() and not target.exists():
                previous.replace(target)
            raise


def _display_path(path: Path) -> Path:
    """Prefer a repo-relative path without rejecting explicit external outputs."""
    try:
        return path.relative_to(REPO_ROOT)
    except ValueError:
        return path


def build(product: str, out_dir: Path) -> list[str]:
    rendered, all_blockers = render_site(product)

    if all_blockers:
        print(f"BUILD BLOCKED — {len(all_blockers)} section(s) could not be resolved:")
        for b in all_blockers:
            print(f"  BLOCKED: {b}")
        print("existing output was left unchanged")
        return all_blockers

    _replace_product_tree(product, out_dir, rendered)
    page_count = sum(1 for rel in rendered if rel.name == "index.html")
    asset_count = len(rendered) - page_count
    asset_note = f" and {asset_count} media asset(s)" if asset_count else ""
    print(
        f"built {page_count} page(s){asset_note} for '{product}' -> {out_dir / product}"
    )
    for rel in sorted(rendered):
        print(f"  {_display_path(out_dir / product / rel)}")
    return all_blockers


def check(product: str, out_dir: Path) -> int:
    """Rebuild each page in memory (never touching disk for the rebuild
    itself) and diff against what is currently written under out_dir — same
    drift contract as the other repo generators' --check. Blockers still
    fail --check: an unresolved section means the site does not yet
    honestly reflect its declared sources."""
    rendered, blockers = render_site(product)
    diffs: list[str] = []
    product_dir = out_dir / product
    for rel, content in rendered.items():
        on_disk = product_dir / rel
        if not on_disk.exists():
            diffs.append(f"missing on disk: {rel}")
            continue
        on_disk_content = (
            on_disk.read_bytes() if isinstance(content, bytes) else on_disk.read_text()
        )
        if on_disk_content != content:
            diffs.append(f"content differs: {rel}")

    expected_paths = set(rendered)
    if product_dir.exists():
        actual_paths = {
            path.relative_to(product_dir)
            for path in product_dir.rglob("*")
            if path.is_file()
        }
        for rel in sorted(actual_paths - expected_paths):
            diffs.append(f"unexpected on disk: {rel}")

    if blockers:
        print(f"CHECK FAILED — {len(blockers)} unresolved section(s):")
        for b in blockers:
            print(f"  BLOCKED: {b}")
        return 1
    if diffs:
        print(
            f"CHECK FAILED — {_display_path(product_dir)} differs from a fresh build:"
        )
        for d in diffs:
            print(f"  {d}")
        return 1
    print(
        f"site check OK — {_display_path(product_dir)} matches a fresh build "
        "from the inventory, with no unresolved sections"
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("product", help="product slug (e.g. ateles)")
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify dist/ matches a fresh build, and no section is unresolved",
    )
    parser.add_argument(
        "--out",
        default=str(DEFAULT_OUT_DIR),
        help="output directory (default: dist/site)",
    )
    args = parser.parse_args()

    out_dir = Path(args.out)
    if not out_dir.is_absolute():
        out_dir = REPO_ROOT / out_dir

    try:
        if args.check:
            return check(args.product, out_dir)
        blockers = build(args.product, out_dir)
        return 1 if blockers else 0
    except BuildBlocker as exc:
        print(f"BUILD BLOCKED: {exc}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
