#!/usr/bin/env python3
"""
Process all 140 recipients from the latest Minted holiday card delivery.
Tags all recipients as having received the 2025 holiday card mailing.
"""

import os
import uuid
from datetime import date, datetime

import pandas as pd

PROJECT_ROOT = "/Users/markmhendrickson/Projects/personal"

# Delivery data from Minted MCP - 140 recipients
delivery_result = {
    "success": True,
    "endpoint": "https://addressbook.minted.com/api/contacts/groups/",
    "delivery_date": "2025-12-02T00:05:35.396065Z",
    "order_id": "851d49cf-df4b-4c7a-a24a-85f83679e983",
    "status": "Unknown",
    "recipient_count": 140,
    "recipients": [
        {
            "id": "3a6ca689-7daf-4727-a16b-430bb1c971e1",
            "name": "Bene Ade",
            "address1": "1572 Elk Ravine Way",
            "address2": "",
            "locality": "Roseville",
            "administrative_area": "California",
            "postal_code": "95661",
            "country": "US",
            "external_id": 379921242,
        },
        {
            "id": "ed88de03-4dfd-4f1a-ba52-f944a48a174d",
            "name": "Adu Family",
            "address1": "79 Linden Street",
            "address2": "",
            "locality": "Needham",
            "administrative_area": "MA",
            "postal_code": "02492",
            "country": "US",
            "external_id": 304352810,
        },
        {
            "id": "3aa8fa8e-90dd-47a0-aad5-f86cf9441524",
            "name": "Alba y Alex",
            "address1": "Avinguda de Catalunya, 37",
            "address2": "Casa",
            "locality": "Matadepera",
            "administrative_area": "Catalunya",
            "postal_code": "08230",
            "country": "ES",
            "external_id": 379921346,
        },
        {
            "id": "e594f811-13e5-4699-9ebd-bbeee4f97b2c",
            "name": "Sara & Alex",
            "address1": "Gran Via 220",
            "address2": "6, 1",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "08004",
            "country": "ES",
            "external_id": 304352783,
        },
        {
            "id": "551d6270-7843-45bd-a52e-ff556aed20c2",
            "name": "Bennett and Alice",
            "address1": "138 Byram Road",
            "address2": "",
            "locality": "Greenwich",
            "administrative_area": "CT",
            "postal_code": "06830",
            "country": "US",
            "external_id": 304352851,
        },
        {
            "id": "846e76a8-042c-4241-a322-bb891dcb9546",
            "name": "Rosa y Antonio",
            "address1": "Via Aurelia",
            "address2": "2 4, B",
            "locality": "Salou",
            "administrative_area": "Tarragona",
            "postal_code": "43840",
            "country": "ES",
            "external_id": 304352766,
        },
        {
            "id": "e4977c48-c2af-4c46-9f9a-7d63d1535218",
            "name": "Ariadna",
            "address1": "Carrer de Marià Aguiló, 22",
            "address2": "Bajos",
            "locality": "Barcelona",
            "administrative_area": "Catalunya",
            "postal_code": "08005",
            "country": "ES",
            "external_id": 379921446,
        },
        {
            "id": "82307474-c524-4553-8b40-264cdc1b9b39",
            "name": "Leorato and Azzolina Family",
            "address1": "Calle Bailen 151",
            "address2": "4-2",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "08037",
            "country": "ES",
            "external_id": 304352796,
        },
        {
            "id": "054ff874-e785-41b9-9648-3701706d4af8",
            "name": "Andrew & Ben",
            "address1": "401 Hamilton Street",
            "address2": "",
            "locality": "Albany",
            "administrative_area": "NY",
            "postal_code": "12210",
            "country": "US",
            "external_id": 304352861,
        },
        {
            "id": "ef29084e-5a9d-44d5-9cc5-79dcbcb191ef",
            "name": "The Beretti Family",
            "address1": "670 Ringwood Ave",
            "address2": "",
            "locality": "Menlo Park",
            "administrative_area": "Ca",
            "postal_code": "94025",
            "country": "US",
            "external_id": 304352814,
        },
        {
            "id": "0079edbd-085b-40a7-bd14-f1607cc702e6",
            "name": "The Refart Bergés family",
            "address1": "Aribau 134",
            "address2": "3, 1",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "08036",
            "country": "ES",
            "external_id": 304352805,
        },
        {
            "id": "e4c8b8e8-a589-4785-bedc-7359d74f6ad6",
            "name": "John Biggs",
            "address1": "6814 6th Avenue",
            "address2": "",
            "locality": "Brooklyn",
            "administrative_area": "NY",
            "postal_code": "11220",
            "country": "US",
            "external_id": 304352813,
        },
        {
            "id": "58913585-8a36-4be2-b2a0-0377549c03db",
            "name": "Elsa, Manu, Nico, Martina y Bimba",
            "address1": "Carrer de València, 176",
            "address2": "Piso 4, puerta 1",
            "locality": "Barcelona",
            "administrative_area": "Catalunya",
            "postal_code": "08011",
            "country": "ES",
            "external_id": 379921104,
        },
        {
            "id": "92f12b74-7841-4cf1-94c0-91fe0b322c46",
            "name": "Dana and Ethan Bloch",
            "address1": "7486 East Sonoran Trail",
            "address2": "",
            "locality": "Scottsdale",
            "administrative_area": "Arizona",
            "postal_code": "85255",
            "country": "US",
            "external_id": 379921223,
        },
        {
            "id": "71317911-8758-41c6-8557-aedc07b10e39",
            "name": "Fernanda Bonini",
            "address1": "Carrer Santa Madrona, 123",
            "address2": "2, 1",
            "locality": "Barcelona",
            "administrative_area": "Badalona",
            "postal_code": "08911",
            "country": "ES",
            "external_id": 304352791,
        },
        {
            "id": "89ae549b-ac40-4111-bab3-0e28fa08cfd6",
            "name": "Sabrina Somalo Bonini",
            "address1": "Carrer de Calàbria, 89",
            "address2": "3-3",
            "locality": "Barcelona",
            "administrative_area": "Catalunya",
            "postal_code": "08015",
            "country": "ES",
            "external_id": 304352860,
        },
        {
            "id": "138b5bab-967f-4069-bea3-05daf73ec99c",
            "name": "Oscar Sanchez Borras",
            "address1": "Angeles Santos 21",
            "address2": "4-2",
            "locality": "L'Hospitalet de Llobregat",
            "administrative_area": "Barcelona",
            "postal_code": "08907",
            "country": "ES",
            "external_id": 304352863,
        },
        {
            "id": "743f3101-6199-40c3-9bbf-f96ec04e25eb",
            "name": "Courtney and Mark Boswell",
            "address1": "379 Cherokee Pl SE",
            "address2": "",
            "locality": "Atlanta",
            "administrative_area": "GA",
            "postal_code": "30312",
            "country": "US",
            "external_id": 304352829,
        },
        {
            "id": "07e2634f-55df-495c-869b-805062a73901",
            "name": "John and Maxine Maroun Bowers",
            "address1": "P.O. Box 10661",
            "address2": "",
            "locality": "Jackson",
            "administrative_area": "WY",
            "postal_code": "83002",
            "country": "US",
            "external_id": 379921240,
        },
        {
            "id": "4e18199d-bb58-4523-954b-064d91aaee9c",
            "name": "Margaret & Peter Bowers",
            "address1": "1334 Bay View Heights",
            "address2": "",
            "locality": "Petoskey",
            "administrative_area": "MI",
            "postal_code": "49770",
            "country": "US",
            "external_id": 304352853,
        },
        {
            "id": "fd230148-3117-4182-9e6e-dc3f69da8e6f",
            "name": "Steve Breen",
            "address1": "640 West 4th Street",
            "address2": "Apartment 308",
            "locality": "Long Beach",
            "administrative_area": "CA",
            "postal_code": "90802",
            "country": "US",
            "external_id": 304352815,
        },
        {
            "id": "0025a278-23da-41e6-84db-d5225332750b",
            "name": "Carmen Company y Bruno",
            "address1": "Aribau 58",
            "address2": "Pral. 1a",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "08011",
            "country": "ES",
            "external_id": 304352804,
        },
        {
            "id": "2263dbee-6fce-4e8e-adbf-565dfc060051",
            "name": "Nat and Auston Bunsen",
            "address1": "3301 NE 1st Ave LPH1",
            "address2": "",
            "locality": "Miami",
            "administrative_area": "Florida",
            "postal_code": "33137",
            "country": "US",
            "external_id": 379921180,
        },
        {
            "id": "f56a2416-916a-4202-8ee5-13504e9573c2",
            "name": "Esther y Camille",
            "address1": "16 Passatge d'Alió",
            "address2": "1r pis",
            "locality": "Barcelona",
            "administrative_area": "Catalunya",
            "postal_code": "08037",
            "country": "ES",
            "external_id": 379919414,
        },
        {
            "id": "684c83d7-b310-43e1-b09b-b9a47c48f1f5",
            "name": "Silvia, Nacho, Eva y Candela",
            "address1": "Via Bellavista, 81",
            "address2": "Casa",
            "locality": "Pallejà",
            "administrative_area": "Catalunya",
            "postal_code": "08753",
            "country": "ES",
            "external_id": 379921418,
        },
        {
            "id": "ecb70301-f6c4-442a-90cf-821e83a8b4c8",
            "name": "Coro, Manu y Catalina",
            "address1": "386 Rue du Creuset",
            "address2": "",
            "locality": "Vedène",
            "administrative_area": "Provence-Alpes-Côte d'Azur",
            "postal_code": "84270",
            "country": "FR",
            "external_id": 381709042,
        },
        {
            "id": "2b5accf3-4e64-4a00-bd0f-0f41babb0a3c",
            "name": "Michael Cecchin",
            "address1": "Carrer Nena Casas, 61",
            "address2": "4-2",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "08017",
            "country": "ES",
            "external_id": 304352792,
        },
        {
            "id": "0a4de9e6-c376-4406-8987-618283e567e5",
            "name": "Paulina Cerda",
            "address1": "Rocafort, 259",
            "address2": "4, 1",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "08029",
            "country": "ES",
            "external_id": 304352771,
        },
        {
            "id": "47076122-d8a4-4423-ac79-0be7fa0581bc",
            "name": "Alex Chugunov",
            "address1": "Breton de los Herreros 55",
            "address2": "5-D",
            "locality": "Madrid",
            "administrative_area": "Madrid",
            "postal_code": "28003",
            "country": "ES",
            "external_id": 304352799,
        },
        {
            "id": "11349625-5721-465b-8602-7426b33a8266",
            "name": "The Cohen Chung Family",
            "address1": "Carrer Gran De Gracia, 7",
            "address2": "2-2",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "08012",
            "country": "ES",
            "external_id": 304352793,
        },
        {
            "id": "e8d89cf8-5b4e-4f7f-b0c6-6404bc4fc285",
            "name": "Sofia Clarke",
            "address1": "Havneholmen 72",
            "address2": "ST TH",
            "locality": "Copenhagen",
            "administrative_area": "Copenhagen",
            "postal_code": "1561",
            "country": "DK",
            "external_id": 304352781,
        },
        {
            "id": "ffa5bfb3-8cb2-45b7-8c19-687c1575fb60",
            "name": "Cora",
            "address1": "Carrer de Balmes, 53",
            "address2": "1-1",
            "locality": "Barcelona",
            "administrative_area": "Catalunya",
            "postal_code": "08007",
            "country": "ES",
            "external_id": 304352784,
        },
        {
            "id": "f55aa1f1-b106-4783-94e2-612d7c286e9d",
            "name": "Jonathan E Cowperthwait",
            "address1": "3189 21st Street",
            "address2": "",
            "locality": "San Francisco",
            "administrative_area": "CA",
            "postal_code": "94110",
            "country": "US",
            "external_id": 304352837,
        },
        {
            "id": "35571067-454f-43bb-927b-686425671b83",
            "name": "David",
            "address1": "Carrer de Pujades, 77",
            "address2": "4-4 (univrse)",
            "locality": "Barcelona",
            "administrative_area": "Catalunya",
            "postal_code": "08005",
            "country": "ES",
            "external_id": 381709102,
        },
        {
            "id": "1e8e6bd2-5937-4634-9c30-6a43dc698485",
            "name": "Jennifer & Dick",
            "address1": "516 Yale Avenue North",
            "address2": "#600",
            "locality": "Seattle",
            "administrative_area": "WA",
            "postal_code": "98109",
            "country": "US",
            "external_id": 304352821,
        },
        {
            "id": "6c7d197e-b9e7-4a51-97e5-00838fb93c1c",
            "name": "Silvia, Miguel y Emma",
            "address1": "Avinguda Cor de Jesús, 116",
            "address2": "4to C",
            "locality": "La Vall d'Uixó",
            "administrative_area": "Comunidad Valenciana",
            "postal_code": "12600",
            "country": "ES",
            "external_id": 379921120,
        },
        {
            "id": "f5c2b5df-f002-4e54-9424-b2328bc2e820",
            "name": "Can Ertugrul",
            "address1": "Gumpendorfer Straße 134–136, Top 9",
            "address2": "",
            "locality": "Vienna",
            "administrative_area": "Wien",
            "postal_code": "1060",
            "country": "AT",
            "external_id": 380048657,
        },
        {
            "id": "04c65e21-202a-4b4e-a70c-5bc622b0b865",
            "name": "Can Ertugrul",
            "address1": "Avenida de la Constitución 412",
            "address2": "3-1, Escalera A",
            "locality": "Casteldellfels",
            "administrative_area": "Barcelona",
            "postal_code": "08860",
            "country": "ES",
            "external_id": 304352803,
        },
        {
            "id": "5d4ded2b-3e58-4af1-aafb-33a934e9d2f1",
            "name": "Clara y Ezequiel",
            "address1": "Carrer de Roger de Flor, 253",
            "address2": "Local 2 y 3",
            "locality": "Barcelona",
            "administrative_area": "Catalunya",
            "postal_code": "08025",
            "country": "ES",
            "external_id": 379921486,
        },
        {
            "id": "dfa2ba42-e140-41b7-8399-57ef15ee244b",
            "name": "Ana Bragatti y Ricard Fayos",
            "address1": "Granja 9",
            "address2": "1, 2",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "08024",
            "country": "ES",
            "external_id": 304352782,
        },
        {
            "id": "c8b1078c-007a-47c7-ac99-227f48c437cd",
            "name": "Patricia y Ferran",
            "address1": "Carrer de Castellnou, 71",
            "address2": "1-2",
            "locality": "Barcelona",
            "administrative_area": "Catalunya",
            "postal_code": "08017",
            "country": "ES",
            "external_id": 379921313,
        },
        {
            "id": "3afdce6b-0856-457c-a980-2897c01b5a2a",
            "name": "Gloria Ferrer",
            "address1": "Cr. Muntaner, 120",
            "address2": "",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "8036",
            "country": "ES",
            "external_id": 304352788,
        },
        {
            "id": "453d20c2-af2a-4684-a6ff-c32cbe352b30",
            "name": "Francesca",
            "address1": "Diagonal, 84",
            "address2": "3-5 Escalera 1",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "08019",
            "country": "ES",
            "external_id": 304352786,
        },
        {
            "id": "52ec7d29-6a1b-41a3-9df9-de14026f7620",
            "name": "The Favorite Hungarian friend",
            "address1": "Avinguda Gaietana 16",
            "address2": "",
            "locality": "Alella",
            "administrative_area": "Barcelona",
            "postal_code": "08328",
            "country": "ES",
            "external_id": 304352800,
        },
        {
            "id": "13774cbe-6a78-43bb-b1c9-b6f36f56e68a",
            "name": "Beatriz Gallego",
            "address1": "Industria 27",
            "address2": "",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "08037",
            "country": "ES",
            "external_id": 304352780,
        },
        {
            "id": "d0ebc857-daba-4b3c-a73d-05f79a2f602b",
            "name": "Noemí Garcia",
            "address1": "Marques de Campo Sagrado, 25",
            "address2": "2-2",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "08015",
            "country": "ES",
            "external_id": 304352778,
        },
        {
            "id": "bf1ca464-47a8-4aee-9854-8dcc5c696e69",
            "name": "Karel Geldhof",
            "address1": "Carretera de Sarria a Vallvidrera, 246",
            "address2": "C-D, 1b",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "08017",
            "country": "ES",
            "external_id": 304352789,
        },
        {
            "id": "a501772d-a753-4253-aa79-dccfa59846ed",
            "name": "Ana, Gustavo y Gerardo",
            "address1": "Calle de Génova, 3",
            "address2": "3A",
            "locality": "Zaragoza",
            "administrative_area": "Aragón",
            "postal_code": "50007",
            "country": "ES",
            "external_id": 379921214,
        },
        {
            "id": "9f001b1b-3d69-4ccc-b547-a60b1f874271",
            "name": "Gloria",
            "address1": "C/ Reina Cristina 1, 3-1",
            "address2": "",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "08003",
            "country": "ES",
            "external_id": 379921315,
        },
        {
            "id": "adc2066a-f397-467a-9a31-3c1bb77325f0",
            "name": "Michael Gorelik",
            "address1": "424 West End Avenue",
            "address2": "Apt 2G",
            "locality": "New York",
            "administrative_area": "New York",
            "postal_code": "10024",
            "country": "US",
            "external_id": 380043596,
        },
        {
            "id": "b5bcdffa-6ee5-452f-92b4-707fa6aae93c",
            "name": "Tasha Graff",
            "address1": "38 Monroe Ct.",
            "address2": "",
            "locality": "Portland",
            "administrative_area": "ME",
            "postal_code": "04101",
            "country": "US",
            "external_id": 304352828,
        },
        {
            "id": "39c1dc65-94b0-448e-985c-0316de3f8585",
            "name": "Emilee & Grant",
            "address1": "1075 Underhills Road",
            "address2": "",
            "locality": "Oakland",
            "administrative_area": "CA",
            "postal_code": "94610",
            "country": "US",
            "external_id": 304352857,
        },
        {
            "id": "243147ab-882a-4bdb-9e4e-2572f5423054",
            "name": "Ducos-Ducq Guiu family",
            "address1": "C Tarragona, 12",
            "address2": "Escalera C, Bloque A, 1-1",
            "locality": "Salou",
            "administrative_area": "Tarragona",
            "postal_code": "43840",
            "country": "ES",
            "external_id": 304352798,
        },
        {
            "id": "befec6df-dc23-4009-87ad-95fc62124a82",
            "name": "Cristal Guzmán",
            "address1": "2315 Isabelle Ave",
            "address2": "",
            "locality": "San Mateo",
            "administrative_area": "CA",
            "postal_code": "94403",
            "country": "US",
            "external_id": 304352840,
        },
        {
            "id": "29d8782b-a41e-442a-bd1c-2f90ddbc2cfb",
            "name": "Nina & Tom Hayton",
            "address1": "Skalitzer StraBe  29",
            "address2": "",
            "locality": "Berlin",
            "administrative_area": "Berlin",
            "postal_code": "10999",
            "country": "DE",
            "external_id": 304352768,
        },
        {
            "id": "1d25b632-074b-41e0-accc-83a472b108c7",
            "name": "Yibriela Hechavarría",
            "address1": "Carrer del Penedès, 9, 3, 1",
            "address2": "",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "08012",
            "country": "ES",
            "external_id": 379921342,
        },
        {
            "id": "d48bc5fc-7a46-43b2-a656-25fac196189c",
            "name": "Inma, Rafa, Claudia y Helena",
            "address1": "Carrer Jaume Valls Canós, 15",
            "address2": "4D",
            "locality": "La Vall d'Uixó",
            "administrative_area": "Comunidad Valenciana",
            "postal_code": "12600",
            "country": "ES",
            "external_id": 379921134,
        },
        {
            "id": "a2218822-e2ce-485b-a75e-945eaa5c24c6",
            "name": "John & Nidy Hendrickson",
            "address1": "3016 Travis Pond Road",
            "address2": "",
            "locality": "Williamsburg",
            "administrative_area": "VA",
            "postal_code": "23185",
            "country": "US",
            "external_id": 304352838,
        },
        {
            "id": "83ed4a0f-56a1-4969-9c07-d3bfdee9ccce",
            "name": "Jorge & Danna Hendrickson",
            "address1": "147 King George St",
            "address2": "",
            "locality": "Daniel Island",
            "administrative_area": "SC",
            "postal_code": "29492",
            "country": "US",
            "external_id": 304352850,
        },
        {
            "id": "dd97184c-afd1-4b40-8420-292815239fac",
            "name": "Lisa & Dana Hendrickson",
            "address1": "365 Ambar Way",
            "address2": "",
            "locality": "Menlo Park",
            "administrative_area": "CA",
            "postal_code": "94025",
            "country": "US",
            "external_id": 304352830,
        },
        {
            "id": "db604985-d268-4d7c-8f8a-4395b069fc85",
            "name": "Paula & Miguel Hendrickson",
            "address1": "100 Barclay Street",
            "address2": "14J",
            "locality": "New York",
            "administrative_area": "NY",
            "postal_code": "10007",
            "country": "US",
            "external_id": 304352859,
        },
        {
            "id": "20b206bc-ae81-4145-8799-1bce2188526f",
            "name": "Kate & Henry",
            "address1": "2111 Tondolea Lane",
            "address2": "",
            "locality": "La Canada Flintridge",
            "administrative_area": "CA",
            "postal_code": "91011",
            "country": "US",
            "external_id": 304352842,
        },
        {
            "id": "f17448e7-9255-4b53-b16e-43ac296b7b2a",
            "name": "Anna Hinohara",
            "address1": "10605 1/2 Ashton Ave",
            "address2": "",
            "locality": "Los Angeles",
            "administrative_area": "CA",
            "postal_code": "90024",
            "country": "US",
            "external_id": 304352858,
        },
        {
            "id": "3063ce3e-aa2d-4a19-8fcf-df9bea2dd9d8",
            "name": "Amy Hsueh",
            "address1": "401 Harrison Street",
            "address2": "Apt 25G",
            "locality": "San Francisco",
            "administrative_area": "CA",
            "postal_code": "94105",
            "country": "US",
            "external_id": 304352827,
        },
        {
            "id": "ed7db31c-e58e-4212-8ef6-83bc822f3833",
            "name": "Rose & Jacob",
            "address1": "5928 Elliot Avenue",
            "address2": "",
            "locality": "Minneapolis",
            "administrative_area": "MN",
            "postal_code": "55417",
            "country": "US",
            "external_id": 304352818,
        },
        {
            "id": "161d8fe0-cfea-4dd1-a9c3-eef6f7a51223",
            "name": "Ana, Alex, Anna y Jan",
            "address1": "Carrer d'Amigó, 69",
            "address2": "Ático",
            "locality": "Barcelona",
            "administrative_area": "Catalunya",
            "postal_code": "08021",
            "country": "ES",
            "external_id": 379919407,
        },
        {
            "id": "cf74046a-65f2-46f9-9b34-d1726b3f1909",
            "name": "Amanda Janzen",
            "address1": "5920 Upton Ave S",
            "address2": "",
            "locality": "Minneapolis",
            "administrative_area": "Mn",
            "postal_code": "55410",
            "country": "US",
            "external_id": 304352819,
        },
        {
            "id": "630f36ad-440a-430f-835e-0b846203a845",
            "name": "Jesusa",
            "address1": "25 Carrer de Villarroel",
            "address2": "Entresuelo 2",
            "locality": "Barcelona",
            "administrative_area": "Catalunya",
            "postal_code": "08011",
            "country": "ES",
            "external_id": 379919419,
        },
        {
            "id": "0973932f-f199-40e2-8690-7e2939dc7b93",
            "name": "Carina Jocham",
            "address1": "Escorial 30",
            "address2": "4-2",
            "locality": "Barcelona",
            "administrative_area": "",
            "postal_code": "08024",
            "country": "ES",
            "external_id": 304352785,
        },
        {
            "id": "42aedfa6-520d-4604-b18d-2d4e8fe5ae0c",
            "name": "Emily & Jordan",
            "address1": "42 Brooks Avenue",
            "address2": "",
            "locality": "Arlington",
            "administrative_area": "MA",
            "postal_code": "02474",
            "country": "US",
            "external_id": 304352824,
        },
        {
            "id": "a7d55960-dd95-4a8d-a7cd-0075ff8ad98d",
            "name": "Irene, Guillermo, Mateo y Júlia",
            "address1": "Calle Doctor Severo Ochoa, 8",
            "address2": "3C",
            "locality": "Vall de Uxó",
            "administrative_area": "Comunidad Valenciana",
            "postal_code": "12600",
            "country": "ES",
            "external_id": 379919428,
        },
        {
            "id": "d2461263-6116-43be-bb3b-07103fb9df6b",
            "name": "The Kantor Family",
            "address1": "3520 E Camden St",
            "address2": "",
            "locality": "Tucson",
            "administrative_area": "AZ",
            "postal_code": "85716",
            "country": "US",
            "external_id": 304352833,
        },
        {
            "id": "4860060b-aa06-4a55-9cfd-a4b7934e10ca",
            "name": "Yoel Karaso",
            "address1": "Carrer de Bailen, 11",
            "address2": "Bajos",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "08010",
            "country": "ES",
            "external_id": 304352794,
        },
        {
            "id": "454eecab-658c-4a62-b83d-3e4f1bf88e5e",
            "name": "Steve and Karen",
            "address1": "640 W 4th St.",
            "address2": "Apt 308",
            "locality": "Long Beach",
            "administrative_area": "CA",
            "postal_code": "90802",
            "country": "US",
            "external_id": 304352816,
        },
        {
            "id": "13437063-f0f4-4092-9b04-ad13ebc92235",
            "name": "Jason Kincaid",
            "address1": "2355 Westwood Blvd",
            "address2": "#568",
            "locality": "Los Angeles",
            "administrative_area": "CA",
            "postal_code": "90064",
            "country": "US",
            "external_id": 304352839,
        },
        {
            "id": "a0dcd474-99f2-44a1-ae6b-c9860d17a08d",
            "name": "The Kinney Family",
            "address1": "322 Overcreek Drive",
            "address2": "",
            "locality": "Richardson",
            "administrative_area": "TX",
            "postal_code": "75080",
            "country": "US",
            "external_id": 304352836,
        },
        {
            "id": "467c0d33-e605-4e20-8b95-154760de2b5a",
            "name": "Sophia Kitter",
            "address1": "882 South Van Ness Avenue",
            "address2": "",
            "locality": "San Francisco",
            "administrative_area": "California",
            "postal_code": "94110",
            "country": "US",
            "external_id": 379921174,
        },
        {
            "id": "36aa137c-3f07-433b-94ed-e2f1dfc90d7a",
            "name": "Rebeca and Kristian",
            "address1": "Muntanya 76-78",
            "address2": "",
            "locality": "Cervelló",
            "administrative_area": "Barcelona",
            "postal_code": "08758",
            "country": "ES",
            "external_id": 379921351,
        },
        {
            "id": "3a72bf2c-4eb1-4f05-ae34-5f6ef4dc9eaa",
            "name": "Luisina y Leandro",
            "address1": "Travesia de la Figueira 50",
            "address2": "",
            "locality": "Medal",
            "administrative_area": "Asturias",
            "postal_code": "33716",
            "country": "ES",
            "external_id": 304352767,
        },
        {
            "id": "cf176bbd-beb3-40df-a71b-9315320f1dc9",
            "name": "Mona, Toño, Selma, Lara and Leo",
            "address2": "",
            "locality": "Hägersten",
            "administrative_area": "Stockholms län",
            "postal_code": "129 50",
            "country": "SE",
            "external_id": 379919701,
        },
        {
            "id": "1f7b79aa-8351-4545-b21f-56814ae6e49d",
            "name": "Sean Longstreet",
            "address1": "130 Les Etoyeres",
            "address2": "",
            "locality": "Montsûrs",
            "administrative_area": "Pays de la Loire",
            "postal_code": "53150",
            "country": "FR",
            "external_id": 379921323,
        },
        {
            "id": "479ec3f8-7289-45dc-8514-12f6f0e4ce47",
            "name": "Familia González López",
            "address1": "Nou de la Rambla 149",
            "address2": "SAT 1a",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "08004",
            "country": "ES",
            "external_id": 304352775,
        },
        {
            "id": "6a78c49f-ccc1-4fb7-bedd-ca29bf1558a9",
            "name": "Familia Van Der Lugt",
            "address1": "Albert Schweitzerplaats 401",
            "address2": "",
            "locality": "Rotterdam",
            "administrative_area": "South Holland",
            "postal_code": "3069 GK",
            "country": "NL",
            "external_id": 304352806,
        },
        {
            "id": "cd9923c4-22d5-45f8-8dd3-b961db4e8baa",
            "name": "Marta y Manel",
            "address1": "C/ Anna Maria Martinez, 16",
            "address2": "bajos",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "08041",
            "country": "ES",
            "external_id": 304352797,
        },
        {
            "id": "10709994-4204-4ef9-af87-0f624298c7c8",
            "name": "Manna-Montazeri",
            "address1": "4331 Pine Blossom Trail",
            "address2": "",
            "locality": "Houston",
            "administrative_area": "Texas",
            "postal_code": "77059",
            "country": "US",
            "external_id": 304352823,
        },
        {
            "id": "e57b7afb-fd03-474f-84d7-47ea5f9c1e34",
            "name": "The Marcyes",
            "address1": "1870 N 1900 E",
            "address2": "",
            "locality": "North Logan",
            "administrative_area": "UT",
            "postal_code": "84341",
            "country": "US",
            "external_id": 304352843,
        },
        {
            "id": "d1667534-446d-40a6-b656-e30863f85643",
            "name": "Ana, Bimba, Pablo y Mark",
            "address1": "Passatge d'Alio, 18",
            "address2": "bajos",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "08037",
            "country": "ES",
            "external_id": 304352774,
        },
        {
            "id": "a206488b-bf92-4cc8-b151-b8f9cff5cb25",
            "name": "Fabricio Rosa Marques",
            "address1": "57 Tannenweg",
            "address2": "",
            "locality": "Montabaur",
            "administrative_area": "Rheinland-Pfalz",
            "postal_code": "56410",
            "country": "DE",
            "external_id": 380044820,
        },
        {
            "id": "8c39532f-044c-4359-8ce2-7cd75ae224e0",
            "name": "Magda y Martí",
            "address1": "Ronda del Carril, 15",
            "address2": "Casa",
            "locality": "La Garriga",
            "administrative_area": "Cataluña",
            "postal_code": "08530",
            "country": "ES",
            "external_id": 379921258,
        },
        {
            "id": "54252927-68b7-4e73-880e-bca48c98cee4",
            "name": "Renata Martins",
            "address1": "Gran Via de les Corts Catalanes, 423",
            "address2": "4-3",
            "locality": "Barcelona",
            "administrative_area": "Catalunya",
            "postal_code": "08015",
            "country": "ES",
            "external_id": 304352772,
        },
        {
            "id": "e2d72647-8654-4bfa-8247-df9c8b4b6b23",
            "name": "Andrea and Matt",
            "address1": "3268 Braemar Road",
            "address2": "",
            "locality": "Shaker Heights",
            "administrative_area": "Ohio",
            "postal_code": "44120",
            "country": "US",
            "external_id": 380053056,
        },
        {
            "id": "771db5e5-c6dc-4265-a225-809e875a1091",
            "name": "Matt Matteson",
            "address1": "17336 Rimrock Drive",
            "address2": "",
            "locality": "Golden",
            "administrative_area": "CO",
            "postal_code": "80401",
            "country": "US",
            "external_id": 304352845,
        },
        {
            "id": "003a97ec-faa2-4a08-922f-c4cf2569af53",
            "name": "Ed McManus",
            "address1": "5465 Kales ave",
            "address2": "",
            "locality": "Oakland",
            "administrative_area": "CA",
            "postal_code": "94618",
            "country": "US",
            "external_id": 304352820,
        },
        {
            "id": "a92ae97f-6c66-49c8-bb65-6f8aff8b0b33",
            "name": "Nicole Melas",
            "address1": "440 Arguello Blvd",
            "address2": "Apt 5",
            "locality": "San Francisco",
            "administrative_area": "CA",
            "postal_code": "94118",
            "country": "US",
            "external_id": 304352822,
        },
        {
            "id": "cb54dd7c-519a-4e1f-85c4-7c0604089a81",
            "name": "Lavinia Mestre",
            "address1": "Muntaner 265",
            "address2": "2o 1a",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "08021",
            "country": "ES",
            "external_id": 304352777,
        },
        {
            "id": "e1987bac-b147-4ffd-8420-5866ef587ac7",
            "name": "Manoli y Miguel",
            "address1": "Plaza del Centro, 4",
            "address2": "Piso 4, Puerta 15",
            "locality": "La Vall d'Uixó",
            "administrative_area": "Comunidad Valenciana",
            "postal_code": "12600",
            "country": "ES",
            "external_id": 379921366,
        },
        {
            "id": "bebe05e8-1f2a-4210-9e7e-2b2841ba2872",
            "name": "Matt Morley",
            "address1": "Carrer de la Costa 55, Puerta 9",
            "address2": "",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "08023",
            "country": "ES",
            "external_id": 379923220,
        },
        {
            "id": "42cf80a0-3434-4868-9d8f-b501460ea8c8",
            "name": "Dom and Mustafa",
            "address1": "299 Coleridge Street",
            "address2": "",
            "locality": "San Francisco",
            "administrative_area": "California",
            "postal_code": "94110",
            "country": "US",
            "external_id": 379921145,
        },
        {
            "id": "5df5b8ce-3052-4a60-95fa-217a656c7b74",
            "name": "Ben Needham",
            "address1": "13701 Marina Pointe Drive",
            "address2": "Apt #310",
            "locality": "Marina Del Rey",
            "administrative_area": "CA",
            "postal_code": "90292",
            "country": "US",
            "external_id": 304352852,
        },
        {
            "id": "aa740b6d-bf18-41a2-a19f-6bead0ea4fee",
            "name": "Morgan Nelson",
            "address1": "3535 Indiana Street",
            "address2": "#23",
            "locality": "San Diego",
            "administrative_area": "CA",
            "postal_code": "92103",
            "country": "US",
            "external_id": 304352832,
        },
        {
            "id": "014d530b-768c-4533-9e54-a5f40d0ad6b7",
            "name": "Sara, Josan y Nia",
            "address1": "Calle Lacort, 10",
            "address2": "Casa",
            "locality": "El Pueyo de Araguas",
            "administrative_area": "Huesca",
            "postal_code": "22338",
            "country": "ES",
            "external_id": 304352802,
        },
        {
            "id": "16067e34-a6d7-482d-ab48-d74eb83aa2b5",
            "name": "Jamie & Nick",
            "address1": "1529 S Westgate Ave",
            "address2": "Unit 301",
            "locality": "Los Angeles",
            "administrative_area": "CA",
            "postal_code": "90025",
            "country": "US",
            "external_id": 304352849,
        },
        {
            "id": "e143c7b0-d37f-499c-b5eb-a172d1217bab",
            "name": "Mary Rose & Nick",
            "address1": "3301 Spring Lane",
            "address2": "",
            "locality": "Falls Church",
            "administrative_area": "VA",
            "postal_code": "22041",
            "country": "US",
            "external_id": 304352834,
        },
        {
            "id": "090d4bec-59d5-496c-a25b-7a4d72099ca7",
            "name": "Flor, Sebas y Oli",
            "address1": "Carrer de Rocafort, 29",
            "address2": "1-2",
            "locality": "Barcelona",
            "administrative_area": "Catalunya",
            "postal_code": "08015",
            "country": "ES",
            "external_id": 304352862,
        },
        {
            "id": "8b8052be-6390-4bd9-adbf-cc70325b8854",
            "name": "Dan Olsen",
            "address1": "804 Laurel Avenue",
            "address2": "",
            "locality": "Menlo Park",
            "administrative_area": "CA",
            "postal_code": "94025",
            "country": "US",
            "external_id": 304352809,
        },
        {
            "id": "ec03d5b6-c287-4670-9754-300b37d6d8b0",
            "name": "Tycho Onnasch",
            "address1": "Marnixstraat 17 Rood",
            "address2": "",
            "locality": "Haarlem",
            "administrative_area": "Noord-Holland",
            "postal_code": "2023 RA",
            "country": "NL",
            "external_id": 380049466,
        },
        {
            "id": "8b20331a-7a38-4ff1-91b9-212f1d273c57",
            "name": "Randee Palmer",
            "address1": "155 South Mathilda Avenue",
            "address2": "",
            "locality": "Sunnyvale",
            "administrative_area": "CA",
            "postal_code": "94086",
            "country": "US",
            "external_id": 304352846,
        },
        {
            "id": "bb44e8ac-6682-4d04-93e1-576fc7c65b34",
            "name": "Fernanda Parolin",
            "address1": "Carrer Sardenya, 464",
            "address2": "1, 2",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "08025",
            "country": "ES",
            "external_id": 304352790,
        },
        {
            "id": "54116354-ecab-4baa-8ce0-d67360227435",
            "name": "Albert y Paula",
            "address1": "Travessera de Dalt, 6-8",
            "address2": "7è B",
            "locality": "Barcelona",
            "administrative_area": "Catalunya",
            "postal_code": "08024",
            "country": "ES",
            "external_id": 379921207,
        },
        {
            "id": "0faaad98-34b3-4203-b413-94466ce16335",
            "name": "Chad Pelton",
            "address1": "154 West 8th St",
            "address2": "unit 8S",
            "locality": "Boston",
            "administrative_area": "MA",
            "postal_code": "02127",
            "country": "US",
            "external_id": 304352848,
        },
        {
            "id": "8cee9604-e747-4dd4-95ae-fb98921695eb",
            "name": "Laura, Manolo, Jorge y Pepe",
            "address1": "Carrer Pare Ricardo, 20",
            "address2": "5to 1ra",
            "locality": "Castelló de la Plana",
            "administrative_area": "Comunidad Valenciana",
            "postal_code": "12005",
            "country": "ES",
            "external_id": 379921110,
        },
        {
            "id": "45e9b3de-ec3c-4e72-ae2a-c5c2d9460572",
            "name": "Eve Peters",
            "address1": "2815 Ellsworth Street",
            "address2": "",
            "locality": "Berkeley",
            "administrative_area": "California",
            "postal_code": "94705",
            "country": "US",
            "external_id": 379921111,
        },
        {
            "id": "17c7d750-f05b-44c1-be9d-eae90cbe85b0",
            "name": "The Popenko's Family",
            "address1": "Simpheropolskay str 2L",
            "address2": "113",
            "locality": "Dnipro",
            "administrative_area": "Dnipro",
            "postal_code": "49005",
            "country": "UA",
            "external_id": 304352769,
        },
        {
            "id": "b1142ffa-c865-4b6c-9877-a7c847ec0595",
            "name": "Familia Serra Quiles",
            "address1": "Maria Cristina 16",
            "address2": "2B",
            "locality": "San Lorenzo de El Escorial",
            "administrative_area": "Madrid",
            "postal_code": "28200",
            "country": "ES",
            "external_id": 304352779,
        },
        {
            "id": "e52c3cf8-9e63-44ae-bf3f-b7b324e97d9d",
            "name": "Jacinta and Raphael",
            "address1": "324 San Antonio Avenue",
            "address2": "",
            "locality": "San Mateo",
            "administrative_area": "California",
            "postal_code": "94401",
            "country": "US",
            "external_id": 380051535,
        },
        {
            "id": "01c749b6-c302-4d80-914f-e04f26a76bb4",
            "name": "Farrell, Brian, Sierra and Reece",
            "address1": "229 Cold Brook Road",
            "address2": "",
            "locality": "Bearsville",
            "administrative_area": "New York",
            "postal_code": "12409",
            "country": "US",
            "external_id": 304352807,
        },
        {
            "id": "66d038c1-06af-41f7-a04f-ef878d464701",
            "name": "The Thys Ritzers",
            "address1": "Rudolf-Camerer-StraBe 12",
            "address2": "",
            "locality": "Muenchen",
            "administrative_area": "Bayern",
            "postal_code": "81369",
            "country": "DE",
            "external_id": 304352770,
        },
        {
            "id": "6a5009e9-bcd6-4fd7-aab6-e2237fda681c",
            "name": "Wes and Laurie Rose",
            "address1": "2365 Sharon Oaks Drive",
            "address2": "",
            "locality": "Menlo Park",
            "administrative_area": "California",
            "postal_code": "94025",
            "country": "US",
            "external_id": 379921245,
        },
        {
            "id": "16b2420d-fec3-4479-acd2-a27a74ea51e3",
            "name": "Sir Dan Rumennik",
            "address1": "110 Dudley Ave",
            "address2": "Apt 1",
            "locality": "Venice",
            "administrative_area": "CA",
            "postal_code": "90291",
            "country": "US",
            "external_id": 304352856,
        },
        {
            "id": "0c7b8783-ab62-4c4f-83c9-b2ea768ff614",
            "name": "Peter Sauer",
            "address1": "136 W. 11th Street",
            "address2": "Apt #2",
            "locality": "New York",
            "administrative_area": "NY",
            "postal_code": "10011",
            "country": "US",
            "external_id": 380060228,
        },
        {
            "id": "e899c188-fda2-4345-92ba-a73448ac4793",
            "name": "The Seeger Family",
            "address1": "4141 N Stratford Rd NE",
            "address2": "",
            "locality": "Atlanta",
            "administrative_area": "GA",
            "postal_code": "30342",
            "country": "US",
            "external_id": 304352826,
        },
        {
            "id": "ad702f9f-0162-4718-abf5-20ec76c9f58d",
            "name": "Familia Serrano-Solsona",
            "address1": "Via Roma",
            "address2": "32-5D",
            "locality": "SALOU",
            "administrative_area": "Tarragona",
            "postal_code": "43840",
            "country": "ES",
            "external_id": 304352765,
        },
        {
            "id": "ede8d5a3-be17-4a8e-be21-4d68e699737f",
            "name": "Shevelenko Family",
            "address1": "608a Missouri Street",
            "address2": "",
            "locality": "San Francisco",
            "administrative_area": "Ca",
            "postal_code": "94107",
            "country": "US",
            "external_id": 304352817,
        },
        {
            "id": "597255da-e1af-47e9-87e7-c699a7053139",
            "name": "Shobeir Shobeiri",
            "address1": "19469 Victoria Ct.",
            "address2": "",
            "locality": "Sonoma",
            "administrative_area": "CA",
            "postal_code": "95476",
            "country": "US",
            "external_id": 304352764,
        },
        {
            "id": "d83cf5ba-2ca4-4579-8633-30feb489e1ae",
            "name": "The Silvas",
            "address1": "1132 Oxford Road",
            "address2": "",
            "locality": "Burlingame",
            "administrative_area": "CA",
            "postal_code": "94010",
            "country": "US",
            "external_id": 304352855,
        },
        {
            "id": "2a100d43-1b87-498a-9b1c-08f1da3901df",
            "name": "Familia Mercader Simona",
            "address1": "Napols, 173",
            "address2": "3o 1a ESC A",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "08013",
            "country": "ES",
            "external_id": 304352776,
        },
        {
            "id": "9b106ee9-7a98-44cc-86cb-edc05ad973fa",
            "name": "The Smith Family",
            "address1": "419 Jacquelyn Lane",
            "address2": "",
            "locality": "Petaluma",
            "administrative_area": "CA",
            "postal_code": "94952",
            "country": "US",
            "external_id": 304352825,
        },
        {
            "id": "29ece723-39ac-4553-9aa5-11a648fee3a8",
            "name": "Sarah Smith",
            "address1": "1785 Oak Ave",
            "address2": "",
            "locality": "Menlo Park",
            "administrative_area": "CA",
            "postal_code": "94025",
            "country": "US",
            "external_id": 304352844,
        },
        {
            "id": "1713a75b-ca61-4d06-b49e-e0caf6027182",
            "name": "Clara Serrano Solsona",
            "address1": "Plaza Descubridor Diego Ordas 1",
            "address2": "Escalera 1, Piso 4 B",
            "locality": "Madrid",
            "administrative_area": "Madrid",
            "postal_code": "28003",
            "country": "ES",
            "external_id": 304352773,
        },
        {
            "id": "7f76e495-3c9e-4e0e-b4f9-4fff258ab0bc",
            "name": "Familia Sanz Solsona",
            "address1": "Cronista Revest 20",
            "address2": "5-1",
            "locality": "Castellón",
            "administrative_area": "Castellón",
            "postal_code": "12005",
            "country": "ES",
            "external_id": 304352787,
        },
        {
            "id": "ace26dc9-d026-45dc-91f5-9b9f8e0e9749",
            "name": "The Southworth Family",
            "address1": "2160 Bryant Street",
            "address2": "",
            "locality": "Palo Alto",
            "administrative_area": "CA",
            "postal_code": "94301",
            "country": "US",
            "external_id": 304352841,
        },
        {
            "id": "d85a17ca-9555-4725-9402-c54e4c35d505",
            "name": "Kristina Simmons and McLain Southworth",
            "address1": "2160 Bryant Street",
            "address2": "",
            "locality": "Palo Alto",
            "administrative_area": "California",
            "postal_code": "94301",
            "country": "US",
            "external_id": 379921162,
        },
        {
            "id": "a29951d5-9d9e-455f-922b-f778540a8ae4",
            "name": "The Strausslakes",
            "address1": "730 Westbourne Dr",
            "address2": "",
            "locality": "West Hollywood",
            "administrative_area": "CA",
            "postal_code": "90069",
            "country": "US",
            "external_id": 304352812,
        },
        {
            "id": "39a85a6a-4ba1-405b-a4cf-58fd074dd4f2",
            "name": "Martina y Teo",
            "address1": "Carrer de Nàpols, 173",
            "address2": "3ro 1ra, esc A",
            "locality": "Barcelona",
            "administrative_area": "Catalunya",
            "postal_code": "08013",
            "country": "ES",
            "external_id": 379921251,
        },
        {
            "id": "88897b87-2be3-4408-9d2d-62e6402360bf",
            "name": "Gordana & Thorsten",
            "address1": "Ausias Marc 29 4-2",
            "address2": "",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "08010",
            "country": "ES",
            "external_id": 379921260,
        },
        {
            "id": "c6b8cf2b-b815-4cd1-bbea-c7b6c5b80d32",
            "name": "The Moe & Torres Family",
            "address1": "Calle de Miguel Angel 4",
            "address2": "Esc. Izq., Piso 1-12",
            "locality": "Madrid",
            "administrative_area": "Madrid",
            "postal_code": "28010",
            "country": "ES",
            "external_id": 304352795,
        },
        {
            "id": "da7e7bb8-0b46-4722-8f7f-a901c4b8709f",
            "name": "Carrie & Keirnan Willett",
            "address1": "124 Little Branch Trail",
            "address2": "",
            "locality": "Chapel Hill",
            "administrative_area": "NC",
            "postal_code": "27517",
            "country": "US",
            "external_id": 304352854,
        },
        {
            "id": "3a45e2cc-248f-4373-872c-ce5591ae4fef",
            "name": "Victoria Yuan",
            "address1": "532 Lorimer Street",
            "address2": "Apt 2B",
            "locality": "Brooklyn",
            "administrative_area": "New York",
            "postal_code": "11211",
            "country": "US",
            "external_id": 304352808,
        },
        {
            "id": "ab8160fb-890c-49cd-a693-27e0a99c07ef",
            "name": "Pierre Yves",
            "address1": "Wellington 80",
            "address2": "5, 3",
            "locality": "Barcelona",
            "administrative_area": "Barcelona",
            "postal_code": "08018",
            "country": "ES",
            "external_id": 304352763,
        },
        {
            "id": "0101549e-0770-479d-99a7-6c4855e28d78",
            "name": "The Doyle Zappacosta Family",
            "address1": "3639 17th St",
            "address2": "",
            "locality": "San Francisco",
            "administrative_area": "CA",
            "postal_code": "94114",
            "country": "US",
            "external_id": 304352831,
        },
    ],
}

# Read current contacts
contacts_path = os.path.join(PROJECT_ROOT, "data/contacts/contacts.parquet")
df_contacts = pd.read_parquet(contacts_path)
print(f"Starting with {len(df_contacts)} contacts")

# Ensure external_id column exists
if "external_id" not in df_contacts.columns:
    df_contacts["external_id"] = None

# Create snapshot
os.makedirs(os.path.join(PROJECT_ROOT, "data/snapshots"), exist_ok=True)
timestamp = datetime.now().strftime("%Y-%m-%d-%H%M%S")
snapshot_path = os.path.join(
    PROJECT_ROOT, f"data/snapshots/contacts-{timestamp}.parquet"
)
df_contacts.to_parquet(snapshot_path, index=False)
print(f"Created snapshot: {snapshot_path}")


# Helper functions
def normalize_name(name):
    if pd.isna(name) or not name:
        return ""
    return str(name).lower().strip()


def normalize_address(addr1, addr2=""):
    parts = [str(addr1) if addr1 else "", str(addr2) if addr2 else ""]
    return " ".join(parts).strip().lower()


def find_existing_contact(recipient, df_contacts):
    """Find existing contact by name, address, or external_id"""
    rec_name = normalize_name(recipient.get("name", ""))
    rec_addr1 = recipient.get("address1", "")
    rec_addr2 = recipient.get("address2", "")
    rec_addr = normalize_address(rec_addr1, rec_addr2)
    rec_external_id = recipient.get("external_id")

    # Try to find by external_id first (most reliable)
    if rec_external_id:
        matches = df_contacts[
            df_contacts["external_id"].astype(str) == str(rec_external_id)
        ]
        if len(matches) > 0:
            return matches.index[0]

    # Try to find by name and address
    for idx, row in df_contacts.iterrows():
        row_name = normalize_name(row.get("name", ""))
        row_addr = normalize_address(row.get("address", ""))

        # Check name match
        if rec_name and row_name and rec_name == row_name:
            # If address also matches, it's definitely the same contact
            if rec_addr and row_addr and rec_addr == row_addr:
                return idx
            # If name matches but no address in recipient, still likely match
            if not rec_addr:
                return idx

        # Check address match (if name doesn't match but address does)
        if rec_addr and row_addr and rec_addr == row_addr and rec_name:
            return idx

    return None


# Process recipients from delivery data
mailing_note = "Received 2025 holiday card mailing (Leaping Stag The Met Holiday Cards)"
today = date.today()

recipients = delivery_result["recipients"]
print(f"Processing {len(recipients)} recipients from delivery data...")

updated_count = 0
added_count = 0
new_rows = []

# Process all recipients
for recipient in recipients:
    idx = find_existing_contact(recipient, df_contacts)

    full_address = (
        f"{recipient.get('address1', '')} {recipient.get('address2', '')}".strip()
    )

    if idx is not None:
        # Update existing contact
        current_notes = (
            df_contacts.loc[idx, "notes"]
            if pd.notna(df_contacts.loc[idx, "notes"])
            else ""
        )
        if mailing_note not in current_notes:
            df_contacts.loc[idx, "notes"] = f"{current_notes}; {mailing_note}".strip(
                "; "
            )
            df_contacts.loc[idx, "updated_date"] = today
            updated_count += 1
    else:
        # Create new contact
        new_contact = {
            "contact_id": str(uuid.uuid4()),
            "name": recipient.get("name", ""),
            "contact_type": "individual",
            "category": "personal",
            "platform": "minted.com",
            "email": "",
            "phone": "",
            "address": full_address,
            "country": recipient.get("country", ""),
            "website": "",
            "language": "",
            "notes": mailing_note,
            "first_contact_date": today,
            "last_contact_date": today,
            "created_date": today,
            "updated_date": today,
            "external_id": (
                str(recipient.get("external_id", ""))
                if recipient.get("external_id")
                else None
            ),
        }
        # Ensure 'mobile' column if it exists
        if "mobile" in df_contacts.columns:
            new_contact["mobile"] = ""

        new_rows.append(new_contact)
        added_count += 1

# Add new contacts
if new_rows:
    df_new = pd.DataFrame(new_rows)
    df_contacts = pd.concat([df_contacts, df_new], ignore_index=True)

# Save updated contacts
df_contacts.to_parquet(contacts_path, index=False)
print(f"Updated {updated_count} existing contacts, added {added_count} new contacts.")
print(f"Total contacts after update: {len(df_contacts)}")
