#!/usr/bin/env python3
"""
render_plan_docs.py — render the plan-mirrored architecture docs from Neotoma.

The Ateles plan entity is canonical for three repo docs:

    plan field              →  repo file
    ----------------------     -------------------------
    taxonomy_markdown       →  docs/taxonomy.md
    phases_markdown         →  docs/phases.md
    architecture_markdown   →  docs/architecture.md

Direct edits to those files are reverted on the next render. The supported
flow is: correct the plan field in Neotoma, then run this script.

Usage:
    render_plan_docs.py             # Neotoma → disk (overwrite local files)
    render_plan_docs.py --check     # exit 1 if disk differs from Neotoma
    render_plan_docs.py --push      # disk → Neotoma corrections (write-back
                                    # for an operator-reviewed local edit)

Env: NEOTOMA_BASE_URL, NEOTOMA_BEARER_TOKEN (falls back to
~/.config/neotoma/.env), ATELES_PLAN_ENTITY_ID (defaults to the Ateles plan).

Each rendered file carries a script-appended observation-id footer — NOT part
of the stored plan field itself (the field's own in-body mirror header,
authored in Neotoma, is left untouched). The footer names the exact
observation that produced the current field value, read from
retrieve_entity_snapshot's per-field provenance map (see
neotoma_mirror_lib.py), so a reader can tell a mirror is stale against a
corrected field by looking at the file, rather than only by re-running
--check. `--push` strips the footer before writing the field back to Neotoma
— the footer is a render artifact, never part of the canonical value.
"""

from __future__ import annotations

import argparse
import difflib
import hashlib
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from neotoma_mirror_lib import load_env, request, unwrap_snapshot  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_PLAN_ID = "ent_99ace4dd6673aa36ed08b1fe"

FIELD_TO_PATH = {
    "taxonomy_markdown": "docs/taxonomy.md",
    "phases_markdown": "docs/phases.md",
    "architecture_markdown": "docs/architecture.md",
}

_FOOTER_RE = re.compile(
    r"\n?<!-- source observation \(do not edit by hand; regenerated by "
    r"render_plan_docs\.py\): plan \S+ field `\S+` observation `\S+` -->\n?$"
)


def _footer(field: str, plan_id: str, obs_id: str) -> str:
    return (
        f"<!-- source observation (do not edit by hand; regenerated by "
        f"render_plan_docs.py): plan {plan_id} field `{field}` observation "
        f"`{obs_id}` -->\n"
    )


def _strip_footer(text: str) -> str:
    return _FOOTER_RE.sub("\n", text)


def _fetch_fields(base_url: str, token: str, plan_id: str) -> tuple[dict[str, str], dict[str, str]]:
    entity = request(f"{base_url}/entities/{plan_id}", token)
    snapshot, provenance = unwrap_snapshot(entity)
    fields = {f: snapshot.get(f) for f in FIELD_TO_PATH}
    obs_ids = {f: (provenance.get(f) or "unknown") for f in FIELD_TO_PATH}
    return fields, obs_ids


def _rendered(body: str, field: str, plan_id: str, obs_id: str) -> str:
    canonical = body if body.endswith("\n") else body + "\n"
    return canonical + _footer(field, plan_id, obs_id)


def render(fields: dict[str, str], obs_ids: dict[str, str], plan_id: str) -> int:
    missing = [f for f, body in fields.items() if not body]
    for field, body in fields.items():
        if not body:
            continue
        path = REPO_ROOT / FIELD_TO_PATH[field]
        path.write_text(_rendered(body, field, plan_id, obs_ids[field]))
        print(
            f"wrote {FIELD_TO_PATH[field]} ({len(body)} chars) from {field}, "
            f"observation {obs_ids[field]}"
        )
    if missing:
        print(f"WARNING: plan fields empty, files left untouched: {missing}")
        return 1
    return 0


def check(fields: dict[str, str], obs_ids: dict[str, str], plan_id: str) -> int:
    failures = []
    for field, body in fields.items():
        path = REPO_ROOT / FIELD_TO_PATH[field]
        if not body:
            failures.append(f"{field}: empty in Neotoma")
            continue
        canonical = _rendered(body, field, plan_id, obs_ids[field])
        on_disk = path.read_text() if path.exists() else ""
        if on_disk != canonical:
            diff = list(
                difflib.unified_diff(
                    canonical.splitlines(), on_disk.splitlines(),
                    fromfile=f"neotoma:{field}", tofile=str(FIELD_TO_PATH[field]),
                    lineterm="", n=1,
                )
            )
            failures.append(f"{FIELD_TO_PATH[field]} differs ({len(diff)} diff lines)")
            print("\n".join(diff[:40]))
    if failures:
        print("MIRROR CHECK FAILED:\n  " + "\n  ".join(failures))
        return 1
    print("mirror check OK — disk matches Neotoma for all three docs")
    return 0


def push(base_url: str, token: str, plan_id: str) -> int:
    for field, rel_path in FIELD_TO_PATH.items():
        raw = (REPO_ROOT / rel_path).read_text()
        body = _strip_footer(raw)
        digest = hashlib.sha256(body.encode()).hexdigest()[:12]
        result = request(
            f"{base_url}/correct",
            token,
            {
                "entity_id": plan_id,
                "entity_type": "plan",
                "field": field,
                "value": body,
                "idempotency_key": f"update-plan-{field}-{digest}",
            },
        )
        status = result.get("status") or result.get("action") or "ok"
        print(f"corrected {field} from {rel_path} ({digest}) — {status}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="verify disk matches Neotoma")
    mode.add_argument("--push", action="store_true", help="write local files back as plan corrections")
    args = parser.parse_args()

    base_url, token = load_env()
    plan_id = os.environ.get("ATELES_PLAN_ENTITY_ID", DEFAULT_PLAN_ID)

    if args.push:
        return push(base_url, token, plan_id)
    fields, obs_ids = _fetch_fields(base_url, token, plan_id)
    return check(fields, obs_ids, plan_id) if args.check else render(fields, obs_ids, plan_id)


if __name__ == "__main__":
    sys.exit(main())
