#!/usr/bin/env python3
"""
render_positioning_docs.py — project product-positioning entities from
Neotoma into repo files, extending the same projection contract as
render_plan_docs.py and render_agent_docs.py.

WHY THIS EXISTS: the operator wants site content sourced from the repo so
repo-to-site drift is structurally impossible. But positioning copy (ICPs,
competitive/incumbent research, chronic/acute pain framing, ICP
reconciliations) is NOT repo-authored — it lives in Neotoma `target_persona`,
`research_finding`, and `analysis` entities that get corrected repeatedly (one
was corrected four times in one day). Committing that content to the repo as
AUTHORED text would violate the fork test (docs/forking.md,
CLAUDE.md#standing-constraints): a forker cloning this repo would inherit
someone else's product positioning baked into files they'd have to hand-edit,
rather than an entity they can supply their own values for.

The resolution mirrors render_plan_docs.py / render_agent_docs.py exactly:
Neotoma stays canonical, the repo holds a GENERATED MIRROR that names its
source and regenerates empty (or absent) for a forker who supplies their own
`POSITIONING_ENTITIES` mapping (below) or none at all.

WHAT IS PROJECTED: one file per entity, under docs/positioning/<product>/. The
entity id list is intentionally a static registry (POSITIONING_ENTITIES,
below), not a type-wide query like render_agent_docs.py's — this script
projects a curated set of settled positioning artifacts, not "every
target_persona/analysis/research_finding entity that exists" (the corpus holds
many analysis entities that are not positioning content — e.g. session
reviews, feedback classification — and a type-wide query would pull those in
too).

OUTPUT FORMAT: frontmatter (every short structured scalar field: archetype,
confidence, kind, tags, …) + a markdown body rendered from the entity's prose
fields (body/summary/method/conclusion/messaging_good/messaging_bad/etc, in a
type-appropriate order) — the render_agent_docs.py pattern. This was chosen
over pure YAML/JSON because these entities mix short structured scalars
(archetype, confidence, stage) with long-form prose (a reconciliation body
runs to several thousand words) that YAML would need to hand as a single
folded/quoted string — worse for both a human reader and a site build than
frontmatter-for-fields + markdown-for-prose, which is exactly the shape a
static-site frontmatter parser (Next.js/Astro/Hugo front matter, gray-matter,
etc.) is built to consume directly.

WHERE THE FILES LIVE: docs/positioning/<product>/<slug>.md, scoped by product
(ateles/, neotoma/) rather than flattened, so a forker cloning this repo sees
immediately that these are one operator's product positioning (not generic
docs) and that regenerating against their own Neotoma graph with their own
POSITIONING_ENTITIES list produces their own tree — empty for a fresh fork
with no entities set, non-empty once they populate it. This is a PUBLIC repo:
positioning content naming competitors is fine (see the entities' own
competitor-test content); evaluator names and verbatim quotes sourced from
customer_development_note entities are NOT — see _scrub_evaluator_pii below.

OBSERVATION-ID STAMP: every field surfaced in frontmatter is paired with the
observation id that produced its current value (neotoma_mirror_lib.
observation_ids_block), fixing the defect named in ateles work on this pass:
previously only the entity id was stamped anywhere in this repo's mirrors, so
a mirror could go stale against a corrected field with the file itself unable
to say so.

Usage:
    render_positioning_docs.py            # Neotoma → disk
    render_positioning_docs.py --check    # exit 1 if disk differs from Neotoma

Env: NEOTOMA_BASE_URL, NEOTOMA_BEARER_TOKEN (falls back to
~/.config/neotoma/.env).
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from neotoma_mirror_lib import load_env, request, unwrap_snapshot, observation_ids_block, yaml_scalar  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[2]
POSITIONING_DIR = REPO_ROOT / "docs" / "positioning"

HEADER = (
    "<!-- Do not edit this file directly. This is a generated mirror of a "
    "Neotoma entity. Correct the entity in Neotoma (neotoma corrections "
    "create / neotoma edit <id> / the Neotoma Inspector), then regenerate "
    "with `python3 execution/scripts/render_positioning_docs.py` (--check "
    "verifies disk matches Neotoma). See that script's module docstring for "
    "why this content is projected rather than authored here. -->\n"
)

# Curated registry of positioning entities to project, by product. This is
# deliberately a static list, not a type-wide Neotoma query: the corpus holds
# many `analysis`/`research_finding` entities that are not settled positioning
# content (session reviews, feedback classification, competitive scans still
# in flux), and this script projects only the ones an operator has decided
# are durable enough to publish. A fork with no entities of its own gets an
# empty dict here and this script renders nothing — the intended fork-test
# behavior (see module docstring).
#
#   product -> [(entity_id, entity_type, slug), ...]
POSITIONING_ENTITIES: dict[str, list[tuple[str, str, str]]] = {
    "ateles": [
        ("ent_fd64f687e7e1bf5711c6de2b", "target_persona", "icp-implementation-derived"),
        ("ent_b6e066a5d110b8500d3ec8c9", "target_persona", "icp-design-sourced"),
        ("ent_fa1f87fbd3b66e491361dae1", "analysis", "icp-reconciliation"),
        ("ent_f8271efcdb842076a5147929", "research_finding", "incumbent-and-competitor-test"),
        ("ent_2a29bed8dcacd4b1ff20c6f2", "analysis", "chronic-acute-pain"),
    ],
    "neotoma": [
        ("ent_825474455c25f9ea0783ebc6", "target_persona", "icp-durable-candidate-b"),
        ("ent_9e105035543fed11658a3fcb", "research_finding", "incumbent"),
        ("ent_e5aff92972fdfbc4f508a7ba", "analysis", "chronic-acute-pain"),
    ],
}

# Field order per entity type: (frontmatter scalar fields, body prose fields).
# Only fields that are short, single-line-ish scalars go in frontmatter;
# long-form prose (even if technically a single string field) renders as a
# markdown body section instead, per the same rule render_agent_docs.py
# applies (output_format there, messaging_good/body/conclusion here).
FRONTMATTER_FIELDS = {
    "target_persona": (
        "name", "title", "product", "company_type", "stage",
    ),
    "analysis": (
        "title", "kind", "confidence", "tags",
    ),
    "research_finding": (
        "title", "confidence", "researched_date",
    ),
}

BODY_SECTIONS = {
    "target_persona": (
        ("Archetype", "archetype"),
        ("Stack", "stack"),
        ("Core job to be done", "core_jtbd"),
        ("Trigger moment", "trigger_moment"),
        ("Messaging — good", "messaging_good"),
        ("Messaging — bad (anti-profile)", "messaging_bad"),
        ("Ideal entry point", "ideal_entry_point"),
        ("Summary", "one_line_summary"),
    ),
    "analysis": (
        ("Subject", "subject"),
        ("Summary", "summary"),
        ("Method", "method"),
        ("Body", "body"),
        ("Gaps", "gaps"),
        ("Source artifacts", "source_artifacts"),
        ("Sources audited", "sources_audited"),
    ),
    "research_finding": (
        ("Subject", "subject"),
        ("Summary", "summary"),
        ("Method", "method"),
        ("Conclusion", "conclusion"),
        ("Sources", "sources"),
    ),
}

# STAMPED_FIELDS per type = every field named in FRONTMATTER_FIELDS or
# BODY_SECTIONS — i.e. everything actually rendered into the file, so every
# rendered fact carries a freshness stamp, not just the frontmatter scalars.
STAMPED_FIELDS = {
    t: tuple(FRONTMATTER_FIELDS[t]) + tuple(f for _, f in BODY_SECTIONS[t])
    for t in FRONTMATTER_FIELDS
}

# ---------------------------------------------------------------------------
# PII scrub: evaluator names / customer_development_note-sourced quotes.
#
# Per this pass's explicit constraint: "Positioning content naming competitors
# is fine (...) evaluator names and quotes from customer_development_note
# entities are NOT". The two Neotoma research/analysis entities in this
# registry (ent_9e105035543fed11658a3fcb, ent_e5aff92972fdfbc4f508a7ba) cite
# named individual evaluators as corroborating evidence, sourced from
# customer_development_note / feedback entities (verified by reading both
# entities in full before writing this list — see the PR description for the
# read). Those names are scrubbed to role descriptions at render time; this is
# a NAMED, DOCUMENTED substitution (not a blanket regex), so a reviewer can
# see exactly what changed and why, and so a name added later that ISN'T in
# this table fails loudly (via the sentinel check in _scrub) rather than
# leaking silently.
# ---------------------------------------------------------------------------
_EVALUATOR_NAME_MAP = {
    "Brandon/AIBTC": "an evaluator deployment",
    "Jacob Cohen": "an evaluator",
    "Jeremiah Lee": "an evaluator",
    "Sidney Brown": "an evaluator",
    "Simon Bergeron": "an evaluator",
    "Rebecca": "an evaluator",
    "Larry": "an evaluator",
    "Jeroen van 't Hoff": "an evaluator",
    "Jeroen": "an evaluator",
    "Eriks Reks": "an evaluator",
    "Eriks": "an evaluator",
    "Mark": "the operator",
}
# entity_id references to customer_development_note / named-evaluator sources
# are dropped from rendered "sources"/"source_artifacts" lists (the record
# itself, not just the name, is the PII-bearing thing) AND scrubbed inline in
# prose (method/body fields cite these ids directly, e.g. "(ent_aaa1226...)"
# — an internal Neotoma pointer that is 1:1-traceable to the named individual
# for anyone with Neotoma access is the same PII-adjacency the name itself
# carries, so it is scrubbed too, not just the sources list). Each id below
# was verified, by reading the two source entities in full, to identify a
# specific named evaluator's customer_development_note or feedback record.
_PII_ENTITY_IDS = {
    "ent_f9bfda2a86f54dc1b72962cb",  # Jeremiah Lee, customer_development_note
    "ent_aaa12264742df8597df6b15f",  # Simon Bergeron, customer_development_note
    "ent_32acb65667294ab579ed6d0d",  # Rebecca, feedback
    "ent_13b6325f273ce0b002832377",  # Larry, feedback
    "ent_22a0ca680051fabd42c1f537",  # Jeroen van 't Hoff, feedback
    "ent_59e1b896157641f9240f9e86",  # Eriks Reks, feedback
    "ent_c649232feaf95688b25be6af",  # named evaluator, feedback
    "ent_1862a583f9ea47cf6b1aa716",  # named evaluator, feedback
    "ent_ca46eb9e4e3150bb0637eb40",  # named evaluator deployment, feedback
}
_PII_SOURCE_MARKERS = ("customer_development_note",)


def _scrub_evaluator_pii(text: str) -> str:
    if not text:
        return text
    out = text
    for name, replacement in _EVALUATOR_NAME_MAP.items():
        out = re.sub(rf"\b{re.escape(name)}\b", replacement, out)
    for entity_id in _PII_ENTITY_IDS:
        out = out.replace(entity_id, "[evaluator-record]")
    return out


def _scrub_source_list(items: list) -> list:
    return [i for i in items if not any(m in str(i) for m in _PII_SOURCE_MARKERS)]


def _render_field_value(v) -> str:
    if isinstance(v, list):
        v = _scrub_source_list(v)
        return "\n".join(f"- {_scrub_evaluator_pii(str(x))}" for x in v) if v else "_(none)_"
    if isinstance(v, dict):
        return "\n".join(f"- **{k}**: {_scrub_evaluator_pii(str(val))}" for k, val in v.items())
    return _scrub_evaluator_pii(str(v)).strip()


def fetch_entity(base_url: str, token: str, entity_id: str) -> tuple[dict, dict]:
    entity = request(f"{base_url}/entities/{entity_id}", token)
    return unwrap_snapshot(entity)


def render_entity_file(entity_id: str, entity_type: str, snapshot: dict, provenance: dict) -> str:
    fm_fields = FRONTMATTER_FIELDS[entity_type]
    body_sections = BODY_SECTIONS[entity_type]

    L = [HEADER.rstrip(), "", "---", f"entity_id: {yaml_scalar(entity_id)}", f"entity_type: {entity_type}"]
    for key in fm_fields:
        val = snapshot.get(key)
        if val is None or val == "":
            continue
        if isinstance(val, list):
            vals = _scrub_source_list(val)
            if not vals:
                continue
            L.append(f"{key}:")
            L += [f"  - {yaml_scalar(_scrub_evaluator_pii(str(v)))}" for v in vals]
        elif "\n" not in str(val):
            L.append(f"{key}: {yaml_scalar(_scrub_evaluator_pii(str(val)))}")
    L += observation_ids_block(provenance, STAMPED_FIELDS[entity_type])
    L.append("---")

    title = snapshot.get("title") or snapshot.get("name") or entity_id
    L += ["", f"# {_scrub_evaluator_pii(str(title))}", ""]

    for heading, field in body_sections:
        val = snapshot.get(field)
        if val is None or val == "" or val == []:
            continue
        rendered = _render_field_value(val)
        if not rendered.strip():
            continue
        L += [f"## {heading}", "", rendered, ""]

    L += [
        "---",
        "",
        f"*Generated from Neotoma `{entity_type}` `{entity_id}`. Do not edit directly: "
        "correct the entity and run `python3 execution/scripts/render_positioning_docs.py`.*",
        "",
    ]
    return "\n".join(L)


def _targets_for_registry(
    base_url: str, token: str
) -> tuple[dict[Path, str], dict[str, tuple[dict, dict]]]:
    """Fetch every registered entity once and compute its rendered content.

    Returns (path -> content, entity_id -> (snapshot, provenance)) so callers
    doing --check can reuse the fetched snapshots for a diff without a second
    round trip.
    """
    targets: dict[Path, str] = {}
    fetched: dict[str, tuple[dict, dict]] = {}
    for product, entries in POSITIONING_ENTITIES.items():
        for entity_id, entity_type, slug in entries:
            snapshot, provenance = fetch_entity(base_url, token, entity_id)
            fetched[entity_id] = (snapshot, provenance)
            content = render_entity_file(entity_id, entity_type, snapshot, provenance)
            path = POSITIONING_DIR / product / f"{slug}.md"
            targets[path] = content
    return targets, fetched


def index_md() -> str:
    L = [
        HEADER.rstrip(),
        "",
        "# Positioning",
        "",
        "Generated mirrors of settled product-positioning entities in Neotoma "
        "(`target_persona`, `analysis`, `research_finding`) — ICPs, competitive/"
        "incumbent research, and chronic/acute pain framing. Neotoma is "
        "canonical; these files are generated by "
        "`execution/scripts/render_positioning_docs.py` from the static "
        "registry `POSITIONING_ENTITIES` in that script. A fork with no "
        "entities of its own regenerates this tree empty — see that script's "
        "module docstring for the fork-test rationale.",
        "",
    ]
    for product, entries in POSITIONING_ENTITIES.items():
        L += [f"## {product}", "", "| File | Entity type | Entity ID |", "| --- | --- | --- |"]
        for entity_id, entity_type, slug in entries:
            L.append(f"| [{slug}.md]({product}/{slug}.md) | {entity_type} | `{entity_id}` |")
        L.append("")
    return "\n".join(L)


def render() -> int:
    base_url, token = load_env()
    targets, _ = _targets_for_registry(base_url, token)
    index_path = POSITIONING_DIR / "README.md"
    targets[index_path] = index_md()
    for path, content in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content if content.endswith("\n") else content + "\n")
    rel = sorted(str(p.relative_to(REPO_ROOT)) for p in targets)
    print(f"rendered {len(targets)} positioning files:")
    for r in rel:
        print(f"  {r}")
    return 0


def check() -> int:
    base_url, token = load_env()
    targets, _ = _targets_for_registry(base_url, token)
    targets[POSITIONING_DIR / "README.md"] = index_md()
    failures = []
    for path, content in targets.items():
        canonical = content if content.endswith("\n") else content + "\n"
        on_disk = path.read_text() if path.exists() else ""
        if on_disk != canonical:
            failures.append(str(path.relative_to(REPO_ROOT)))
    # Orphan check: a positioning file on disk with the generated-mirror
    # header but no entry in the current registry (an entity id was removed
    # from POSITIONING_ENTITIES, or renamed to a new slug).
    known = {str(p.relative_to(REPO_ROOT)) for p in targets}
    orphans = []
    if POSITIONING_DIR.exists():
        for p in POSITIONING_DIR.rglob("*.md"):
            rel = str(p.relative_to(REPO_ROOT))
            if rel in known:
                continue
            if "generated mirror of a Neotoma entity" in p.read_text():
                orphans.append(rel)
    if failures or orphans:
        if failures:
            print("POSITIONING MIRROR CHECK FAILED — disk differs from Neotoma:")
            for f in failures:
                print(f"  {f}")
        if orphans:
            print("POSITIONING MIRROR CHECK FAILED — stale orphan files (removed from registry):")
            for o in sorted(orphans):
                print(f"  {o}")
        return 1
    print(f"positioning mirror check OK — {len(targets)} files match Neotoma")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify disk matches Neotoma")
    args = parser.parse_args()
    return check() if args.check else render()


if __name__ == "__main__":
    sys.exit(main())
