#!/usr/bin/env python3
"""
render_agent_docs.py — render the canonical per-agent file + Claude Code
SKILL.md mirror from Neotoma.

`agent_definition` entities in Neotoma are canonical. This script projects each
into ONE harness-neutral file plus a thin harness adapter:

    1. docs/agents/<name>.md   — THE canonical on-disk agent file. Harness-
                                 neutral. Rich YAML frontmatter (every
                                 structured field: tier, genus, status, AAuth
                                 sub, grant, triggers, allowed tools, context/
                                 operational entity types, entity_id) + a
                                 human-readable metadata table + the full
                                 operational prompt body. Any harness can read
                                 this; nothing here is Claude-specific.
    2. .claude/skills/<name>/SKILL.md — a GENERATED MIRROR for Claude Code,
                                 whose loader hard-requires this exact path.
                                 Minimal CC frontmatter (name, description,
                                 triggers, user_invocable, entity_id) + the
                                 same prompt body + a pointer back to the
                                 canonical docs/agents file. Not authored;
                                 regenerated from the same entity.

Plus docs/agents/README.md, an index table over all agents.

Daemons do NOT read either file — they load prompt_markdown straight from
Neotoma (lib/daemon_runtime/agent_loader.py). These files are for humans and
the Claude Code harness only.

Per agent_policy ent_c3c5e4a9350250cbf69e08bf, prompt_markdown is always
public and PII-free — so both surfaces are safe for the public repo and there
is no per-agent visibility gating.

A "real agent" = an agent_definition with a `name` AND at least one of
tier/genus/aauth_sub (this excludes skills miscategorized as agent_definition).
`proposed`-status agents are listed in the index but get no SKILL.md (no
running prompt yet).

Usage:
    render_agent_docs.py            # Neotoma → disk
    render_agent_docs.py --check    # exit 1 if disk differs from Neotoma

Env: NEOTOMA_BASE_URL, NEOTOMA_BEARER_TOKEN (falls back to
~/.config/neotoma/.env).
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
import urllib.request
import urllib.error
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
AGENTS_DOC_DIR = REPO_ROOT / "docs" / "agents"
SKILLS_DIR = REPO_ROOT / ".claude" / "skills"

SKILL_HEADER = (
    "<!-- Do not edit this file directly. Corrections go through "
    "`neotoma corrections create`, `neotoma edit <id>`, or the Neotoma "
    "Inspector. This file is regenerated on every relevant write. -->\n"
)


def _load_env() -> tuple[str, str]:
    base_url = os.environ.get("NEOTOMA_BASE_URL", "")
    token = os.environ.get("NEOTOMA_BEARER_TOKEN", "")
    env_path = Path.home() / ".config" / "neotoma" / ".env"
    if (not base_url or not token) and env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            value = value.strip().strip('"').strip("'")
            if key == "NEOTOMA_BASE_URL" and not base_url:
                base_url = value
            elif key == "NEOTOMA_BEARER_TOKEN" and not token:
                token = value
    if not base_url:
        sys.exit("NEOTOMA_BASE_URL not set (env or ~/.config/neotoma/.env)")
    return base_url.rstrip("/"), token


def _request(url: str, token: str, payload: dict | None = None, retries: int = 5) -> dict:
    last = None
    for attempt in range(retries):
        try:
            req = urllib.request.Request(url)
            if token:
                req.add_header("Authorization", f"Bearer {token}")
            if payload is not None:
                req.add_header("Content-Type", "application/json")
                req.data = json.dumps(payload).encode()
            with urllib.request.urlopen(req, timeout=30) as resp:
                return json.loads(resp.read().decode())
        except (urllib.error.URLError, ConnectionError) as exc:
            last = exc
            time.sleep(2)
    raise SystemExit(f"Neotoma unreachable after {retries} tries: {last}")


def _unwrap(entity: dict) -> dict:
    s = entity.get("snapshot", entity)
    if isinstance(s.get("snapshot"), dict):
        s = s["snapshot"]
    return s


def fetch_agents(base_url: str, token: str) -> list[dict]:
    data = _request(f"{base_url}/entities/query", token, {"entity_type": "agent_definition", "limit": 200})
    ents = data.get("entities") or data.get("results") or []
    real = []
    for e in ents:
        s = _unwrap(e)
        if not s.get("name"):
            continue
        if not (s.get("tier") or s.get("genus") or s.get("aauth_sub")):
            continue  # excludes skills miscategorized as agent_definition
        s["_entity_id"] = e.get("entity_id") or s.get("entity_id", "")
        real.append(s)
    real.sort(key=lambda s: s["name"])
    return real


def _as_list(v) -> list[str]:
    """Normalize a list-ish field to a clean list of strings.

    Handles the three shapes seen in stored agent_definition data:
    a real list; a JSON-encoded array string (e.g. '["a", "b"]'); and a
    plain comma-separated string. The JSON case matters — some entities
    store triggers/allowed_tools as a stringified array, which a naive
    comma split would corrupt into items like '["a"'.
    """
    if v is None:
        return []

    def _flatten(item) -> list[str]:
        """Expand one item, JSON-parsing it if it's a stringified array."""
        if isinstance(item, list):
            out: list[str] = []
            for x in item:
                out += _flatten(x)
            return out
        sv = str(item).strip()
        if not sv:
            return []
        if sv[:1] == "[" and sv[-1:] == "]":
            try:
                parsed = json.loads(sv)
                if isinstance(parsed, list):
                    out = []
                    for x in parsed:
                        out += _flatten(x)
                    return out
            except (json.JSONDecodeError, ValueError):
                pass
        return [sv.strip('"').strip("'")]

    if isinstance(v, list):
        out: list[str] = []
        for x in v:
            out += _flatten(x)
        return [s for s in (i.strip() for i in out) if s]
    sv = str(v).strip()
    flat = _flatten(sv)
    if len(flat) == 1 and "," in flat[0] and not (sv[:1] == "[" and sv[-1:] == "]"):
        # plain comma-separated string
        return [p.strip().strip('"').strip("'") for p in flat[0].split(",") if p.strip()]
    return [s for s in (i.strip() for i in flat) if s]


def _yaml_scalar(v) -> str:
    """Quote a YAML scalar when it contains characters that would break parsing."""
    sv = str(v)
    if sv == "":
        return '""'
    if any(c in sv for c in ':#') or sv[0] in "!&*?{}[]|>@`\"'%,-" or sv != sv.strip():
        return '"' + sv.replace('\\', '\\\\').replace('"', '\\"') + '"'
    return sv


def _canonical_frontmatter(s: dict) -> list[str]:
    """Rich, harness-neutral frontmatter — every structured field of the entity."""
    fm = ["---", "entity_id: " + _yaml_scalar(s.get("_entity_id", "")), "entity_type: agent_definition"]
    # Only short, single-line scalars belong in frontmatter. Multi-line fields
    # (e.g. output_format) are rendered as body sections instead.
    for key in ("name", "description", "tier", "genus", "status", "aauth_sub", "agent_grant",
                "observation_source_default", "harness_preferences"):
        val = s.get(key)
        if val and "\n" not in str(val):
            fm.append(f"{key}: {_yaml_scalar(val)}")
    if s.get("user_invocable") is not None:
        fm.append(f"user_invocable: {str(bool(s['user_invocable'])).lower()}")
    # tool_allowlist is the canonical tool field (allowed_tools was a diverged
    # duplicate, merged into tool_allowlist 2026-06-17; stale residue may remain
    # in allowed_tools but is not surfaced).
    for key in ("triggers", "tool_allowlist", "context_entity_types", "operational_entity_types"):
        vals = _as_list(s.get(key))
        if vals:
            fm.append(f"{key}:")
            fm += [f"  - {_yaml_scalar(v)}" for v in vals]
    fm.append("---")
    return fm


def canonical_agent_file(s: dict) -> str:
    """THE canonical, harness-neutral agent file: rich frontmatter + a
    human-readable metadata table + the full operational prompt body."""
    name = s["name"]
    L = [SKILL_HEADER.rstrip(), ""]
    L += _canonical_frontmatter(s)
    L += ["", f"# {name}", ""]
    if s.get("description"):
        L += [s["description"], ""]
    # Human-readable metadata table (mirrors the frontmatter for skimming).
    L += ["## Definition", "", "| Field | Value |", "| --- | --- |"]
    rows = [
        ("Tier", s.get("tier")),
        ("Genus", s.get("genus")),
        ("Status", s.get("status")),
        ("AAuth sub", s.get("aauth_sub")),
        ("Agent grant", s.get("agent_grant")),
        ("Observation source", s.get("observation_source_default")),
        ("Triggers", ", ".join(_as_list(s.get("triggers"))) or None),
        ("Allowed tools", ", ".join(_as_list(s.get("tool_allowlist"))) or None),
        ("Context entity types", ", ".join(_as_list(s.get("context_entity_types"))) or None),
        ("Operational entity types", ", ".join(_as_list(s.get("operational_entity_types"))) or None),
        ("Harness", s.get("harness_preferences")),
        ("Entity ID", s.get("_entity_id")),
    ]
    for label, val in rows:
        if val:
            L.append(f"| {label} | {val} |")
    L.append("")
    body = (s.get("prompt_markdown") or "").strip()
    if body:
        L += ["## Prompt", "", body, ""]
    elif s.get("status") == "proposed":
        L += ["## Prompt", "", "_Proposed agent — prompt is a design sketch, not yet operational._", ""]
    else:
        L += ["## Prompt", "", "_No operational prompt authored yet._", ""]
    # Note: the `output_format` entity field (where set) is already embedded in
    # prompt_markdown for these agents; we don't repeat it as a separate section.
    L += [
        "---",
        "",
        f"*Canonical agent file, generated from Neotoma `agent_definition` `{s.get('_entity_id','')}`. "
        "Harness-neutral — the Claude Code mirror at `.claude/skills/" + name + "/SKILL.md` is generated "
        "from this same entity. Do not edit directly: correct the entity and run "
        "`python3 execution/scripts/render_agent_docs.py`.*",
        "",
    ]
    return "\n".join(L)


def skill_md(s: dict) -> str:
    """Claude Code adapter: minimal frontmatter (only the keys the CC loader
    consumes) + the same prompt body + a pointer to the canonical file."""
    name = s["name"]
    fm = ["---", f"entity_id: {_yaml_scalar(s.get('_entity_id',''))}", "entity_type: agent_definition"]
    if s.get("name"):
        fm.append(f"name: {_yaml_scalar(s['name'])}")
    if s.get("description"):
        fm.append(f"description: {_yaml_scalar(s['description'])}")
    triggers = _as_list(s.get("triggers"))
    if triggers:
        fm.append("triggers:")
        fm += [f"  - {_yaml_scalar(t)}" for t in triggers]
    if s.get("user_invocable") is not None:
        fm.append(f"user_invocable: {str(bool(s['user_invocable'])).lower()}")
    fm.append("---")
    body = (s.get("prompt_markdown") or "").rstrip()
    pointer = (
        f"<!-- Claude Code adapter for agent `{name}`. Canonical file: "
        f"docs/agents/{name}.md (harness-neutral). Both are generated from the "
        f"same Neotoma agent_definition; daemons load the prompt from Neotoma "
        f"directly, not from this file. -->"
    )
    return SKILL_HEADER + "\n" + "\n".join(fm) + "\n\n" + pointer + "\n\n" + body + "\n"


def index_md(agents: list[dict]) -> str:
    L = [
        "# Ateles agents",
        "",
        "The canonical, harness-neutral file for every `agent_definition` entity in Neotoma. "
        "Each `<name>.md` carries the full definition (frontmatter + metadata table + operational "
        "prompt) and is the source any harness can read. Neotoma is canonical; these files are "
        "generated — see `execution/scripts/render_agent_docs.py`. The Claude Code harness loads a "
        "generated mirror at `.claude/skills/<name>/SKILL.md` (same entity, minimal frontmatter). "
        "Per agent_policy `ent_c3c5e4a9350250cbf69e08bf`, prompts are public and PII-free.",
        "",
        "| Agent | Tier | Genus | Status | Prompt | File |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for s in agents:
        name = s["name"]
        prompt = "✅" if (s.get("prompt_markdown") or "").strip() else "—"
        L.append(
            f"| {name} | {s.get('tier','')} | {s.get('genus','')} | "
            f"{s.get('status','')} | {prompt} | [{name}.md]({name}.md) |"
        )
    L += ["", f"*{len(agents)} agents. Generated from Neotoma — do not edit directly.*", ""]
    return "\n".join(L)


def _has_skill(s: dict) -> bool:
    """A SKILL.md is mirrored only for agents with a prompt that aren't merely
    proposed — a `proposed` prompt is a design sketch, not a running prompt."""
    return bool((s.get("prompt_markdown") or "").strip()) and s.get("status") != "proposed"


def _targets(agents: list[dict]) -> dict[Path, str]:
    """Map every output path → its canonical content."""
    out: dict[Path, str] = {}
    out[AGENTS_DOC_DIR / "README.md"] = index_md(agents)
    for s in agents:
        out[AGENTS_DOC_DIR / f"{s['name']}.md"] = canonical_agent_file(s)
        if _has_skill(s):
            out[SKILLS_DIR / s["name"] / "SKILL.md"] = skill_md(s)
    return out


def _orphans(agents: list[dict]) -> list[Path]:
    """Stale agent-mirror files on disk with no matching current agent.

    When an agent is renamed (e.g. gryllus -> cicada) or removed, its old
    docs/agents/<old>.md and .claude/skills/<old>/SKILL.md linger. We only
    treat a file as an orphan if it is unambiguously an agent_definition
    mirror (carries the `entity_type: agent_definition` marker), so authored
    non-agent skills (commit, analyze, …) are never touched.
    """
    current = {s["name"] for s in agents}
    orphans: list[Path] = []
    # docs/agents/<name>.md
    if AGENTS_DOC_DIR.exists():
        for p in AGENTS_DOC_DIR.glob("*.md"):
            if p.name == "README.md" or p.stem in current:
                continue
            if "entity_type: agent_definition" in p.read_text():
                orphans.append(p)
    # .claude/skills/<name>/SKILL.md
    if SKILLS_DIR.exists():
        for d in SKILLS_DIR.iterdir():
            if not d.is_dir() or d.name in current:
                continue
            f = d / "SKILL.md"
            if f.exists() and "entity_type: agent_definition" in f.read_text():
                orphans.append(f)
    return sorted(orphans)


def render(agents: list[dict]) -> int:
    targets = _targets(agents)
    for path, content in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content if content.endswith("\n") else content + "\n")
    rel = sorted(str(p.relative_to(REPO_ROOT)) for p in targets)
    print(f"rendered {len(targets)} files for {len(agents)} agents:")
    for r in rel:
        print(f"  {r}")
    orphans = _orphans(agents)
    for p in orphans:
        p.unlink()
        # remove a now-empty skill dir
        if p.parent != SKILLS_DIR and p.parent != AGENTS_DOC_DIR and not any(p.parent.iterdir()):
            p.parent.rmdir()
        print(f"  pruned orphan {p.relative_to(REPO_ROOT)}")
    return 0


def check(agents: list[dict]) -> int:
    targets = _targets(agents)
    failures = []
    for path, content in targets.items():
        canonical = content if content.endswith("\n") else content + "\n"
        on_disk = path.read_text() if path.exists() else ""
        if on_disk != canonical:
            failures.append(str(path.relative_to(REPO_ROOT)))
    orphans = [str(p.relative_to(REPO_ROOT)) for p in _orphans(agents)]
    if failures or orphans:
        if failures:
            print("AGENT MIRROR CHECK FAILED — disk differs from Neotoma:")
            for f in failures:
                print(f"  {f}")
        if orphans:
            print("AGENT MIRROR CHECK FAILED — stale orphan files (renamed/removed agents):")
            for o in orphans:
                print(f"  {o}")
        return 1
    print(f"agent mirror check OK — {len(targets)} files match Neotoma ({len(agents)} agents)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify disk matches Neotoma")
    args = parser.parse_args()
    base_url, token = _load_env()
    agents = fetch_agents(base_url, token)
    return check(agents) if args.check else render(agents)


if __name__ == "__main__":
    sys.exit(main())
