#!/usr/bin/env python3
"""
render_agent_docs.py — render per-agent docs + SKILL.md mirrors from Neotoma.

`agent_definition` entities in Neotoma are canonical. This script projects them
to two one-way (Neotoma → disk) surfaces:

    1. docs/agents/<name>.md   — human/contributor reference card (field
                                 projection: identity, tier, genus, triggers,
                                 context/operational entity types, allowed
                                 tools, AAuth sub, grant, status). NEVER the
                                 raw prompt.
    2. .claude/skills/<name>/SKILL.md — the operational prompt the LLM loads
                                 (frontmatter + prompt_markdown), mirrored
                                 verbatim.

Plus docs/agents/README.md, an index table over all agents.

Per agent_policy ent_c3c5e4a9350250cbf69e08bf, prompt_markdown is always
public and PII-free — so both surfaces are safe for the public repo and there
is no per-agent visibility gating.

A "real agent" = an agent_definition with a `name` AND at least one of
tier/genus/aauth_sub (this excludes skills miscategorized as agent_definition).
`proposed`-status agents are listed in the index but get no SKILL.md (no
running prompt yet).

Usage:
    render_agent_docs.py            # Neotoma → disk
    render_agent_docs.py --check    # exit 1 if disk differs from Neotoma

Env: NEOTOMA_BASE_URL, NEOTOMA_BEARER_TOKEN (falls back to
~/.config/neotoma/.env).
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
import urllib.request
import urllib.error
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
AGENTS_DOC_DIR = REPO_ROOT / "docs" / "agents"
SKILLS_DIR = REPO_ROOT / ".claude" / "skills"

SKILL_HEADER = (
    "<!-- Do not edit this file directly. Corrections go through "
    "`neotoma corrections create`, `neotoma edit <id>`, or the Neotoma "
    "Inspector. This file is regenerated on every relevant write. -->\n"
)


def _load_env() -> tuple[str, str]:
    base_url = os.environ.get("NEOTOMA_BASE_URL", "")
    token = os.environ.get("NEOTOMA_BEARER_TOKEN", "")
    env_path = Path.home() / ".config" / "neotoma" / ".env"
    if (not base_url or not token) and env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            value = value.strip().strip('"').strip("'")
            if key == "NEOTOMA_BASE_URL" and not base_url:
                base_url = value
            elif key == "NEOTOMA_BEARER_TOKEN" and not token:
                token = value
    if not base_url:
        sys.exit("NEOTOMA_BASE_URL not set (env or ~/.config/neotoma/.env)")
    return base_url.rstrip("/"), token


def _request(url: str, token: str, payload: dict | None = None, retries: int = 5) -> dict:
    last = None
    for attempt in range(retries):
        try:
            req = urllib.request.Request(url)
            if token:
                req.add_header("Authorization", f"Bearer {token}")
            if payload is not None:
                req.add_header("Content-Type", "application/json")
                req.data = json.dumps(payload).encode()
            with urllib.request.urlopen(req, timeout=30) as resp:
                return json.loads(resp.read().decode())
        except (urllib.error.URLError, ConnectionError) as exc:
            last = exc
            time.sleep(2)
    raise SystemExit(f"Neotoma unreachable after {retries} tries: {last}")


def _unwrap(entity: dict) -> dict:
    s = entity.get("snapshot", entity)
    if isinstance(s.get("snapshot"), dict):
        s = s["snapshot"]
    return s


def fetch_agents(base_url: str, token: str) -> list[dict]:
    data = _request(f"{base_url}/entities/query", token, {"entity_type": "agent_definition", "limit": 200})
    ents = data.get("entities") or data.get("results") or []
    real = []
    for e in ents:
        s = _unwrap(e)
        if not s.get("name"):
            continue
        if not (s.get("tier") or s.get("genus") or s.get("aauth_sub")):
            continue  # excludes skills miscategorized as agent_definition
        s["_entity_id"] = e.get("entity_id") or s.get("entity_id", "")
        real.append(s)
    real.sort(key=lambda s: s["name"])
    return real


def _as_list(v) -> list[str]:
    if v is None:
        return []
    if isinstance(v, list):
        return [str(x) for x in v]
    return [p.strip() for p in str(v).split(",") if p.strip()]


def reference_card(s: dict) -> str:
    name = s["name"]
    L = [f"# {name}", ""]
    if s.get("description"):
        L += [s["description"], ""]
    L += ["| Field | Value |", "| --- | --- |"]
    rows = [
        ("Tier", s.get("tier")),
        ("Genus", s.get("genus")),
        ("Status", s.get("status")),
        ("AAuth sub", s.get("aauth_sub")),
        ("Agent grant", s.get("agent_grant")),
        ("Triggers", ", ".join(_as_list(s.get("triggers"))) or None),
        ("Allowed tools", ", ".join(_as_list(s.get("allowed_tools") or s.get("tool_allowlist"))) or None),
        ("Context entity types", ", ".join(_as_list(s.get("context_entity_types"))) or None),
        ("Operational entity types", ", ".join(_as_list(s.get("operational_entity_types"))) or None),
        ("Harness", s.get("harness_preferences")),
        ("Output format", s.get("output_format")),
        ("Entity ID", s.get("_entity_id")),
    ]
    for label, val in rows:
        if val:
            L.append(f"| {label} | {val} |")
    L += ["", "---", ""]
    has_prompt = bool((s.get("prompt_markdown") or "").strip())
    if has_prompt:
        L.append(f"Operational prompt: [`.claude/skills/{name}/SKILL.md`](../../.claude/skills/{name}/SKILL.md)")
    else:
        L.append("_No operational prompt authored yet._")
    L += [
        "",
        f"*Reference card mirrored from Neotoma `agent_definition` `{s.get('_entity_id','')}`. "
        "Do not edit directly — correct the entity and run "
        "`python3 execution/scripts/render_agent_docs.py`.*",
        "",
    ]
    return "\n".join(L)


def skill_md(s: dict) -> str:
    """Frontmatter + prompt_markdown, matching the existing mirror shape."""
    fm = ["---"]
    fm.append(f"entity_id: {s.get('_entity_id','')}")
    fm.append("entity_type: agent_definition")
    if s.get("name"):
        fm.append(f"name: {s['name']}")
    if s.get("description"):
        fm.append(f"description: {s['description']}")
    triggers = _as_list(s.get("triggers"))
    if triggers:
        fm.append("triggers:")
        fm += [f"  - {t}" for t in triggers]
    if s.get("user_invocable") is not None:
        fm.append(f"user_invocable: {str(bool(s['user_invocable'])).lower()}")
    fm.append("---")
    body = (s.get("prompt_markdown") or "").rstrip()
    return SKILL_HEADER + "\n" + "\n".join(fm) + "\n\n" + body + "\n"


def index_md(agents: list[dict]) -> str:
    L = [
        "# Ateles agents",
        "",
        "Reference cards for every `agent_definition` entity in Neotoma, mirrored to disk. "
        "Neotoma is canonical; these files are generated — see "
        "`execution/scripts/render_agent_docs.py`. Operational prompts live in "
        "`.claude/skills/<name>/SKILL.md` (also mirrored). Per agent_policy "
        "`ent_c3c5e4a9350250cbf69e08bf`, prompts are public and PII-free.",
        "",
        "| Agent | Tier | Genus | Status | Prompt | Card |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for s in agents:
        name = s["name"]
        prompt = "✅" if (s.get("prompt_markdown") or "").strip() else "—"
        L.append(
            f"| {name} | {s.get('tier','')} | {s.get('genus','')} | "
            f"{s.get('status','')} | {prompt} | [{name}.md]({name}.md) |"
        )
    L += ["", f"*{len(agents)} agents. Generated from Neotoma — do not edit directly.*", ""]
    return "\n".join(L)


def _has_skill(s: dict) -> bool:
    """A SKILL.md is mirrored only for agents with a prompt that aren't merely
    proposed — a `proposed` prompt is a design sketch, not a running prompt."""
    return bool((s.get("prompt_markdown") or "").strip()) and s.get("status") != "proposed"


def _targets(agents: list[dict]) -> dict[Path, str]:
    """Map every output path → its canonical content."""
    out: dict[Path, str] = {}
    out[AGENTS_DOC_DIR / "README.md"] = index_md(agents)
    for s in agents:
        out[AGENTS_DOC_DIR / f"{s['name']}.md"] = reference_card(s)
        if _has_skill(s):
            out[SKILLS_DIR / s["name"] / "SKILL.md"] = skill_md(s)
    return out


def render(agents: list[dict]) -> int:
    targets = _targets(agents)
    for path, content in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content if content.endswith("\n") else content + "\n")
    rel = sorted(str(p.relative_to(REPO_ROOT)) for p in targets)
    print(f"rendered {len(targets)} files for {len(agents)} agents:")
    for r in rel:
        print(f"  {r}")
    return 0


def check(agents: list[dict]) -> int:
    targets = _targets(agents)
    failures = []
    for path, content in targets.items():
        canonical = content if content.endswith("\n") else content + "\n"
        on_disk = path.read_text() if path.exists() else ""
        if on_disk != canonical:
            failures.append(str(path.relative_to(REPO_ROOT)))
    if failures:
        print("AGENT MIRROR CHECK FAILED — disk differs from Neotoma:")
        for f in failures:
            print(f"  {f}")
        return 1
    print(f"agent mirror check OK — {len(targets)} files match Neotoma ({len(agents)} agents)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify disk matches Neotoma")
    args = parser.parse_args()
    base_url, token = _load_env()
    agents = fetch_agents(base_url, token)
    return check(agents) if args.check else render(agents)


if __name__ == "__main__":
    sys.exit(main())
