#!/usr/bin/env python3
"""
render_plan_page.py — render a shared rendered_page FROM its plan entity.

The plan is canonical. The page is a projection of it. No copy of the plan's
content lives in this repo:

    plan entity field           →  rendered_page field
    -------------------------      -------------------
    title / next_steps /        →  html_body
    decisions / goals              (generated by this script)

This is the same direction as render_plan_docs.py, which renders repo docs from
plan fields. An earlier revision of this script had it backwards — the HTML sat
in docs/pages/ and the entity was corrected from it — which created a second,
hand-maintained copy of the plan's content. It diverged immediately: the file
said "22 decisions" while the plan held 26.

Usage:
    render_plan_page.py             # plan → page, then verify by read-back
    render_plan_page.py --check     # exit 1 if the served page is stale
    render_plan_page.py --dump      # print the HTML that would be published

Env: NEOTOMA_BASE_URL, NEOTOMA_BEARER_TOKEN (falls back to
~/.config/neotoma/.env).

HOW UPDATING ACTUALLY WORKS (verified live 2026-09-02)
-------------------------------------------------------
`publish_rendered_page` with an existing entity_id does NOT update content. It
returns success with `created: false` and a NEW access token while continuing
to serve the old bytes — it is a create-and-mint call, not an update call.

The update path is `POST /correct` on the page's fields, which the live /html
route reflects immediately.

Because that distinction is invisible in a success payload, this script NEVER
trusts the write. It embeds a content hash, re-fetches /entities/<id>/html, and
exits non-zero unless the served page carries the hash just written. Byte length
alone is a weak signal — an equal-length edit leaves it unchanged.

PARSING `next_steps`
--------------------
`next_steps` is prose, not a schema. This script parses it with an explicit
grammar and FAILS LOUDLY rather than degrading:

  * every non-empty line between strand headings must be claimed by a step, or
    the run aborts — silent omission is the failure mode that matters here,
    since nobody reloads a page they have already read;
  * a strand with zero steps aborts;
  * zero strands aborts.

A step with no "Blocked by:" clause is NOT an error and NOT an empty cell. In
the plan today, steps 12-15 have no blocker because they are not blockable:
12 and 14 are cross-references ("= step 4", "= step 6"), 13 restates an existing
contract, 15 is an open item for the operator. The renderer omits the "Blocked
by" column for any strand where no step carries one — which reproduces, from the
data, the judgement a human made by hand.
"""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

DEFAULT_PLAN_ID = "ent_18b902cf72822373f9da8ced"
DEFAULT_PAGE_ID = "ent_d6a9e133e1da93c009ac4b76"

USER_AGENT = "ateles-plan-page-sync/2.0"

# ---------------------------------------------------------------- transport


def _load_env() -> tuple[str, str]:
    base_url = os.environ.get("NEOTOMA_BASE_URL", "")
    token = os.environ.get("NEOTOMA_BEARER_TOKEN", "")
    env_path = Path.home() / ".config" / "neotoma" / ".env"
    if (not base_url or not token) and env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            value = value.strip().strip('"').strip("'")
            if key == "NEOTOMA_BASE_URL" and not base_url:
                base_url = value
            elif key == "NEOTOMA_BEARER_TOKEN" and not token:
                token = value
    if not base_url:
        sys.exit("NEOTOMA_BASE_URL not set (env or ~/.config/neotoma/.env)")
    if not token:
        sys.exit("NEOTOMA_BEARER_TOKEN not set (env or ~/.config/neotoma/.env)")
    return base_url.rstrip("/"), token


def _request(url: str, token: str, payload: dict | None = None) -> dict:
    req = urllib.request.Request(url)
    # Cloudflare 1010-blocks urllib's default UA against the hosted instance.
    req.add_header("User-Agent", USER_AGENT)
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    if payload is not None:
        req.add_header("Content-Type", "application/json")
        req.data = json.dumps(payload).encode()
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode())


def _fetch_snapshot(base_url: str, token: str, entity_id: str) -> dict:
    entity = _request(f"{base_url}/entities/{entity_id}", token)
    snapshot = entity.get("snapshot", entity)
    if isinstance(snapshot.get("snapshot"), dict):
        snapshot = snapshot["snapshot"]
    return snapshot


def _fetch_served_html(base_url: str, token: str, page_id: str) -> str:
    """Fetch the page through the same /html route a viewer hits.

    This is the only check that proves a write reached the served page. The
    snapshot can be correct while the rendered route serves something else,
    which is precisely the failure this script exists to catch.
    """
    req = urllib.request.Request(f"{base_url}/entities/{page_id}/html")
    req.add_header("User-Agent", USER_AGENT)
    req.add_header("Authorization", f"Bearer {token}")
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode()


# ------------------------------------------------------------------ parsing


class PlanShapeError(RuntimeError):
    """The plan no longer matches the grammar this renderer understands.

    Raised rather than degrading. A page that quietly drops a strand is worse
    than a page that fails to publish, because nobody reloads it to notice.
    """


STRAND_RE = re.compile(r"^STRAND\s+([A-Z])\s*[—-]\s*(.+?)\s*$", re.M)
STEP_RE = re.compile(r"^(\d+)\.\s+\[([A-Z]+)\]\s+", re.M)
BLOCKED_RE = re.compile(r"Blocked by:\s*(.+?)(?:\.\s|\.$|$)", re.S)


def parse_steps(next_steps: str) -> list[dict]:
    """Parse `next_steps` prose into strands of numbered steps.

    Fails loudly on anything it cannot account for.
    """
    strand_marks = list(STRAND_RE.finditer(next_steps))
    if not strand_marks:
        raise PlanShapeError(
            "no STRAND headings found in next_steps — the plan's shape changed; "
            "update parse_steps() rather than publishing a page missing content"
        )

    strands: list[dict] = []
    for i, mark in enumerate(strand_marks):
        end = strand_marks[i + 1].start() if i + 1 < len(strand_marks) else len(next_steps)
        block = next_steps[mark.end() : end]

        starts = list(STEP_RE.finditer(block))
        if not starts:
            raise PlanShapeError(
                f"strand {mark.group(1)} ({mark.group(2)!r}) contains no parseable "
                f"steps — refusing to publish a page with an empty strand"
            )

        # Any prose before the first step is the strand's own preamble.
        preamble = block[: starts[0].start()].strip()

        steps = []
        for j, sm in enumerate(starts):
            s_end = starts[j + 1].start() if j + 1 < len(starts) else len(block)
            text = block[sm.end() : s_end].strip()

            blocked = None
            bm = BLOCKED_RE.search(text)
            if bm:
                blocked = " ".join(bm.group(1).split())
                # The blocker clause is metadata, not part of the step summary.
                text = text[: bm.start()].strip()

            steps.append(
                {
                    "number": int(sm.group(1)),
                    "who": sm.group(2),
                    "text": " ".join(text.split()),
                    "blocked_by": blocked,
                }
            )

        strands.append(
            {
                "letter": mark.group(1),
                "title": mark.group(2),
                "preamble": preamble,
                "steps": steps,
            }
        )

    # Every step number in the source must appear exactly once in the output.
    # This is the check that catches a step written outside any strand.
    all_numbers = [s["number"] for st in strands for s in st["steps"]]
    source_numbers = [int(m.group(1)) for m in STEP_RE.finditer(next_steps)]
    if sorted(all_numbers) != sorted(source_numbers):
        missing = sorted(set(source_numbers) - set(all_numbers))
        raise PlanShapeError(
            f"steps {missing} appear in next_steps but fall outside every strand "
            f"— they would be silently dropped from the page"
        )
    if len(set(all_numbers)) != len(all_numbers):
        raise PlanShapeError(f"duplicate step numbers in next_steps: {all_numbers}")

    return strands


# ----------------------------------------------------------------- render


WHO_CLASS = {"SWARM": "sw", "SUBAGENT": "sa", "OPERATOR": "op"}

# The plan writes long analytical steps. The page is a scan surface, so each row
# shows the leading sentence and links the reader onward to the plan itself.
def _summarize(text: str, limit: int = 240) -> str:
    first = re.split(r"(?<=[.!?])\s+", text.strip())[0] if text.strip() else ""
    if len(first) > limit:
        first = first[: limit - 1].rstrip() + "…"
    return first


def _esc(text: str) -> str:
    return html.escape(text, quote=False)


def _strand_table(strand: dict) -> str:
    steps = strand["steps"]
    # Reproduce, from the data, the judgement a human made by hand: a strand in
    # which nothing is blocked gets no "Blocked by" column, rather than a column
    # of empty cells.
    has_blockers = any(s["blocked_by"] for s in steps)

    head = "<tr><th>#</th><th>Who</th><th>Step</th>"
    head += "<th>Blocked by</th></tr>" if has_blockers else "</tr>"

    rows = []
    for s in steps:
        cls = WHO_CLASS.get(s["who"], "sw")
        tr = ' class="opr"' if s["who"] == "OPERATOR" else ""
        row = (
            f"<tr{tr}><td>{s['number']}</td>"
            f'<td><span class="tag {cls}">{_esc(s["who"])}</span></td>'
            f"<td>{_esc(_summarize(s['text']))}</td>"
        )
        if has_blockers:
            blocked = s["blocked_by"]
            if blocked:
                row += f"<td>{_esc(_summarize(blocked, 120))}</td>"
            else:
                # Not "unknown" — this step genuinely has no blocker.
                row += '<td class="free">&mdash;</td>'
        rows.append(row + "</tr>")

    return (
        f'<h2>Strand {strand["letter"]} &mdash; {_esc(strand["title"])}</h2>\n'
        + (f'<p class="lead">{_esc(_summarize(strand["preamble"], 400))}</p>\n' if strand["preamble"] else "")
        + "<table>\n<thead>"
        + head
        + "</thead>\n<tbody>\n"
        + "\n".join(rows)
        + "\n</tbody>\n</table>\n"
    )


def build_html(plan: dict) -> str:
    """Generate the page body from the plan snapshot. Pure — no I/O."""
    title = plan.get("title") or "Plan"
    strands = parse_steps(plan.get("next_steps") or "")
    decisions = plan.get("decisions") or {}
    goals = plan.get("goals") or []

    step_count = sum(len(s["steps"]) for s in strands)
    operator_steps = [
        s for st in strands for s in st["steps"] if s["who"] == "OPERATOR"
    ]

    parts = [
        f"<h1>{_esc(title)}</h1>",
        f'<p class="sub">plan <code>{_esc(plan.get("_entity_id", DEFAULT_PLAN_ID))}</code> '
        f"&middot; {step_count} steps, {len(strands)} strands "
        f"&middot; {len(decisions)} decisions recorded "
        f"&middot; generated from the plan entity</p>",
    ]

    overview = plan.get("overview")
    if overview:
        parts.append(f'<div class="callout">\n<p>{_esc(overview)}</p>\n</div>')

    if goals:
        parts.append('<h2 class="first">Goals</h2>\n<ul>')
        parts.extend(f"<li>{_esc(str(g))}</li>" for g in goals)
        parts.append("</ul>")

    for strand in strands:
        parts.append(_strand_table(strand))

    if operator_steps:
        listed = ", ".join(
            f"<strong>{s['number']}</strong>" for s in operator_steps
        )
        parts.append(
            "<h2>Operator-only steps</h2>\n"
            f"<p>{listed} &mdash; these need a decision, not execution. "
            "Every other step is executable by the swarm or a subagent.</p>"
        )

    if decisions:
        parts.append(
            "<h2>Decisions on record</h2>\n"
            '<p class="lead">Settled. Do not re-raise these.</p>\n<ul>'
        )
        for key in sorted(decisions):
            label = key.replace("_", " ")
            parts.append(
                f"<li><strong>{_esc(label)}</strong> &mdash; "
                f"{_esc(_summarize(str(decisions[key]), 300))}</li>"
            )
        parts.append("</ul>")

    return "\n\n".join(parts) + "\n"


# ------------------------------------------------------- verify by read-back


def _fingerprint(text: str) -> str:
    """A short content fingerprint embedded in the page and asserted after write.

    Byte-length alone is a weak signal: an edit that swaps equal-length text
    leaves it unchanged. Comparing full text against the served page is not
    possible either, since the server wraps html_body in its own template. A
    marker derived from the content gives an exact, template-independent check.
    """
    return hashlib.sha256(text.encode()).hexdigest()[:16]


MARKER_RE = re.compile(r"<!-- page-content-hash: ([0-9a-f]{16}) -->")


def _with_marker(body: str) -> tuple[str, str]:
    stripped = MARKER_RE.sub("", body).rstrip() + "\n"
    digest = _fingerprint(stripped)
    return f"{stripped}<!-- page-content-hash: {digest} -->\n", digest


def _served_hash(served: str) -> str | None:
    match = MARKER_RE.search(served)
    return match.group(1) if match else None


# -------------------------------------------------------------------- modes


def _generate(base_url: str, token: str, plan_id: str) -> tuple[str, str]:
    plan = _fetch_snapshot(base_url, token, plan_id)
    plan["_entity_id"] = plan_id
    return _with_marker(build_html(plan))


def render(base_url: str, token: str, plan_id: str, page_id: str) -> int:
    body, digest = _generate(base_url, token, plan_id)

    _request(
        f"{base_url}/correct",
        token,
        {
            "entity_id": page_id,
            "entity_type": "rendered_page",
            "field": "html_body",
            "value": body,
            "idempotency_key": f"render-plan-page-html_body-{digest}",
        },
    )
    print(f"corrected html_body ({len(body)} chars)")

    # The write "succeeded". That proves nothing — verify through the viewer's
    # own path before reporting success.
    served = _fetch_served_html(base_url, token, page_id)
    got = _served_hash(served)
    if got != digest:
        print(
            f"VERIFY FAILED: wrote {digest} but the live page serves "
            f"{got or '<no marker>'} ({len(served)} bytes).\n"
            f"  The correction reported success and the page did NOT change.\n"
            f"  Do not trust the write; investigate before assuming it landed.",
            file=sys.stderr,
        )
        return 1

    print(f"verified: live page serves {digest} ({len(served)} bytes)")
    return 0


def check(base_url: str, token: str, plan_id: str, page_id: str) -> int:
    _, digest = _generate(base_url, token, plan_id)
    served = _fetch_served_html(base_url, token, page_id)
    got = _served_hash(served)
    if got == digest:
        print(f"live page matches the plan ({digest})")
        return 0
    print(
        f"PAGE CHECK FAILED: page serves {got or '<no marker>'} but the plan "
        f"renders to {digest}.\n"
        f"  The plan changed and the page was not republished.\n"
        f"  Run: execution/scripts/render_plan_page.py",
        file=sys.stderr,
    )
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="exit 1 if the served page is stale")
    mode.add_argument("--dump", action="store_true", help="print the HTML and exit")
    parser.add_argument("--plan-id", default=os.environ.get("ATELES_PLAN_ENTITY_ID", DEFAULT_PLAN_ID))
    parser.add_argument("--page-id", default=os.environ.get("ATELES_PLAN_PAGE_ID", DEFAULT_PAGE_ID))
    args = parser.parse_args()

    base_url, token = _load_env()

    try:
        if args.dump:
            body, digest = _generate(base_url, token, args.plan_id)
            print(body)
            print(f"# {len(body)} chars, hash {digest}", file=sys.stderr)
            return 0
        if args.check:
            return check(base_url, token, args.plan_id, args.page_id)
        return render(base_url, token, args.plan_id, args.page_id)
    except PlanShapeError as exc:
        print(f"PLAN SHAPE CHANGED: {exc}", file=sys.stderr)
        return 1
    except urllib.error.HTTPError as exc:
        print(f"HTTP {exc.code} {exc.reason}", file=sys.stderr)
        return 1
    except urllib.error.URLError as exc:
        print(f"network error: {exc.reason}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
