#!/usr/bin/env python3
"""
render_plan_page.py — render a shared rendered_page FROM its plan entity.

The plan is canonical. The page is a projection of it. No copy of the plan's
content lives in this repo:

    plan entity field           →  rendered_page field
    -------------------------      -------------------
    title / next_steps /        →  html_body
    decisions / goals              (generated by this script)

This is the same direction as render_plan_docs.py, which renders repo docs from
plan fields. An earlier revision of this script had it backwards — the HTML sat
in docs/pages/ and the entity was corrected from it — which created a second,
hand-maintained copy of the plan's content. It diverged immediately: the file
said "22 decisions" while the plan held 26.

Usage:
    render_plan_page.py             # plan → page, then verify by read-back
    render_plan_page.py --check     # exit 1 if the served page is stale
    render_plan_page.py --dump      # print the HTML that would be published

Env: NEOTOMA_BASE_URL, NEOTOMA_BEARER_TOKEN (falls back to
~/.config/neotoma/.env).

HOW UPDATING ACTUALLY WORKS (verified live 2026-09-02)
-------------------------------------------------------
`publish_rendered_page` with an existing entity_id does NOT update content. It
returns success with `created: false` and a NEW access token while continuing
to serve the old bytes — it is a create-and-mint call, not an update call.

The update path is `POST /correct` on the page's fields, which the live /html
route reflects immediately.

Because that distinction is invisible in a success payload, this script NEVER
trusts the write. It embeds a content hash, re-fetches /entities/<id>/html, and
exits non-zero unless the served page carries the hash just written. Byte length
alone is a weak signal — an equal-length edit leaves it unchanged.

PARSING `next_steps`
--------------------
`next_steps` is prose, not a schema. This script parses it with an explicit
grammar and FAILS LOUDLY rather than degrading:

  * every non-empty line between strand headings must be claimed by a step, or
    the run aborts — silent omission is the failure mode that matters here,
    since nobody reloads a page they have already read;
  * a strand with zero steps aborts;
  * zero strands aborts.

A step with no "Blocked by:" clause is NOT an error and NOT an empty cell. In
the plan today, steps 12-15 have no blocker because they are not blockable:
12 and 14 are cross-references ("= step 4", "= step 6"), 13 restates an existing
contract, 15 is an open item for the operator. The renderer omits the "Blocked
by" column for any strand where no step carries one — which reproduces, from the
data, the judgement a human made by hand.
"""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

DEFAULT_PLAN_ID = "ent_18b902cf72822373f9da8ced"
DEFAULT_PAGE_ID = "ent_d6a9e133e1da93c009ac4b76"

USER_AGENT = "ateles-plan-page-sync/2.0"

# ---------------------------------------------------------------- transport


def _load_env() -> tuple[str, str]:
    base_url = os.environ.get("NEOTOMA_BASE_URL", "")
    token = os.environ.get("NEOTOMA_BEARER_TOKEN", "")
    env_path = Path.home() / ".config" / "neotoma" / ".env"
    if (not base_url or not token) and env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            value = value.strip().strip('"').strip("'")
            if key == "NEOTOMA_BASE_URL" and not base_url:
                base_url = value
            elif key == "NEOTOMA_BEARER_TOKEN" and not token:
                token = value
    if not base_url:
        sys.exit("NEOTOMA_BASE_URL not set (env or ~/.config/neotoma/.env)")
    if not token:
        sys.exit("NEOTOMA_BEARER_TOKEN not set (env or ~/.config/neotoma/.env)")
    return base_url.rstrip("/"), token


def _request(url: str, token: str, payload: dict | None = None) -> dict:
    req = urllib.request.Request(url)
    # Cloudflare 1010-blocks urllib's default UA against the hosted instance.
    req.add_header("User-Agent", USER_AGENT)
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    if payload is not None:
        req.add_header("Content-Type", "application/json")
        req.data = json.dumps(payload).encode()
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode())


def _fetch_snapshot(base_url: str, token: str, entity_id: str) -> dict:
    entity = _request(f"{base_url}/entities/{entity_id}", token)
    snapshot = entity.get("snapshot", entity)
    if isinstance(snapshot.get("snapshot"), dict):
        snapshot = snapshot["snapshot"]
    return snapshot


def _fetch_served_html(base_url: str, token: str, page_id: str) -> str:
    """Fetch the page through the same /html route a viewer hits.

    This is the only check that proves a write reached the served page. The
    snapshot can be correct while the rendered route serves something else,
    which is precisely the failure this script exists to catch.
    """
    req = urllib.request.Request(f"{base_url}/entities/{page_id}/html")
    req.add_header("User-Agent", USER_AGENT)
    req.add_header("Authorization", f"Bearer {token}")
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode()


# ------------------------------------------------------------------ parsing


class PlanShapeError(RuntimeError):
    """The plan no longer matches the grammar this renderer understands.

    Raised rather than degrading. A page that quietly drops a strand is worse
    than a page that fails to publish, because nobody reloads it to notice.
    """


STRAND_RE = re.compile(r"^STRAND\s+([A-Z])\s*[—-]\s*(.+?)\s*$", re.M)
STEP_RE = re.compile(r"^(\d+)\.\s+\[([A-Z]+)\]\s+", re.M)
BLOCKED_RE = re.compile(r"Blocked by:\s*(.+?)(?:\.\s|\.$|$)", re.S)


def parse_steps(next_steps: str) -> list[dict]:
    """Parse `next_steps` prose into strands of numbered steps.

    Fails loudly on anything it cannot account for.
    """
    strand_marks = list(STRAND_RE.finditer(next_steps))
    if not strand_marks:
        raise PlanShapeError(
            "no STRAND headings found in next_steps — the plan's shape changed; "
            "update parse_steps() rather than publishing a page missing content"
        )

    strands: list[dict] = []
    for i, mark in enumerate(strand_marks):
        end = strand_marks[i + 1].start() if i + 1 < len(strand_marks) else len(next_steps)
        block = next_steps[mark.end() : end]

        starts = list(STEP_RE.finditer(block))
        if not starts:
            raise PlanShapeError(
                f"strand {mark.group(1)} ({mark.group(2)!r}) contains no parseable "
                f"steps — refusing to publish a page with an empty strand"
            )

        # Any prose before the first step is the strand's own preamble.
        preamble = block[: starts[0].start()].strip()

        steps = []
        for j, sm in enumerate(starts):
            s_end = starts[j + 1].start() if j + 1 < len(starts) else len(block)
            text = block[sm.end() : s_end].strip()

            blocked = None
            bm = BLOCKED_RE.search(text)
            if bm:
                blocked = " ".join(bm.group(1).split())
                # The blocker clause is metadata, not part of the step summary.
                text = text[: bm.start()].strip()

            steps.append(
                {
                    "number": int(sm.group(1)),
                    "who": sm.group(2),
                    "text": " ".join(text.split()),
                    "blocked_by": blocked,
                }
            )

        strands.append(
            {
                "letter": mark.group(1),
                "title": mark.group(2),
                "preamble": preamble,
                "steps": steps,
            }
        )

    # Every step number in the source must appear exactly once in the output.
    # This is the check that catches a step written outside any strand.
    all_numbers = [s["number"] for st in strands for s in st["steps"]]
    source_numbers = [int(m.group(1)) for m in STEP_RE.finditer(next_steps)]
    if sorted(all_numbers) != sorted(source_numbers):
        missing = sorted(set(source_numbers) - set(all_numbers))
        raise PlanShapeError(
            f"steps {missing} appear in next_steps but fall outside every strand "
            f"— they would be silently dropped from the page"
        )
    if len(set(all_numbers)) != len(all_numbers):
        raise PlanShapeError(f"duplicate step numbers in next_steps: {all_numbers}")

    return strands


# ----------------------------------------------------------------- render


WHO_CLASS = {"SWARM": "sw", "SUBAGENT": "sa", "OPERATOR": "op"}

# The plan writes long analytical steps. The page is a scan surface, so each row
# shows the leading sentence and links the reader onward to the plan itself. Any
# drop of trailing sentences OR a length cut must be visibly incomplete — a
# truncated cell with no ellipsis reads as the full step, which is the silent
# omission this renderer exists to avoid.
#
# A bare split on `[.!?]\s+` treats "e.g. the" or "Mr. Smith" as a sentence
# boundary and truncates a short step down to a two-character fragment — a
# sharper silent-omission bug than the one this function exists to fix. The
# lookbehind excludes the common abbreviations plan prose actually uses; this
# is a short, practical list, not a full NLP sentence splitter. It must sit
# immediately after `[.!?]`, before the `\s+` that consumes the following
# whitespace — a lookbehind placed after `\s+` sees "Mr. " (with the space)
# rather than "Mr.", so it never matches.
_ABBREV = r"(?<!\bMr\.)(?<!\bMs\.)(?<!\bDr\.)(?<!e\.g\.)(?<!i\.e\.)(?<!\betc\.)(?<!\bvs\.)"
SENTENCE_SPLIT_RE = re.compile(r"(?<=[.!?])" + _ABBREV + r"\s+")


def _summarize(text: str, limit: int = 240) -> str:
    text = text.strip()
    if not text:
        return ""
    parts = SENTENCE_SPLIT_RE.split(text)
    first = parts[0]
    truncated = len(parts) > 1 or len(first) > limit
    if len(first) > limit:
        first = first[: limit - 1].rstrip()
    if truncated and "…" not in first[-3:]:
        # Strip exactly one trailing '.' — the sentence terminator we just cut
        # on — before appending the ellipsis. NOT rstrip(".") or a "\.+$"
        # collapse: either would also eat a decimal point, over-strip a
        # multi-period abbreviation like "e.g." that survived the split, or
        # collapse a source "..."/"…." the author already wrote. If the tail
        # already reads as incomplete (ends in one of those), leave it as-is.
        if first.endswith("...") or first.endswith("…."):
            pass
        elif first.endswith("."):
            first = first[:-1] + "…"
        else:
            first = first + "…"
    return first


def _esc(text: str) -> str:
    return html.escape(text, quote=False)


SLUG_RE = re.compile(r"[^a-z0-9]+")


def _slug(text: str, seen: set) -> str:
    """Slugify heading text into a stable id; de-dupe collisions with -2, -3, …

    `seen` is a caller-owned set of every id already issued on the page (keyed
    by the id string itself, not the base text), threaded across every
    heading. Two headings with the same text (e.g. two strands both titled
    "REVIEW") get distinct anchors — and so does a heading whose literal text
    already looks like a generated suffix (a strand titled "Goals 2" sitting
    next to a second "Goals" heading), since the candidate is checked against
    every id already taken, not just re-derived from a per-base counter that
    the literal text could coincidentally match.
    """
    base = SLUG_RE.sub("-", text.lower()).strip("-") or "section"
    candidate = base
    n = 2
    while candidate in seen:
        candidate = f"{base}-{n}"
        n += 1
    seen.add(candidate)
    return candidate


def _heading(level: int, text: str, seen: set) -> str:
    """A deep-linkable heading: stable id + hover `.hanchor` permalink.

    Required by the draft-rendered-page skill (`RENDERED_PAGE_NO_HEADING_ANCHORS`
    on conformance_policy ent_edd087ca6482f7d93162f9a2) so a reader can point
    someone at "Strand B" by URL. CSS ships via PAGE_CSS / custom_css.
    """
    hid = _slug(text, seen)
    esc = _esc(text)
    return f'<h{level} id="{hid}">{esc} <a class="hanchor" href="#{hid}">#</a></h{level}>'


def _plan_link(plan_id: str, label: str) -> str:
    return f'<a href="/entities/{_esc(plan_id)}">{label}</a>'


def _strand_table(strand: dict, plan_id: str, seen: set) -> str:
    steps = strand["steps"]
    # Reproduce, from the data, the judgement a human made by hand: a strand in
    # which nothing is blocked gets no "Blocked by" column, rather than a column
    # of empty cells.
    has_blockers = any(s["blocked_by"] for s in steps)

    head = "<tr><th>#</th><th>Who</th><th>Step</th>"
    head += "<th>Blocked by</th></tr>" if has_blockers else "</tr>"

    rows = []
    for s in steps:
        cls = WHO_CLASS.get(s["who"], "sw")
        tr = ' class="opr"' if s["who"] == "OPERATOR" else ""
        summary = _summarize(s["text"])
        step_cell = _esc(summary)
        if summary != s["text"].strip():
            # Truncated: point the reader onward to the full step text.
            step_cell += f' {_plan_link(plan_id, "full step")}'
        row = (
            f"<tr{tr}><td>{s['number']}</td>"
            f'<td><span class="tag {cls}">{_esc(s["who"])}</span></td>'
            f"<td>{step_cell}</td>"
        )
        if has_blockers:
            blocked = s["blocked_by"]
            if blocked:
                row += f"<td>{_esc(_summarize(blocked, 120))}</td>"
            else:
                # Not "unknown" — this step genuinely has no blocker.
                row += '<td class="free">&mdash;</td>'
        rows.append(row + "</tr>")

    heading = _heading(2, f'Strand {strand["letter"]} — {strand["title"]}', seen)
    return (
        f"{heading}\n"
        + (f'<p class="lead">{_esc(_summarize(strand["preamble"], 400))}</p>\n' if strand["preamble"] else "")
        + "<table>\n<thead>"
        + head
        + "</thead>\n<tbody>\n"
        + "\n".join(rows)
        + "\n</tbody>\n</table>\n"
    )


def build_html(plan: dict) -> str:
    """Generate the page body from the plan snapshot. Pure — no I/O."""
    title = plan.get("title") or "Plan"
    plan_id = plan.get("_entity_id", DEFAULT_PLAN_ID)
    strands = parse_steps(plan.get("next_steps") or "")
    decisions = plan.get("decisions") or {}
    goals = plan.get("goals") or []
    seen_ids: set = set()

    step_count = sum(len(s["steps"]) for s in strands)
    operator_steps = [
        s for st in strands for s in st["steps"] if s["who"] == "OPERATOR"
    ]

    parts = [
        _heading(1, title, seen_ids),
        f'<p class="sub">Scan surface of {_plan_link(plan_id, f"plan <code>{_esc(plan_id)}</code>")} '
        f"&middot; {step_count} steps, {len(strands)} strands "
        f"&middot; {len(decisions)} decisions recorded "
        f"&middot; summarized here, full step text on the plan entity</p>",
    ]

    overview = plan.get("overview")
    if overview:
        parts.append(f'<div class="callout">\n<p>{_esc(overview)}</p>\n</div>')

    if goals:
        parts.append(_heading(2, "Goals", seen_ids) + "\n<ul>")
        parts.extend(f"<li>{_esc(str(g))}</li>" for g in goals)
        parts.append("</ul>")

    for strand in strands:
        parts.append(_strand_table(strand, plan_id, seen_ids))

    if operator_steps:
        listed = ", ".join(str(s["number"]) for s in operator_steps)
        parts.append(
            _heading(2, "Operator-only steps", seen_ids) + "\n"
            f"<p>Steps {listed} need a decision, not execution. "
            "Every other step is executable by the swarm or a subagent.</p>"
        )

    if decisions:
        parts.append(
            _heading(2, "Decisions on record", seen_ids) + "\n"
            '<p class="lead">Settled. Do not re-raise these.</p>\n<ul>'
        )
        for key in sorted(decisions):
            label = key.replace("_", " ")
            parts.append(
                f'<li><span class="dlabel">{_esc(label)}</span> &mdash; '
                f"{_esc(_summarize(str(decisions[key]), 300))}</li>"
            )
        parts.append("</ul>")

    return "\n\n".join(parts) + "\n"


# Hover-revealed heading permalinks (draft-rendered-page skill, "Deep-linkable
# headings"). Host defaults do not define `.hanchor`; without this CSS the
# anchors render but are visually unusable, which fails the same rule.
PAGE_CSS = """
h1,h2,h3,h4,h5,h6{ scroll-margin-top:1.5rem; }
a.hanchor{ margin-left:.4em; font-weight:400; font-size:.85em; text-decoration:none; opacity:0; transition:opacity .12s ease; color:var(--muted); }
h1:hover>a.hanchor,h2:hover>a.hanchor,h3:hover>a.hanchor,h4:hover>a.hanchor,h5:hover>a.hanchor,h6:hover>a.hanchor{ opacity:.5; }
a.hanchor:hover{ opacity:1; }
.dlabel{ font-weight:600; }
""".strip()


# ------------------------------------------------------- verify by read-back


def _fingerprint(text: str) -> str:
    """A short content fingerprint embedded in the page and asserted after write.

    Byte-length alone is a weak signal: an edit that swaps equal-length text
    leaves it unchanged. Comparing full text against the served page is not
    possible either, since the server wraps html_body in its own template. A
    marker derived from the content gives an exact, template-independent check.
    """
    return hashlib.sha256(text.encode()).hexdigest()[:16]


MARKER_RE = re.compile(r"<!-- page-content-hash: ([0-9a-f]{16}) -->")


def _with_marker(body: str) -> tuple[str, str]:
    stripped = MARKER_RE.sub("", body).rstrip() + "\n"
    digest = _fingerprint(stripped)
    return f"{stripped}<!-- page-content-hash: {digest} -->\n", digest


def _served_hash(served: str) -> str | None:
    match = MARKER_RE.search(served)
    return match.group(1) if match else None


# -------------------------------------------------------------------- modes


def _generate(base_url: str, token: str, plan_id: str) -> tuple[str, str]:
    plan = _fetch_snapshot(base_url, token, plan_id)
    plan["_entity_id"] = plan_id
    return _with_marker(build_html(plan))


def _correct_field(base_url: str, token: str, page_id: str, field: str, value: str, digest: str) -> None:
    """POST one /correct call for a single rendered_page field.

    Kept separate per field (rather than one call try/excepted as a unit) so a
    failure names which field it was — html_body and custom_css are corrected
    independently, and a failure on the second must not be reported the same
    way as a failure on the first, since the first may have already landed.
    """
    _request(
        f"{base_url}/correct",
        token,
        {
            "entity_id": page_id,
            "entity_type": "rendered_page",
            "field": field,
            "value": value,
            "idempotency_key": f"render-plan-page-{field}-{digest}",
        },
    )
    print(f"corrected {field} ({len(value)} chars)")


def render(base_url: str, token: str, plan_id: str, page_id: str) -> int:
    body, digest = _generate(base_url, token, plan_id)

    try:
        _correct_field(base_url, token, page_id, "html_body", body, digest)
    except (urllib.error.HTTPError, urllib.error.URLError) as exc:
        print(f"html_body correction FAILED (nothing landed): {exc}", file=sys.stderr)
        return 1

    # The .hanchor affordance in html_body is unusable without this CSS — push
    # it every run so a manual custom_css edit can never drift from the markup
    # the generator emits.
    css_digest = _fingerprint(PAGE_CSS)
    try:
        _correct_field(base_url, token, page_id, "custom_css", PAGE_CSS, css_digest)
    except (urllib.error.HTTPError, urllib.error.URLError) as exc:
        print(
            f"custom_css correction FAILED: {exc}\n"
            f"  html_body already landed (verify separately with --check);"
            f" only the CSS half is stale — re-run to retry.",
            file=sys.stderr,
        )
        return 1

    # Both writes "succeeded". That proves nothing — verify through the
    # viewer's own path before reporting success. html_body carries its own
    # content-hash marker; custom_css has no such marker in the served /html
    # body, so it is verified by re-fetching the entity snapshot instead.
    served = _fetch_served_html(base_url, token, page_id)
    got = _served_hash(served)
    if got != digest:
        print(
            f"VERIFY FAILED: wrote {digest} but the live page serves "
            f"{got or '<no marker>'} ({len(served)} bytes).\n"
            f"  The correction reported success and the page did NOT change.\n"
            f"  Do not trust the write; investigate before assuming it landed.",
            file=sys.stderr,
        )
        return 1

    page_snapshot = _fetch_snapshot(base_url, token, page_id)
    if page_snapshot.get("custom_css") != PAGE_CSS:
        print(
            "VERIFY FAILED: custom_css correction reported success but the "
            "entity snapshot does not carry the CSS just written.\n"
            "  The .hanchor anchors will render with no styling until this "
            "is corrected — do not trust the write.",
            file=sys.stderr,
        )
        return 1

    print(f"verified: live page serves {digest} ({len(served)} bytes), custom_css confirmed")
    return 0


def check(base_url: str, token: str, plan_id: str, page_id: str) -> int:
    _, digest = _generate(base_url, token, plan_id)
    served = _fetch_served_html(base_url, token, page_id)
    got = _served_hash(served)
    if got == digest:
        print(f"live page matches the plan ({digest})")
        return 0
    print(
        f"PAGE CHECK FAILED: page serves {got or '<no marker>'} but the plan "
        f"renders to {digest}.\n"
        f"  The plan changed and the page was not republished.\n"
        f"  Run: execution/scripts/render_plan_page.py",
        file=sys.stderr,
    )
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="exit 1 if the served page is stale")
    mode.add_argument("--dump", action="store_true", help="print the HTML and exit")
    parser.add_argument("--plan-id", default=os.environ.get("ATELES_PLAN_ENTITY_ID", DEFAULT_PLAN_ID))
    parser.add_argument("--page-id", default=os.environ.get("ATELES_PLAN_PAGE_ID", DEFAULT_PAGE_ID))
    args = parser.parse_args()

    base_url, token = _load_env()

    try:
        if args.dump:
            body, digest = _generate(base_url, token, args.plan_id)
            print(body)
            print(f"# {len(body)} chars, hash {digest}", file=sys.stderr)
            return 0
        if args.check:
            return check(base_url, token, args.plan_id, args.page_id)
        return render(base_url, token, args.plan_id, args.page_id)
    except PlanShapeError as exc:
        print(f"PLAN SHAPE CHANGED: {exc}", file=sys.stderr)
        return 1
    except urllib.error.HTTPError as exc:
        print(f"HTTP {exc.code} {exc.reason}", file=sys.stderr)
        return 1
    except urllib.error.URLError as exc:
        print(f"network error: {exc.reason}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
