#!/usr/bin/env python3
"""
sync_skills.py — reconcile on-disk Claude Code SKILL.md files with their
canonical Neotoma `skill` entities.

Neotoma `skill` entities are canonical (edited via `neotoma corrections create`
on the `content` field, per the skill_md_neotoma_first rule). Each on-disk
`SKILL.md` is a generated MIRROR keyed by an `entity_id` in its frontmatter.
Nothing reconciled these before, so local mirrors silently drifted (a stale
`/end`) and entity-only skills never reached disk at all (`draft-rendered-page`
existed only in Neotoma, so it never loaded into any harness).

This is the sibling of render_agent_docs.py (which does the same for
`agent_definition` entities); it shares the same `_request`/`_load_env` shape
and the same `--check` discipline so both can run in pre-commit / CI.

What it does:
  * Pull every `skill` entity from Neotoma.
  * For each, locate its on-disk mirror by `entity_id` (searching the known
    skill roots), or by slug/name if no entity_id is on disk yet.
  * Rebuild the canonical SKILL.md (do-not-edit header + minimal frontmatter
    from the entity fields + the `content` body) and compare / write.

Two skill roots are handled:
  * USER root  — ~/.claude/skills/<slug>  (symlinks into the neotoma-prod
                 skills checkout; we write through the symlink to its target).
  * REPO root  — <repo>/.claude/skills/<slug>  (real dirs, committed).
  An entity's home is inferred from where its mirror already lives; a brand-new
  entity-only skill is installed to the root named by --install-root
  (default: repo).

Usage:
    sync_skills.py --check                 # exit 1 if any mirror differs / missing
    sync_skills.py                         # write all drifted mirrors (in place)
    sync_skills.py --install <slug|id>     # materialize one entity-only skill
    sync_skills.py --install <slug|id> --install-root user
    sync_skills.py --only <slug|id> [...]  # restrict to specific skills

Env: NEOTOMA_BASE_URL, NEOTOMA_BEARER_TOKEN (falls back to
~/.config/neotoma/.env). Read-only against Neotoma; never writes entities.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
import urllib.request
import urllib.error
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
REPO_SKILLS_DIR = REPO_ROOT / ".claude" / "skills"
USER_SKILLS_DIR = Path.home() / ".claude" / "skills"

DO_NOT_EDIT = (
    "<!-- Do not edit this file directly. Corrections go through "
    "`neotoma corrections create` on the skill entity's content field "
    "(skill_md_neotoma_first rule). This file is a generated mirror; the "
    "Neotoma `skill` entity is canonical. Regenerate with "
    "execution/scripts/sync_skills.py. -->\n"
)

# Frontmatter keys we project from the entity (used only when writing a brand-new
# mirror that has no existing frontmatter to preserve). `content` is the body.
FM_SCALAR = ["name", "description", "slug", "user_invocable"]
FM_LIST = ["triggers", "supported_harnesses"]


# --------------------------------------------------------------------------- IO

def _load_env() -> tuple[str, str]:
    base_url = os.environ.get("NEOTOMA_BASE_URL", "")
    token = os.environ.get("NEOTOMA_BEARER_TOKEN", "")
    env_path = Path.home() / ".config" / "neotoma" / ".env"
    if (not base_url or not token) and env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            value = value.strip().strip('"').strip("'")
            if key == "NEOTOMA_BASE_URL" and not base_url:
                base_url = value
            elif key == "NEOTOMA_BEARER_TOKEN" and not token:
                token = value
    if not base_url:
        # Final fallback to the apis daemons' default rather than failing hard;
        # the env var and ~/.config/neotoma/.env still take precedence above.
        base_url = "https://neotoma.markmhendrickson.com"
    return base_url.rstrip("/"), token


def _request(url: str, token: str, payload: dict | None = None, retries: int = 5) -> dict:
    last = None
    for _ in range(retries):
        try:
            req = urllib.request.Request(url)
            # Prod WAF returns 403 for requests with no User-Agent.
            req.add_header("User-Agent", "ateles-mirror-tools/1.0")
            if token:
                req.add_header("Authorization", f"Bearer {token}")
            if payload is not None:
                req.add_header("Content-Type", "application/json")
                req.data = json.dumps(payload).encode()
            with urllib.request.urlopen(req, timeout=30) as resp:
                return json.loads(resp.read().decode())
        except (urllib.error.URLError, ConnectionError) as exc:
            last = exc
            time.sleep(2)
    raise SystemExit(f"Neotoma unreachable after {retries} tries: {last}")


def _unwrap(entity: dict) -> dict:
    s = entity.get("snapshot", entity)
    if isinstance(s.get("snapshot"), dict):
        s = s["snapshot"]
    return s


def fetch_skills(base_url: str, token: str, disk_id_index: dict[str, Path] | None = None) -> list[dict]:
    data = _request(
        f"{base_url}/entities/query", token, {"entity_type": "skill", "limit": 500}
    )
    ents = data.get("entities") or data.get("results") or []
    by_slug: dict[str, list[dict]] = {}
    for e in ents:
        s = _unwrap(e)
        name = s.get("name")
        content = s.get("content") or ""
        # A syncable skill needs a name and a real body.
        if not name or not content.strip():
            continue
        s["_entity_id"] = e.get("entity_id") or s.get("entity_id", "")
        s["_slug"] = s.get("slug") or name
        by_slug.setdefault(s["_slug"], []).append(s)

    disk_id_index = disk_id_index or {}
    skills: list[dict] = []
    for slug, group in by_slug.items():
        if len(group) == 1:
            skills.append(group[0])
            continue
        # Duplicate slug in Neotoma. Prefer the entity already mirrored on disk;
        # else the longest content (most-developed). Warn either way.
        on_disk = [g for g in group if g["_entity_id"] in disk_id_index]
        chosen = (on_disk or sorted(group, key=lambda g: len(g["content"]), reverse=True))[0]
        ids = ", ".join(g["_entity_id"] for g in group)
        print(
            f"WARN duplicate skill slug {slug!r} across {len(group)} entities "
            f"({ids}); using {chosen['_entity_id']}"
            f"{' (on disk)' if on_disk else ' (longest content)'}.",
            file=sys.stderr,
        )
        skills.append(chosen)
    skills.sort(key=lambda s: s["_slug"])
    return skills


# --------------------------------------------------------------- rendering

def _yaml_scalar(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    s = str(v)
    # quote if it contains a colon-space or leading special char
    if any(t in s for t in [": ", " #"]) or s[:1] in "[]{}#&*!|>%@`\"'":
        return json.dumps(s, ensure_ascii=False)
    return s


def _split_frontmatter(text: str) -> tuple[str, str]:
    """Return (frontmatter_block_including_fences_and_leading_header, body).

    Handles an optional leading HTML comment (do-not-edit header) before the
    `---` fences, then the YAML block, then the body. If no frontmatter is
    found, frontmatter_block is "" and body is the whole text.
    """
    lines = text.splitlines(keepends=True)
    i = 0
    lead = ""
    # consume a leading HTML comment + blank lines
    if i < len(lines) and lines[i].lstrip().startswith("<!--"):
        while i < len(lines):
            lead += lines[i]
            if "-->" in lines[i]:
                i += 1
                break
            i += 1
        while i < len(lines) and lines[i].strip() == "":
            lead += lines[i]
            i += 1
    if i < len(lines) and lines[i].strip() == "---":
        fm = lead + lines[i]
        i += 1
        while i < len(lines):
            fm += lines[i]
            if lines[i].strip() == "---":
                i += 1
                break
            i += 1
        body = "".join(lines[i:])
        return fm, body
    return "", text


def _fresh_frontmatter(skill: dict) -> str:
    """Build minimal frontmatter for a brand-new mirror (no existing file)."""
    fm_lines = ["---"]
    for k in FM_SCALAR:
        if skill.get(k) is not None and skill.get(k) != "":
            fm_lines.append(f"{k}: {_yaml_scalar(skill[k])}")
    for k in FM_LIST:
        vals = skill.get(k)
        if isinstance(vals, str):
            try:
                vals = json.loads(vals)
            except Exception:
                vals = [vals]
        if vals:
            fm_lines.append(f"{k}:")
            for item in vals:
                fm_lines.append(f"  - {_yaml_scalar(item)}")
    fm_lines.append(f"entity_id: {skill['_entity_id']}")
    fm_lines.append("---")
    return "\n".join(fm_lines) + "\n"


def canonical_text(skill: dict, existing: str | None) -> str:
    """The on-disk text this skill SHOULD have.

    The entity's `content` may itself be either body-only OR a full document
    that already begins with its own `---` frontmatter block — both shapes occur
    in prod. Split content into (its own fm, its body) first so we never stack
    two frontmatter blocks.

    Frontmatter precedence: the existing file's fm (preserve it — don't churn
    formatting/ordering on a reconcile) → else the entity content's own fm →
    else minimal generated fm. Exactly one block is emitted, with `entity_id`
    guaranteed present in it.
    """
    content_fm, content_body = _split_frontmatter(skill["content"])
    body = content_body.strip("\n") + "\n"

    existing_fm = ""
    if existing:
        existing_fm, _ = _split_frontmatter(existing)

    if existing_fm:
        fm_block = existing_fm
    elif content_fm:
        # content's fm may already carry its own do-not-edit header (captured by
        # _split_frontmatter); only prepend ours if it doesn't, to avoid stacking
        # two header comments.
        header = "" if content_fm.lstrip().startswith("<!--") else DO_NOT_EDIT
        fm_block = header + _ensure_entity_id(content_fm, skill["_entity_id"])
    else:
        fm_block = DO_NOT_EDIT + _fresh_frontmatter(skill)

    return fm_block.rstrip("\n") + "\n\n" + body


def _ensure_entity_id(fm_block: str, entity_id: str) -> str:
    """Return the YAML frontmatter block with an `entity_id:` line present.

    `fm_block` includes its `---` fences (and may include a leading HTML
    comment). If it already declares entity_id, return unchanged; else insert
    the line just before the closing fence.
    """
    if "entity_id:" in fm_block:
        return fm_block
    lines = fm_block.splitlines(keepends=True)
    # find the LAST '---' fence (the closer) and insert before it
    for idx in range(len(lines) - 1, -1, -1):
        if lines[idx].strip() == "---":
            lines.insert(idx, f"entity_id: {entity_id}\n")
            break
    return "".join(lines)


# ------------------------------------------------------ disk discovery

def _index_disk_mirrors() -> tuple[dict[str, Path], dict[str, Path]]:
    """Return (by_entity_id, by_slug) → SKILL.md path, across both roots.

    The slug index (keyed on the skill's directory name) is a fallback for
    mirrors that exist on disk but carry no `entity_id` frontmatter (e.g. the
    neotoma-prod user-level skills), so they aren't misreported as "missing".
    User symlinks are resolved to their real target.
    """
    by_id: dict[str, Path] = {}
    by_slug: dict[str, Path] = {}
    for root in (REPO_SKILLS_DIR, USER_SKILLS_DIR):
        if not root.exists():
            continue
        for skill_md in root.glob("*/SKILL.md"):
            slug = skill_md.parent.name
            by_slug.setdefault(slug, skill_md.resolve())
            try:
                head = skill_md.read_text(errors="replace")[:2000]
            except OSError:
                continue
            for line in head.splitlines():
                line = line.strip()
                if line.startswith("entity_id:"):
                    by_id[line.split(":", 1)[1].strip()] = skill_md.resolve()
                    break
    return by_id, by_slug


def _target_path(skill: dict, disk_id_index: dict[str, Path],
                 disk_slug_index: dict[str, Path], install_root: str) -> Path:
    eid = skill["_entity_id"]
    if eid in disk_id_index:
        return disk_id_index[eid]
    if skill["_slug"] in disk_slug_index:
        # present on disk but unlinked by entity_id — treat as its mirror
        return disk_slug_index[skill["_slug"]]
    # not on disk anywhere → install to the chosen root, by slug
    root = USER_SKILLS_DIR if install_root == "user" else REPO_SKILLS_DIR
    return (root / skill["_slug"] / "SKILL.md").resolve()


# --------------------------------------------------------------- ops

def _selected(skills: list[dict], only: list[str]) -> list[dict]:
    if not only:
        return skills
    want = set(only)
    sel = [s for s in skills if s["_slug"] in want or s["_entity_id"] in want]
    missing = want - {s["_slug"] for s in sel} - {s["_entity_id"] for s in sel}
    if missing:
        sys.exit(f"no skill entity matched: {', '.join(sorted(missing))}")
    return sel


def run_check(skills: list[dict], id_index: dict, slug_index: dict, install_root: str) -> int:
    drift, missing = [], []
    for s in skills:
        path = _target_path(s, id_index, slug_index, install_root)
        if not path.exists():
            missing.append((s["_slug"], path))
            continue
        existing = path.read_text()
        if existing != canonical_text(s, existing):
            drift.append((s["_slug"], path))
    if not drift and not missing:
        print(f"OK — {len(skills)} skill mirror(s) match Neotoma (body-level).")
        return 0
    for slug, p in missing:
        print(f"MISSING  {slug:28} (entity-only; no mirror on disk) -> {p}")
    for slug, p in drift:
        print(f"DRIFTED  {slug:28} {p}")
    print(f"\n{len(missing)} missing, {len(drift)} drifted (body differs from Neotoma).")
    print("Run without --check to write, or --install <slug> for a missing one.")
    return 1


def run_write(skills: list[dict], id_index: dict, slug_index: dict, install_root: str,
              install_only: bool) -> int:
    wrote = []
    for s in skills:
        path = _target_path(s, id_index, slug_index, install_root)
        existed = path.exists()
        if install_only and existed:
            continue  # --install only materializes new ones
        existing = path.read_text() if existed else None
        canonical = canonical_text(s, existing)
        if existed and existing == canonical:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(canonical)
        wrote.append((s["_slug"], path, "installed" if not existed else "updated"))
    if not wrote:
        print("nothing to do — all mirrors current.")
        return 0
    print(f"wrote {len(wrote)} skill mirror(s):")
    for slug, p, kind in wrote:
        print(f"  {kind:9} {slug:28} {p}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Sync Neotoma skill entities → on-disk SKILL.md mirrors.")
    ap.add_argument("--check", action="store_true", help="report drift/missing, exit 1 if any; no writes")
    ap.add_argument("--install", metavar="SLUG_OR_ID", action="append", default=[],
                    help="materialize one entity-only skill to disk (repeatable)")
    ap.add_argument("--install-root", choices=["repo", "user"], default="repo",
                    help="where to install brand-new mirrors (default: repo)")
    ap.add_argument("--only", metavar="SLUG_OR_ID", action="append", default=[],
                    help="restrict to specific skill(s) (repeatable)")
    args = ap.parse_args()

    base_url, token = _load_env()
    id_index, slug_index = _index_disk_mirrors()
    skills = fetch_skills(base_url, token, id_index)

    selection = list(args.only) + list(args.install)
    skills = _selected(skills, selection)

    if args.check:
        return run_check(skills, id_index, slug_index, args.install_root)
    return run_write(skills, id_index, slug_index, args.install_root, install_only=bool(args.install))


if __name__ == "__main__":
    raise SystemExit(main())
