#!/usr/bin/env python3
"""
sync_skills.py — reconcile on-disk Claude Code SKILL.md files with their
canonical Neotoma `skill` entities.

Neotoma `skill` entities are canonical (edited via `neotoma corrections create`
on the `content` field, per the skill_md_neotoma_first rule). Each on-disk
`SKILL.md` is a generated MIRROR keyed by an `entity_id` in its frontmatter.
Nothing reconciled these before, so local mirrors silently drifted (a stale
`/end`) and entity-only skills never reached disk at all (`draft-rendered-page`
existed only in Neotoma, so it never loaded into any harness).

This is the sibling of render_agent_docs.py (which does the same for
`agent_definition` entities); it shares the same `_request`/`_load_env` shape
and the same `--check` discipline so both can run in pre-commit / CI.

What it does:
  * Pull every `skill` entity from Neotoma.
  * For each, locate its on-disk mirror by `entity_id` (searching the known
    skill roots), or by slug/name if no entity_id is on disk yet.
  * Rebuild the canonical SKILL.md (do-not-edit header + minimal frontmatter
    from the entity fields + the `content` body) and compare / write.

Two skill roots are handled:
  * USER root  — ~/.claude/skills/<slug>  (symlinks into the neotoma-prod
                 skills checkout; we write through the symlink to its target).
  * REPO root  — <repo>/.claude/skills/<slug>  (real dirs, committed).
  An entity's home is inferred from where its mirror already lives; a brand-new
  entity-only skill is installed to the root named by --install-root
  (default: repo).

Usage:
    sync_skills.py --check                 # exit 1 if any mirror differs / missing
    sync_skills.py                         # write all drifted mirrors (in place)
    sync_skills.py --install <slug|id>     # materialize one entity-only skill
    sync_skills.py --install <slug|id> --install-root user
    sync_skills.py --only <slug|id> [...]  # restrict to specific skills

Env: NEOTOMA_BASE_URL, NEOTOMA_BEARER_TOKEN (falls back to
~/.config/neotoma/.env). Read-only against Neotoma; never writes entities.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
import urllib.request
import urllib.error
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
REPO_SKILLS_DIR = REPO_ROOT / ".claude" / "skills"
USER_SKILLS_DIR = Path.home() / ".claude" / "skills"

DO_NOT_EDIT = (
    "<!-- Do not edit this file directly. Corrections go through "
    "`neotoma corrections create` on the skill entity's content field "
    "(skill_md_neotoma_first rule). This file is a generated mirror; the "
    "Neotoma `skill` entity is canonical. Regenerate with "
    "execution/scripts/sync_skills.py. -->\n"
)

# Frontmatter keys we project from the entity (used both when writing a
# brand-new mirror and when reconciling an existing one's drifted values).
# `content` is the body.
FM_SCALAR = ["name", "description", "slug", "user_invocable"]
FM_LIST = ["triggers", "supported_harnesses"]

# The frontmatter keys the ENTITY owns. Drift in any of these is a real defect:
# a harness reads `description` and `triggers` to decide whether to load a skill
# at all, so a stale value silently mis-advertises the skill's contract.
#
# Keys NOT listed here are harness-local (e.g. `entity_type`, `allowed-tools`,
# `model`) or mirror bookkeeping (`entity_id`). They are preserved verbatim and
# never reported as drift, because the entity has no opinion about them.
ENTITY_OWNED_FM_KEYS = tuple(FM_SCALAR) + tuple(FM_LIST)


# --------------------------------------------------------------------------- IO

def _load_env() -> tuple[str, str]:
    base_url = os.environ.get("NEOTOMA_BASE_URL", "")
    token = os.environ.get("NEOTOMA_BEARER_TOKEN", "")
    env_path = Path.home() / ".config" / "neotoma" / ".env"
    if (not base_url or not token) and env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            value = value.strip().strip('"').strip("'")
            if key == "NEOTOMA_BASE_URL" and not base_url:
                base_url = value
            elif key == "NEOTOMA_BEARER_TOKEN" and not token:
                token = value
    if not base_url:
        sys.exit("NEOTOMA_BASE_URL not set (env or ~/.config/neotoma/.env)")
    return base_url.rstrip("/"), token


def _request(url: str, token: str, payload: dict | None = None, retries: int = 5) -> dict:
    last = None
    for _ in range(retries):
        try:
            req = urllib.request.Request(url)
            req.add_header("User-Agent", "ateles-neotoma-sync/1.0")
            if token:
                req.add_header("Authorization", f"Bearer {token}")
            if payload is not None:
                req.add_header("Content-Type", "application/json")
                req.data = json.dumps(payload).encode()
            with urllib.request.urlopen(req, timeout=30) as resp:
                return json.loads(resp.read().decode())
        except (urllib.error.URLError, ConnectionError) as exc:
            last = exc
            time.sleep(2)
    raise SystemExit(f"Neotoma unreachable after {retries} tries: {last}")


def _unwrap(entity: dict) -> dict:
    s = entity.get("snapshot", entity)
    if isinstance(s.get("snapshot"), dict):
        s = s["snapshot"]
    return s


def fetch_skills(base_url: str, token: str, disk_id_index: dict[str, Path] | None = None) -> list[dict]:
    data = _request(
        f"{base_url}/entities/query", token, {"entity_type": "skill", "limit": 500}
    )
    ents = data.get("entities") or data.get("results") or []
    by_slug: dict[str, list[dict]] = {}
    for e in ents:
        s = _unwrap(e)
        name = s.get("name")
        content = s.get("content") or ""
        # A syncable skill needs a name and a real body.
        if not name or not content.strip():
            continue
        s["_entity_id"] = e.get("entity_id") or s.get("entity_id", "")
        s["_slug"] = s.get("slug") or name
        by_slug.setdefault(s["_slug"], []).append(s)

    disk_id_index = disk_id_index or {}
    skills: list[dict] = []
    for slug, group in by_slug.items():
        if len(group) == 1:
            skills.append(group[0])
            continue
        # Duplicate slug in Neotoma. Prefer the entity already mirrored on disk;
        # else the longest content (most-developed). Warn either way.
        on_disk = [g for g in group if g["_entity_id"] in disk_id_index]
        chosen = (on_disk or sorted(group, key=lambda g: len(g["content"]), reverse=True))[0]
        ids = ", ".join(g["_entity_id"] for g in group)
        print(
            f"WARN duplicate skill slug {slug!r} across {len(group)} entities "
            f"({ids}); using {chosen['_entity_id']}"
            f"{' (on disk)' if on_disk else ' (longest content)'}.",
            file=sys.stderr,
        )
        skills.append(chosen)
    skills.sort(key=lambda s: s["_slug"])
    return skills


# --------------------------------------------------------------- rendering

def _yaml_scalar(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    s = str(v)
    # quote if it contains a colon-space or leading special char
    if any(t in s for t in [": ", " #"]) or s[:1] in "[]{}#&*!|>%@`\"'":
        return json.dumps(s, ensure_ascii=False)
    return s


def _fm_inner(fm_block: str) -> tuple[str, list[str], str]:
    """Split a frontmatter block into (leading_header, yaml_lines, trailing).

    `fm_block` is what _split_frontmatter returns: an optional leading HTML
    comment, then `---`, the YAML lines, then the closing `---`. Returns the
    header+opening fence, the YAML body lines (no fences, keepends stripped),
    and the closing fence line.
    """
    lines = fm_block.splitlines(keepends=True)
    open_idx = next((i for i, ln in enumerate(lines) if ln.strip() == "---"), None)
    if open_idx is None:
        return fm_block, [], ""
    close_idx = next(
        (i for i in range(len(lines) - 1, open_idx, -1) if lines[i].strip() == "---"),
        None,
    )
    if close_idx is None:
        return fm_block, [], ""
    head = "".join(lines[: open_idx + 1])
    inner = [ln.rstrip("\n") for ln in lines[open_idx + 1 : close_idx]]
    tail = lines[close_idx]
    return head, inner, tail


def _unquote(s: str):
    """Decode a scalar the way our own writer and common YAML encode it.

    Deliberately narrow: this handles the shapes that actually occur in skill
    frontmatter (plain, single- and double-quoted, and the booleans/None our
    writer emits). It is NOT a general YAML implementation.
    """
    s = s.strip()
    if len(s) >= 2 and s[0] == s[-1] and s[0] in "\"'":
        if s[0] == '"':
            try:
                return json.loads(s)
            except Exception:
                return s[1:-1]
        return s[1:-1].replace("''", "'")
    if s in ("true", "True"):
        return True
    if s in ("false", "False"):
        return False
    if s in ("null", "~", ""):
        return None
    return s


def parse_frontmatter_values(fm_block: str) -> dict:
    """Parse a frontmatter block to a dict of KEY -> VALUE.

    This is what makes drift detection value-level rather than text-level: two
    blocks that differ only in quoting, key order, or how a long string is
    wrapped parse to equal dicts, so reconciling never churns formatting. Only a
    genuine change in a value shows up as a difference.

    Supports the shapes present in this repo's mirrors:
      * plain / quoted scalars            key: value
      * block lists                       key:\n  - a\n  - b
      * inline flow lists                 key: [a, b]
      * folded / literal block scalars    key: >\n  wrapped text...
    Unrecognized constructs are recorded as raw strings; they are still compared
    consistently, they just are not interpreted.
    """
    _, inner, _ = _fm_inner(fm_block)
    out: dict = {}
    i = 0
    while i < len(inner):
        raw = inner[i]
        if not raw.strip() or raw.lstrip().startswith("#"):
            i += 1
            continue
        if raw[:1] in " \t" or ":" not in raw:
            i += 1
            continue
        key, _, rest = raw.partition(":")
        key = key.strip()
        rest = rest.strip()
        i += 1

        if rest.startswith("[") and rest.endswith("]"):
            body = rest[1:-1].strip()
            out[key] = [_unquote(x) for x in body.split(",") if x.strip()] if body else []
            continue

        if rest[:1] in (">", "|"):
            # Folded (>) or literal (|) block scalar: consume the indented run.
            chunks: list[str] = []
            while i < len(inner) and (not inner[i].strip() or inner[i][:1] in " \t"):
                chunks.append(inner[i].strip())
                i += 1
            while chunks and not chunks[-1]:
                chunks.pop()
            if rest[:1] == "|":
                out[key] = "\n".join(chunks)
            else:
                # Folded: blank lines become paragraph breaks, others join with a
                # space. This is what makes re-wrapping invisible to the compare.
                text, prev_blank = "", False
                for c in chunks:
                    if not c:
                        prev_blank = True
                        continue
                    if not text:
                        text = c
                    elif prev_blank:
                        text += "\n" + c
                    else:
                        text += " " + c
                    prev_blank = False
                out[key] = text
            continue

        if rest == "":
            # Either a block list or an empty value.
            items: list = []
            saw_item = False
            while i < len(inner) and (not inner[i].strip() or inner[i][:1] in " \t"):
                stripped = inner[i].strip()
                if stripped.startswith("- "):
                    saw_item = True
                    items.append(_unquote(stripped[2:]))
                elif stripped == "-":
                    saw_item = True
                    items.append(None)
                elif not stripped:
                    pass
                else:
                    # nested mapping or other structure — keep raw, do not guess
                    items.append(stripped)
                    saw_item = True
                i += 1
            out[key] = items if saw_item else None
            continue

        out[key] = _unquote(rest)
    return out


def _split_frontmatter(text: str) -> tuple[str, str]:
    """Return (frontmatter_block_including_fences_and_leading_header, body).

    Handles an optional leading HTML comment (do-not-edit header) before the
    `---` fences, then the YAML block, then the body. If no frontmatter is
    found, frontmatter_block is "" and body is the whole text.
    """
    lines = text.splitlines(keepends=True)
    i = 0
    lead = ""
    # consume a leading HTML comment + blank lines
    if i < len(lines) and lines[i].lstrip().startswith("<!--"):
        while i < len(lines):
            lead += lines[i]
            if "-->" in lines[i]:
                i += 1
                break
            i += 1
        while i < len(lines) and lines[i].strip() == "":
            lead += lines[i]
            i += 1
    if i < len(lines) and lines[i].strip() == "---":
        fm = lead + lines[i]
        i += 1
        while i < len(lines):
            fm += lines[i]
            if lines[i].strip() == "---":
                i += 1
                break
            i += 1
        body = "".join(lines[i:])
        return fm, body
    return "", text


def _fresh_frontmatter(skill: dict) -> str:
    """Build minimal frontmatter for a brand-new mirror (no existing file)."""
    fm_lines = ["---"]
    for k in FM_SCALAR:
        if skill.get(k) is not None and skill.get(k) != "":
            fm_lines.append(f"{k}: {_yaml_scalar(skill[k])}")
    for k in FM_LIST:
        vals = skill.get(k)
        if isinstance(vals, str):
            try:
                vals = json.loads(vals)
            except Exception:
                vals = [vals]
        if vals:
            fm_lines.append(f"{k}:")
            for item in vals:
                fm_lines.append(f"  - {_yaml_scalar(item)}")
    fm_lines.append(f"entity_id: {skill['_entity_id']}")
    fm_lines.append("---")
    return "\n".join(fm_lines) + "\n"


def _entity_fm_values(skill: dict) -> dict:
    """The frontmatter values the ENTITY asserts, normalized for comparison.

    Only keys the entity actually carries are returned — a key the entity leaves
    unset is not drift, it is simply not owned, so the mirror's value stands.
    """
    vals: dict = {}
    for k in FM_SCALAR:
        v = skill.get(k)
        if v is None or v == "":
            continue
        vals[k] = v.strip() if isinstance(v, str) else v
    for k in FM_LIST:
        v = skill.get(k)
        if isinstance(v, str):
            try:
                v = json.loads(v)
            except Exception:
                v = [v]
        if not v:
            continue
        vals[k] = [x.strip() if isinstance(x, str) else x for x in v]
    return vals


def _values_equal(disk, entity) -> bool:
    """Compare a parsed on-disk value against an entity value.

    Strings compare on whitespace-collapsed content so that re-wrapping a folded
    scalar, or a trailing newline, is not drift. Lists compare element-wise
    under the same rule. This is the line between VALUE drift (real, reported)
    and FORMATTING churn (invisible, never rewritten).
    """
    def norm(x):
        if isinstance(x, str):
            return " ".join(x.split())
        if isinstance(x, bool) or x is None:
            return x
        if isinstance(x, (int, float)):
            return str(x)
        return x

    if isinstance(entity, list) or isinstance(disk, list):
        d = disk if isinstance(disk, list) else ([] if disk is None else [disk])
        e = entity if isinstance(entity, list) else ([] if entity is None else [entity])
        if len(d) != len(e):
            return False
        return all(norm(a) == norm(b) for a, b in zip(d, e))
    if isinstance(entity, bool) or isinstance(disk, bool):
        def as_bool(x):
            if isinstance(x, bool):
                return x
            if isinstance(x, str):
                return x.strip().lower() in ("true", "yes", "1")
            return x
        return as_bool(disk) == as_bool(entity)
    return norm(disk) == norm(entity)


def frontmatter_drift(skill: dict, existing_fm: str) -> list[str]:
    """Return the entity-owned frontmatter keys whose VALUE differs on disk.

    Empty list == the mirror advertises what the entity says, whatever the
    formatting looks like.
    """
    disk_vals = parse_frontmatter_values(existing_fm)
    entity_vals = _entity_fm_values(skill)
    drifted = []
    for key in ENTITY_OWNED_FM_KEYS:
        if key not in entity_vals:
            continue
        if not _values_equal(disk_vals.get(key), entity_vals[key]):
            drifted.append(key)
    return drifted


def _render_fm_entry(key: str, value) -> list[str]:
    """Render one frontmatter key back to YAML lines, in our canonical style."""
    if isinstance(value, list):
        lines = [f"{key}:"]
        lines += [f"  - {_yaml_scalar(item)}" for item in value]
        return lines
    return [f"{key}: {_yaml_scalar(value)}"]


def _reconcile_frontmatter(existing_fm: str, skill: dict, drifted: list[str]) -> str:
    """Rewrite ONLY the drifted keys in place, preserving everything else.

    Preserved verbatim: the do-not-edit header, `entity_id`, key ORDER, and any
    harness-local key the entity does not own. Non-drifted entity keys keep
    their existing formatting too — including folded block scalars — because a
    key that already says the right thing is never re-rendered. That is what
    keeps a reconcile from churning the 90+ mirrors that are already correct.
    """
    if not drifted:
        return existing_fm
    head, inner, tail = _fm_inner(existing_fm)
    if not tail:
        return existing_fm

    entity_vals = _entity_fm_values(skill)
    out: list[str] = []
    seen: set[str] = set()
    i = 0
    while i < len(inner):
        raw = inner[i]
        # Identify the key this line opens, if any.
        key = None
        if raw.strip() and not raw.lstrip().startswith("#") and raw[:1] not in " \t" and ":" in raw:
            key = raw.partition(":")[0].strip()

        if key in drifted:
            seen.add(key)
            out += _render_fm_entry(key, entity_vals[key])
            # Skip this key's continuation lines (block list items, folded text).
            i += 1
            while i < len(inner) and (not inner[i].strip() or inner[i][:1] in " \t"):
                i += 1
            continue

        out.append(raw)
        if key:
            seen.add(key)
        i += 1

    # A drifted key that was absent from the file entirely: append before the
    # closing fence so it starts being advertised.
    for key in drifted:
        if key not in seen:
            out += _render_fm_entry(key, entity_vals[key])

    return head + "".join(ln + "\n" for ln in out) + tail


def canonical_text(skill: dict, existing: str | None) -> str:
    """The on-disk text this skill SHOULD have.

    The entity's `content` may itself be either body-only OR a full document
    that already begins with its own `---` frontmatter block — both shapes occur
    in prod. Split content into (its own fm, its body) first so we never stack
    two frontmatter blocks.

    Frontmatter precedence: the existing file's fm, RECONCILED against the
    entity's own values → else the entity content's own fm → else minimal
    generated fm. Exactly one block is emitted, with `entity_id` guaranteed
    present in it.

    "Reconciled" rather than "preserved": the entity owns `description`,
    `triggers`, `slug`, `user_invocable`, `supported_harnesses` and `name`, so a
    change to any of them must reach the mirror — a harness reads `description`
    and `triggers` to decide whether to load the skill at all. Only the keys
    whose parsed VALUE actually differs are rewritten; everything else (header,
    `entity_id`, key order, harness-local keys, and the formatting of keys that
    already agree) is preserved byte-for-byte, so a reconcile still never churns
    formatting or ordering. That was the original intent of preserving the block
    wholesale, and it is kept — what is dropped is the part that made
    entity-side changes permanently invisible to `--check`.
    """
    content_fm, content_body = _split_frontmatter(skill["content"])
    body = content_body.strip("\n") + "\n"

    existing_fm = ""
    if existing:
        existing_fm, _ = _split_frontmatter(existing)

    if existing_fm:
        drifted = frontmatter_drift(skill, existing_fm)
        fm_block = _reconcile_frontmatter(existing_fm, skill, drifted)
    elif content_fm:
        # content's fm may already carry its own do-not-edit header (captured by
        # _split_frontmatter); only prepend ours if it doesn't, to avoid stacking
        # two header comments.
        header = "" if content_fm.lstrip().startswith("<!--") else DO_NOT_EDIT
        fm_block = header + _ensure_entity_id(content_fm, skill["_entity_id"])
    else:
        fm_block = DO_NOT_EDIT + _fresh_frontmatter(skill)

    return fm_block.rstrip("\n") + "\n\n" + body


def _ensure_entity_id(fm_block: str, entity_id: str) -> str:
    """Return the YAML frontmatter block with an `entity_id:` line present.

    `fm_block` includes its `---` fences (and may include a leading HTML
    comment). If it already declares entity_id, return unchanged; else insert
    the line just before the closing fence.
    """
    if "entity_id:" in fm_block:
        return fm_block
    lines = fm_block.splitlines(keepends=True)
    # find the LAST '---' fence (the closer) and insert before it
    for idx in range(len(lines) - 1, -1, -1):
        if lines[idx].strip() == "---":
            lines.insert(idx, f"entity_id: {entity_id}\n")
            break
    return "".join(lines)


# ------------------------------------------------------ disk discovery

def _index_disk_mirrors() -> tuple[dict[str, Path], dict[str, Path]]:
    """Return (by_entity_id, by_slug) → SKILL.md path, across both roots.

    The slug index (keyed on the skill's directory name) is a fallback for
    mirrors that exist on disk but carry no `entity_id` frontmatter (e.g. the
    neotoma-prod user-level skills), so they aren't misreported as "missing".
    User symlinks are resolved to their real target.
    """
    by_id: dict[str, Path] = {}
    by_slug: dict[str, Path] = {}
    for root in (REPO_SKILLS_DIR, USER_SKILLS_DIR):
        if not root.exists():
            continue
        for skill_md in root.glob("*/SKILL.md"):
            slug = skill_md.parent.name
            by_slug.setdefault(slug, skill_md.resolve())
            try:
                head = skill_md.read_text(errors="replace")[:2000]
            except OSError:
                continue
            for line in head.splitlines():
                line = line.strip()
                if line.startswith("entity_id:"):
                    by_id[line.split(":", 1)[1].strip()] = skill_md.resolve()
                    break
    return by_id, by_slug


def _target_path(skill: dict, disk_id_index: dict[str, Path],
                 disk_slug_index: dict[str, Path], install_root: str) -> Path:
    eid = skill["_entity_id"]
    if eid in disk_id_index:
        return disk_id_index[eid]
    if skill["_slug"] in disk_slug_index:
        # present on disk but unlinked by entity_id — treat as its mirror
        return disk_slug_index[skill["_slug"]]
    # not on disk anywhere → install to the chosen root, by slug
    root = USER_SKILLS_DIR if install_root == "user" else REPO_SKILLS_DIR
    return (root / skill["_slug"] / "SKILL.md").resolve()


# --------------------------------------------------------------- ops

def _selected(skills: list[dict], only: list[str]) -> list[dict]:
    if not only:
        return skills
    want = set(only)
    sel = [s for s in skills if s["_slug"] in want or s["_entity_id"] in want]
    missing = want - {s["_slug"] for s in sel} - {s["_entity_id"] for s in sel}
    if missing:
        sys.exit(f"no skill entity matched: {', '.join(sorted(missing))}")
    return sel


def required_skill_rule_gaps(name: str, content: str) -> list[str]:
    """Rules 3–5 missing from a loaded skill body. Not a mirror drift signal."""
    text = content or ""
    gaps: list[str] = []
    if name == "writing-voice":
        emotion = (
            "evidence present → the claim only with that evidence shown; "
            "no evidence → omit the claim."
        )
        if emotion not in text or "## 3. Never invent" not in text:
            gaps.append("skill_rule_missing writing-voice 3")
    elif name == "email-mechanics":
        if "If showing the draft fails, say the show failed." not in text:
            gaps.append("skill_rule_missing email-mechanics 4")
        if (
            "names the discarded draft id" not in text
            or "the delete is permanent" not in text
        ):
            gaps.append("skill_rule_missing email-mechanics 5")
    return gaps


def run_check(skills: list[dict], id_index: dict, slug_index: dict, install_root: str) -> int:
    for s in skills:
        for line in required_skill_rule_gaps(s.get("_slug") or "", s.get("content") or ""):
            print(line)
    drift, missing = [], []
    for s in skills:
        path = _target_path(s, id_index, slug_index, install_root)
        if not path.exists():
            missing.append((s["_slug"], path))
            continue
        existing = path.read_text()
        if existing != canonical_text(s, existing):
            existing_fm, _ = _split_frontmatter(existing)
            fm_keys = frontmatter_drift(s, existing_fm) if existing_fm else []
            drift.append((s["_slug"], path, fm_keys))
    if not drift and not missing:
        print(f"OK — {len(skills)} skill mirror(s) match Neotoma "
              f"(body and entity-owned frontmatter).")
        return 0
    for slug, p in missing:
        print(f"MISSING  {slug:28} (entity-only; no mirror on disk) -> {p}")
    for slug, p, fm_keys in drift:
        why = f"frontmatter: {', '.join(fm_keys)}" if fm_keys else "body"
        print(f"DRIFTED  {slug:28} [{why}]  {p}")
    print(f"\n{len(missing)} missing, {len(drift)} drifted "
          f"(body or entity-owned frontmatter differs from Neotoma).")
    print("Run without --check to write, or --install <slug> for a missing one.")
    return 1


def run_write(skills: list[dict], id_index: dict, slug_index: dict, install_root: str,
              install_only: bool) -> int:
    wrote = []
    for s in skills:
        path = _target_path(s, id_index, slug_index, install_root)
        existed = path.exists()
        if install_only and existed:
            continue  # --install only materializes new ones
        existing = path.read_text() if existed else None
        canonical = canonical_text(s, existing)
        if existed and existing == canonical:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(canonical)
        wrote.append((s["_slug"], path, "installed" if not existed else "updated"))
    if not wrote:
        print("nothing to do — all mirrors current.")
        return 0
    print(f"wrote {len(wrote)} skill mirror(s):")
    for slug, p, kind in wrote:
        print(f"  {kind:9} {slug:28} {p}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Sync Neotoma skill entities → on-disk SKILL.md mirrors.")
    ap.add_argument("--check", action="store_true", help="report drift/missing, exit 1 if any; no writes")
    ap.add_argument("--install", metavar="SLUG_OR_ID", action="append", default=[],
                    help="materialize one entity-only skill to disk (repeatable)")
    ap.add_argument("--install-root", choices=["repo", "user"], default="repo",
                    help="where to install brand-new mirrors (default: repo)")
    ap.add_argument("--only", metavar="SLUG_OR_ID", action="append", default=[],
                    help="restrict to specific skill(s) (repeatable)")
    args = ap.parse_args()

    base_url, token = _load_env()
    id_index, slug_index = _index_disk_mirrors()
    skills = fetch_skills(base_url, token, id_index)

    selection = list(args.only) + list(args.install)
    skills = _selected(skills, selection)

    if args.check:
        return run_check(skills, id_index, slug_index, args.install_root)
    return run_write(skills, id_index, slug_index, args.install_root, install_only=bool(args.install))


if __name__ == "__main__":
    raise SystemExit(main())
