"""
Tests for render_positioning_docs.py and the shared neotoma_mirror_lib.py
observation-id stamping helper.

Two kinds of test here:
  1. Pure-function tests (PII scrub, frontmatter/observation-id rendering) —
     no network, always run.
  2. A filesystem doc-sync contract test — asserts every file under
     docs/positioning/ carries the generated-mirror header and, when it has
     an `observation_ids:` block, that every entry in it is either a
     plausible observation id or the literal `unknown` sentinel. This is a
     pure filesystem check (same pattern as test_render_agent_docs.py) and
     always runs; it does not require live Neotoma.

Run with: pytest execution/scripts/test_render_positioning_docs.py -v
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_REPO_ROOT / "execution" / "scripts"))

import render_positioning_docs as rpd  # noqa: E402
from neotoma_mirror_lib import observation_ids_block, yaml_scalar  # noqa: E402

POSITIONING_DIR = _REPO_ROOT / "docs" / "positioning"
OBS_ID_LINE_RE = re.compile(
    r"^\s+([a-zA-Z0-9_]+):\s+(unknown|[0-9a-f-]{8,}(?:,[0-9a-f-]{8,})*)\s*$"
)


class TestObservationIdsBlock:
    def test_stamps_every_requested_field(self) -> None:
        provenance = {"a": "obs-1", "b": "obs-2"}
        lines = observation_ids_block(provenance, ("a", "b", "c"))
        assert lines[0] == "observation_ids:"
        assert "  a: obs-1" in lines
        assert "  b: obs-2" in lines
        # A field absent from provenance is stamped `unknown`, never omitted —
        # an unstamped field must read as "freshness not verifiable," never as
        # "this field is fine" (fail-closed discipline).
        assert "  c: unknown" in lines

    def test_empty_provenance_stamps_all_unknown(self) -> None:
        lines = observation_ids_block({}, ("x", "y"))
        assert lines == ["observation_ids:", "  x: unknown", "  y: unknown"]


class TestYamlScalar:
    def test_plain_scalar_unquoted(self) -> None:
        assert yaml_scalar("hello") == "hello"

    def test_scalar_with_colon_is_quoted(self) -> None:
        assert yaml_scalar("a: b") == '"a: b"'

    def test_empty_string_quoted(self) -> None:
        assert yaml_scalar("") == '""'


class TestEvaluatorPiiScrub:
    def test_known_names_are_scrubbed(self) -> None:
        text = (
            "Rebecca reported an issue; Simon Bergeron agreed; "
            "Sidney Brown, Jacob Cohen, Brandon/AIBTC, and Mark were named."
        )
        scrubbed = rpd._scrub_evaluator_pii(text)
        assert "Rebecca" not in scrubbed
        assert "Bergeron" not in scrubbed
        assert "Sidney" not in scrubbed
        assert "Jacob" not in scrubbed
        assert "Brandon" not in scrubbed
        assert "Mark" not in scrubbed
        assert "an evaluator" in scrubbed

    def test_known_entity_ids_are_scrubbed(self) -> None:
        text = "see (ent_aaa12264742df8597df6b15f) for detail"
        scrubbed = rpd._scrub_evaluator_pii(text)
        assert "ent_aaa12264742df8597df6b15f" not in scrubbed
        assert "[evaluator-record]" in scrubbed

    def test_source_list_drops_customer_development_note_markers(self) -> None:
        items = [
            "customer_development_note ent_f9bfda2a86f54dc1b72962cb (a call)",
            "docs/icp.md @ origin/main",
        ]
        kept = rpd._scrub_source_list(items)
        assert len(kept) == 1
        assert "docs/icp.md" in kept[0]

    def test_unrelated_text_untouched(self) -> None:
        text = "LangGraph's Item class has no attribution field."
        assert rpd._scrub_evaluator_pii(text) == text


class TestRenderEntityFile:
    def test_target_persona_renders_frontmatter_and_body(self) -> None:
        snapshot = {
            "name": "Test persona",
            "product": "Ateles",
            "archetype": "A solo operator",
            "messaging_bad": "Not for Rebecca-style enterprise teams",
        }
        provenance = {"name": "obs-1", "product": "obs-1", "archetype": "obs-2"}
        content = rpd.render_entity_file(
            "ent_test000000000000000000", "target_persona", snapshot, provenance
        )
        assert "entity_id: ent_test000000000000000000" in content
        assert "entity_type: target_persona" in content
        assert "observation_ids:" in content
        assert "## Archetype" in content
        assert "A solo operator" in content
        # PII scrub applies to body sections too.
        assert "Rebecca" not in content
        assert "an evaluator" in content

    def test_generated_mirror_header_present(self) -> None:
        content = rpd.render_entity_file(
            "ent_test000000000000000000", "target_persona", {"name": "x"}, {}
        )
        assert "generated mirror of a Neotoma entity" in content
        assert "Do not edit this file directly" in content


class TestDocSyncFilesystemContract:
    """Pure filesystem checks — always run, no live Neotoma required.

    Mirrors test_render_agent_docs.py's pattern: assert properties of
    whatever is currently checked in under docs/positioning/, rather than
    re-fetching from Neotoma.
    """

    def test_every_positioning_file_carries_generated_header(self) -> None:
        if not POSITIONING_DIR.exists():
            return  # nothing rendered yet in this checkout — not a failure
        for path in POSITIONING_DIR.rglob("*.md"):
            content = path.read_text()
            assert "Do not edit this file directly" in content, (
                f"{path} is under docs/positioning/ but has no generated-mirror header"
            )

    def test_observation_id_lines_are_well_formed(self) -> None:
        if not POSITIONING_DIR.exists():
            return
        for path in POSITIONING_DIR.rglob("*.md"):
            if path.name == "README.md":
                continue
            content = path.read_text()
            if "observation_ids:" not in content:
                continue
            block = content.split("observation_ids:", 1)[1].split("---", 1)[0]
            for line in block.splitlines():
                if not line.strip():
                    continue
                assert OBS_ID_LINE_RE.match(line), f"{path}: malformed observation_ids line: {line!r}"

    def test_no_known_evaluator_name_leaks_into_positioning_docs(self) -> None:
        if not POSITIONING_DIR.exists():
            return
        banned = ("Jeremiah Lee", "Simon Bergeron")
        for path in POSITIONING_DIR.rglob("*.md"):
            content = path.read_text()
            for name in banned:
                assert name not in content, f"{path} leaks evaluator name {name!r}"
