"""minimal_markdown.py — a small, dependency-free Markdown-to-HTML converter.

WHY A HAND-ROLLED CONVERTER: this repo's generator scripts
(render_plan_docs.py, render_agent_docs.py, the hooks) run stdlib-only Python
with no third-party dependency, and no Markdown library is pinned in
pyproject.toml / scripts/requirements.txt. Adding one for a single generator
would be the first third-party dependency this class of script has ever
needed, so this module covers the actual subset of Markdown that
render_agent_docs.py / render_positioning_docs.py-style mirrors produce:
headings, paragraphs, bold/italic, inline code, links, and simple bullet
lists. It is NOT a general CommonMark implementation — do not extend it to
handle syntax it does not need; reach for a real dependency if the mirror
content grows past this.

Frontmatter (a leading `---\\n...\\n---` block) is stripped by the caller
before this module sees the body, since frontmatter parsing belongs to the
positioning-mirror reader, not to Markdown rendering.
"""

from __future__ import annotations

import html
import re

_INLINE_CODE = re.compile(r"`([^`]+)`")
_BOLD = re.compile(r"\*\*([^*]+)\*\*")
_ITALIC = re.compile(r"(?<!\*)\*([^*]+)\*(?!\*)")
_LINK = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
_HEADING = re.compile(r"^(#{1,6})\s+(.*)$")
_BULLET = re.compile(r"^[-*]\s+(.*)$")


def _inline(text: str) -> str:
    text = html.escape(text, quote=False)
    text = _INLINE_CODE.sub(r"<code>\1</code>", text)
    text = _LINK.sub(r'<a href="\2">\1</a>', text)
    text = _BOLD.sub(r"<strong>\1</strong>", text)
    text = _ITALIC.sub(r"<em>\1</em>", text)
    return text


def to_html(markdown_text: str) -> str:
    """Convert the supported Markdown subset to HTML fragments (no wrapping
    <html>/<body> — caller embeds this into a page template)."""
    lines = markdown_text.replace("\r\n", "\n").split("\n")
    out: list[str] = []
    para_buf: list[str] = []
    list_buf: list[str] = []

    def flush_para():
        if para_buf:
            out.append(f"<p>{_inline(' '.join(para_buf))}</p>")
            para_buf.clear()

    def flush_list():
        if list_buf:
            items = "".join(f"<li>{_inline(i)}</li>" for i in list_buf)
            out.append(f"<ul>{items}</ul>")
            list_buf.clear()

    for raw_line in lines:
        line = raw_line.rstrip()
        if not line.strip():
            flush_para()
            flush_list()
            continue
        heading = _HEADING.match(line)
        if heading:
            flush_para()
            flush_list()
            level = len(heading.group(1))
            out.append(f"<h{level}>{_inline(heading.group(2))}</h{level}>")
            continue
        bullet = _BULLET.match(line)
        if bullet:
            flush_para()
            list_buf.append(bullet.group(1))
            continue
        flush_list()
        para_buf.append(line.strip())

    flush_para()
    flush_list()
    return "\n".join(out)


_LEADING_HTML_COMMENT = re.compile(r"^\s*<!--.*?-->\s*\n?", re.DOTALL)


def strip_frontmatter(text: str) -> tuple[dict, str]:
    """Split a `---\\nkey: value\\n---\\nbody` file into (frontmatter_dict,
    body). Frontmatter parsing here is intentionally minimal (flat
    `key: value` scalars only, plus `key:` followed by indented `- item`
    lists) — enough for the render_positioning_docs.py / render_agent_docs.py
    frontmatter shape without pulling in a YAML dependency this script class
    has never needed.

    Every projection generator in this repo (render_plan_docs.py,
    render_agent_docs.py, render_positioning_docs.py) leads its output with
    a "do not edit this file directly" HTML comment BEFORE the YAML
    frontmatter block, so that comment is stripped first -- otherwise the
    leading `<!--` means the file does not start with `---` and this
    function silently treats the whole file (comment, frontmatter, and all)
    as body text, which is exactly what a first pass of this module did."""
    text = _LEADING_HTML_COMMENT.sub("", text, count=1)
    if not text.startswith("---"):
        return {}, text
    parts = text.split("\n---", 1)
    if len(parts) != 2:
        return {}, text
    fm_block = parts[0][3:].strip("\n")
    body = parts[1].lstrip("\n")

    fm: dict = {}
    current_list_key: str | None = None
    for raw_line in fm_block.split("\n"):
        if not raw_line.strip():
            continue
        if raw_line.startswith("  - ") and current_list_key:
            fm.setdefault(current_list_key, [])
            fm[current_list_key].append(raw_line.strip()[2:].strip())
            continue
        if ":" in raw_line and not raw_line.startswith(" "):
            key, _, value = raw_line.partition(":")
            key = key.strip()
            value = value.strip()
            if value:
                fm[key] = value.strip('"')
                current_list_key = None
            else:
                current_list_key = key
    return fm, body
