#!/bin/bash
# Interactive TP-Link Router Configuration Script
# This script guides you through configuring your TP-Link router for HomeKit mDNS

set -e

echo "=========================================="
echo "TP-Link Router Configuration for HomeKit"
echo "=========================================="
echo ""
echo "This script will guide you through configuring your TP-Link router"
echo "to enable mDNS/Bonjour forwarding for HomeKit automatic discovery."
echo ""
echo "Router IP: 192.168.0.1"
echo ""

# Check if router is accessible
echo "Checking router accessibility..."
if curl -s --connect-timeout 3 http://192.168.0.1 > /dev/null 2>&1; then
    echo "✅ Router is accessible at http://192.168.0.1"
else
    echo "❌ Cannot reach router at http://192.168.0.1"
    echo "   Please check:"
    echo "   - Router is powered on"
    echo "   - You're connected to the network"
    echo "   - Router IP is correct"
    exit 1
fi

echo ""
echo "=========================================="
echo "Step 1: Open Router Admin"
echo "=========================================="
echo ""
echo "1. Open a web browser"
echo "2. Navigate to: http://tplinkwifi.net or http://192.168.0.1"
echo "3. Login with your admin credentials"
echo ""
read -p "Press Enter when you've logged into the router admin panel..."

echo ""
echo "=========================================="
echo "Step 2: Enable IGMP Snooping"
echo "=========================================="
echo ""
echo "Navigate to: Advanced → Network → IGMP Snooping"
echo ""
echo "1. Click 'Advanced' in the top menu"
echo "2. Click 'Network' in the left sidebar"
echo "3. Click 'IGMP Snooping'"
echo "4. Enable 'IGMP Snooping' (toggle ON)"
echo "5. Click 'Save'"
echo ""
read -p "Press Enter when you've enabled IGMP Snooping..."

echo ""
echo "=========================================="
echo "Step 3: Enable UPnP"
echo "=========================================="
echo ""
echo "Navigate to: Advanced → NAT Forwarding → UPnP"
echo ""
echo "1. Click 'Advanced' in the top menu"
echo "2. Click 'NAT Forwarding' in the left sidebar"
echo "3. Click 'UPnP'"
echo "4. Enable 'UPnP' (toggle ON)"
echo "5. Click 'Save'"
echo ""
read -p "Press Enter when you've enabled UPnP..."

echo ""
echo "=========================================="
echo "Step 4: Check for mDNS (Optional)"
echo "=========================================="
echo ""
echo "Some newer TP-Link models have explicit mDNS settings."
echo ""
echo "Navigate to: Advanced → System Tools → mDNS"
echo ""
echo "If you see an mDNS option:"
echo "1. Enable it (toggle ON)"
echo "2. Click 'Save'"
echo ""
echo "If you don't see mDNS, that's OK - IGMP Snooping + UPnP should be sufficient."
echo ""
read -p "Press Enter to continue..."

echo ""
echo "=========================================="
echo "Step 5: Restart Router"
echo "=========================================="
echo ""
echo "Navigate to: System Tools → Reboot"
echo ""
echo "1. Click 'System Tools' in the top menu"
echo "2. Click 'Reboot' in the left sidebar"
echo "3. Click 'Reboot' button"
echo "4. Wait 2-3 minutes for router to restart"
echo ""
read -p "Press Enter when router has restarted..."

echo ""
echo "=========================================="
echo "Step 6: Test mDNS"
echo "=========================================="
echo ""
echo "Testing mDNS discovery..."
echo ""

# Check if dns-sd is available
if command -v dns-sd &> /dev/null; then
    echo "Starting mDNS discovery test..."
    echo "You should see HomeKit devices appear below."
    echo "Press Ctrl+C to stop the test."
    echo ""
    sleep 2
    dns-sd -B _hap._tcp
else
    echo "dns-sd not found. Install Bonjour tools:"
    echo "  brew install bonjour"
    echo ""
    echo "Or test from iPhone/iPad:"
    echo "  1. Open Home app"
    echo "  2. Tap '+' → 'Add Accessory'"
    echo "  3. You should see 'HASS Bridge' appear automatically"
fi

echo ""
echo "=========================================="
echo "Configuration Complete!"
echo "=========================================="
echo ""
echo "If mDNS is working, you should see HomeKit devices in the test above."
echo ""
echo "To test from iPhone/iPad:"
echo "  1. Open Home app"
echo "  2. Tap '+' → 'Add Accessory'"
echo "  3. 'HASS Bridge' should appear automatically"
echo ""
echo "If it doesn't appear, you can still use manual pairing:"
echo "  IP: 192.168.0.252:21064"
echo "  Code: 471-42-540"
echo ""
